amake system update

diff --git a/aubit4glsrc/trunk/bin/4glpc b/aubit4glsrc/trunk/bin/4glpc
--- a/aubit4glsrc/trunk/bin/4glpc
+++ b/aubit4glsrc/trunk/bin/4glpc
@@ -356,7 +356,7 @@ do
 						cat $errfname | grep -B $GOBACKLINES -A $GOAFTERLINES $ERRCHAR
                     else
 						echo "============ FIRST ERROR: =============="
-						$HEAD $errfname  >> $ERRORLOG
+						$HEAD $errfname
                     fi
                     echo "========================================"
                 fi
@@ -429,7 +429,7 @@ do
 	          $output "$fname: "
 			  $output ODBC_LIB_DIR is $ODBC_LIB_DIR
 			  $output LD_LIBRARY_PATH is $LD_LIBRARY_PATH
-              $output Executing: 4glc "$a"
+              $output "Executing (3) : 4glc $a"
           fi
 
           err_msg=`4glc "$a"`
@@ -448,7 +448,7 @@ do
 						cat $errfname | grep -B $GOBACKLINES -A $GOAFTERLINES $ERRCHAR
                     else
 						echo "============ FIRST ERROR: =============="
-						$HEAD $errfname  >> $ERRORLOG
+						$HEAD $errfname
                     fi
                     echo "========================================"
                 fi
@@ -456,19 +456,21 @@ do
 			else
 				 $output "Error compiling $a - error file NOT created"
             fi
-				  if [ "$A4GLVERBOSE" = "yes" ]
-				  then
-                    $output err_msg is: $err_msg
-                    $output err_code is: $err_code
-                    $output Please check file "$fname".err
-                    $output 'You can also "export DEBUG=ALL" to get "debug.out" file'
-                  fi
+			
+			if [ "$A4GLVERBOSE" = "yes" ]
+			then
+            	$output err_msg is: $err_msg
+                $output err_code is: $err_code
+                $output Please check file "$fname".err
+                $output 'You can also "export DEBUG=ALL" to get "debug.out" file'
+            fi
 
-				if [ "$A4GLVERBOSE" = "yes" ]
-				then
-			        echo "Exiting with code $err_code"
-			    fi
-				exit $err_code
+			if [ "$A4GLVERBOSE" = "yes" ]
+			then
+				echo "Exiting with code $err_code"
+			fi
+
+			exit $err_code
           fi
 
 		if [ -f $fname.c ]
@@ -488,7 +490,7 @@ do
 			if [ -x "$AUBITDIR/bin/loadmap" -a "$LOADMAP" != "N" ]
             then
                         $output "Loading map file for $a into database"
-                        loadmap $fname.map > /dev/null 2> /dev/null
+                        loadmap $fname.map > /dev/null 2> $fname.map.err
             fi
           fi
 
@@ -499,41 +501,60 @@ do
 
 			COMPCC="$COMPCC $fname.c"
         else
-			$output "Error compiling $a - $fname.c not generated, but no err code from 4glc"
-			if [ "$A4GLVERBOSE" = "yes" ]
-			then
-			  	if [ -f $errfname ]
-    	        then
-                    if test $SHOWERRCODE = "1"
-					then
-						ERRLINES=`cat $errfname | grep -c $ERRCHAR`
-	                    if [ "$ERRLINES" != "0" ]
-	                    then
-							echo "============ FIRST ERROR: =============="
-							cat $errfname | grep -B $GOBACKLINES -A $GOAFTERLINES $ERRCHAR
-	                    else
-							echo "============ FIRST ERROR: =============="
-							$HEAD $errfname  >> $ERRORLOG
-	                    fi
-	                    echo "========================================"
-					fi
-                    echo "see $errfname"
-                else
-					echo "Error file NOT created"
+            #is this a 0 length file?
+			FGLFILESIZE=$(ls -al $fname3 | awk '{print $5}')
+
+			if [ "$FGLFILESIZE" = "0" ]
+            then
+				if [ "$A4GLVERBOSE" = "yes" ]
+	    		then
+					echo "$fname3 size is $FGLFILESIZE"
                 fi
 
-				$output err_msg is: $err_msg
-                $output err_code is: $err_code
-                $output Please check file "$fname".err
-                $output 'You can also "export DEBUG=ALL" to get "debug.out" file'
-			fi
-            #we don't want to wxit with 0 here:
-            err_code=9
-			if [ "$A4GLVERBOSE" = "yes" ]
-			then
-				echo "Exiting with code $err_code"
-			fi
-			exit $err_code
+				#fakeing c file, to get empty object file from c compiler:
+				#Simplest way is before the 4glc call in 4glpc, 'touch' the required C
+				#file...
+
+				touch $fname.c
+				COMPCC="$COMPCC $fname.c"
+            else
+
+				$output "Error compiling $a - $fname.c not generated, but no err code from 4glc"
+				if [ "$A4GLVERBOSE" = "yes" ]
+				then
+				  	if [ -f $errfname ]
+	    	        then
+	                    if test $SHOWERRCODE = "1"
+						then
+							ERRLINES=`cat $errfname | grep -c $ERRCHAR`
+		                    if [ "$ERRLINES" != "0" ]
+		                    then
+								echo "============ FIRST ERROR: =============="
+								cat $errfname | grep -B $GOBACKLINES -A $GOAFTERLINES $ERRCHAR
+		                    else
+								echo "============ FIRST ERROR: =============="
+								$HEAD $errfname
+		                    fi
+		                    echo "========================================"
+						fi
+	                    echo "see $errfname"
+	                else
+						echo "Error file NOT created"
+	                fi
+
+					$output err_msg is: $err_msg
+	                $output err_code is: $err_code
+	                $output Please check file "$fname".err
+	                $output 'You can also "export DEBUG=ALL" to get "debug.out" file'
+				fi
+	            #we don't want to wxit with 0 here:
+	            err_code=9
+				if [ "$A4GLVERBOSE" = "yes" ]
+				then
+					echo "Exiting with code $err_code"
+				fi
+				exit $err_code
+            fi
 		fi
    ;;
 
@@ -771,21 +792,19 @@ then
 
    if [ "$A4GLVERBOSE" = "yes" ]
    then
-        $output executing: $EXEC
+        $output "executing (1) : $EXEC"
    fi
 
    	eval $EXEC
 	err_code=$?
 
-   if [ $err_code != 0 ]
-   then
-      if [ "$LAST" != "" ]
-      then
-		  errfname=`expr "$LAST" : "..\(.*\)"`
-		  #$output "Error compiling... check"`expr "$LAST" : "..\(.*\)"`
-          $output "Error compiling... check $errfname"
+	if [ $err_code != 0 ]
+	then
+		if [ "$LAST" != "" ]
+		then
+			errfname=`expr "$LAST" : "..\(.*\)"`
 
-            if test $SHOWERRCODE = "1"
+          	if test $SHOWERRCODE = "1"
 			then
 				ERRLINES=`cat $errfname | grep -c $ERRCHAR`
                 if [ "$ERRLINES" != "0" ]
@@ -794,10 +813,12 @@ then
 					cat $errfname | grep -B $GOBACKLINES -A $GOAFTERLINES $ERRCHAR
                 else
 					echo "============ FIRST ERROR: =============="
-					$HEAD $errfname  >> $ERRORLOG
+					$HEAD $errfname
                 fi
                 echo "========================================"
             fi
+
+			$output "Error compiling... check $errfname"
       else
 		  $output "Error compiling."
       fi
@@ -813,17 +834,16 @@ else
 
    if [ "$A4GLVERBOSE" = "yes" ]
    then
-	   $output executing: $DOIT $GCC $COMPCC  $INCLDIR  $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $LAST
+	   $output "executing (2) : $DOIT $GCC $COMPCC  $INCLDIR  $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $LAST"
    fi
 	eval $DOIT $GCC $COMPCC  $INCLDIR  $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $LAST
 	err_code=$?
-   if [ $err_code != 0 ]
-   then
-      if [ "$LAST" != "" ]
-      then
-		  errfname=`expr "$LAST" : "..\(.*\)"`
-		  #$output "Error compiling... check"`expr "$LAST" : "..\(.*\)"`
-          $output "Error compiling... check $errfname"
+
+	if [ $err_code != 0 ]
+	then
+		if [ "$LAST" != "" ]
+		then
+			errfname=`expr "$LAST" : "..\(.*\)"`
 
             if test $SHOWERRCODE = "1"
 			then
@@ -834,10 +854,11 @@ else
 					cat $errfname | grep -B $GOBACKLINES -A $GOAFTERLINES $ERRCHAR
                 else
 					echo "============ FIRST ERROR: =============="
-					$HEAD $errfname  >> $ERRORLOG
+					$HEAD $errfname
                 fi
                 echo "========================================"
             fi
+			$output "Error compiling... check $errfname"
 
 	  else
 		  $output "Error compiling."
diff --git a/aubit4glsrc/trunk/bin/prepmake b/aubit4glsrc/trunk/bin/prepmake
--- a/aubit4glsrc/trunk/bin/prepmake
+++ b/aubit4glsrc/trunk/bin/prepmake
@@ -1,119 +1,276 @@
 #!/bin/sh
-############################################################
-#   Aubit 4gl compiler - make system
-#prepmake - utillity script to convert makefiles
+##########################################################################
+#                  Aubit 4gl compiler - make system
+#    prepmake - utillity script to convert makefiles to amake format
+#    ---------------------------------------------------------------
+#                    See manual for information
 #
-#See manual for information
 #
-############################################################
-
-#Confirmed to work in :
-#gl
-#ap
-
-#$WARNING: some Maximise moduls depend on other modules already being
-#compiled. If they are not, makefile.prep will fail.
-#Compile modules in this order:
-#winds csimods main ar eo fa gl in jm lc qe re ss ap pu wo;
-
-
-#1. run "prepmake" in directory containing Maximise make file, "makefile".
+#Run "prepmake" in directory containing make file, "makefile".
 #This will create file "makefile.prep" containing instruction needed for
 #dumping program definitions to individual make files (*.mk). Note: this
-#functionallity depends on fact that all Maximise makefiles use command
+#functionallity depends on fact that all (Maximise) makefiles use command
 #"fgllink" somewhere in each defined prgram target, and list all source
 #files in dependencies. If for any reason this is not true for some makefie
 #you want to process, look at the script, it should be easy to substitute
 #this with some other present command.
+#
+#"prepmake" will then run first "touch *.4gl" (to force all targets into
+#thinking they need building) and then "make -f makefile.prep". This will
+#create one make file for each program defined in makefile.prep, named as
+#<progname>.mk, using script "genmake". Each .mk files will contain
+#definitions of include headers and footers, and names of source files
+#needed to build that program, and nothing else. allsinglelibs.mk will
+#also be created, and contain library objects - this file will probably
+#not need to be used, since all makefiles for building programs should
+#be able to build objects for themselves.
+#
+#WARNING: some Maximise moduls depend on other modules already being
+#compiled. If they are not, makefile.prep will fail.
+#Compile modules in this order:
+#	winds csimods main ar eo fa gl in jm lc qe re ss ap pu wo
+#
+#Confirmed to work in $MAXDIR:
+#
+#	winds
+#   ar
+#	gl
+#	ap
+#
+##########################################################################
 
-FILENAME=allsinglelibs.mk
-rm -f $FILENAME
-COMPOSITE=/tmp/makefile
+########################
+function replace {
+########################
 
-#replacing all "fgllink" lines with our command:
-#INCLCMT='	genmake $(basename $(@F)) $(addsuffix .4gl,$(basename $(^F))) #'
-#we don't want to rename ALL dependencies to .4gl they may be .per files!
-#INCLCMT='	genmake $(basename $(@F)) $(^F) #'
-#we alos don't want to strip extension from object name, it may be library
-#target, not executable:
-INCLCMT='	genmake $(@F) $(^F) #'
+    echo "Replacing    [$TOREPLACE]	with	[$INCLCMT]"
+	sed -e "s%$TOREPLACE%$INCLCMT%g" $RESULTMAKEFILE > $TMPCOMPOSITE
+	mv $TMPCOMPOSITE $RESULTMAKEFILE
 
-sed -e "s%fgllink%$INCLCMT%g" makefile > $COMPOSITE.tmp
-
-#commenting out all "cat" lines, so they don't get executed:
-INCLCMT2="#cat "
-sed -e "s%cat %$INCLCMT2%g" $COMPOSITE.tmp > makefile.prep
-
-
-################### for GL #################################
-#INCLCMT2='touch $(addsuffix .42m,$(basename $($<)))'
-#INCLCMT2='touch $(basename $<).42m'
-INCLCMT2='touch $(notdir $(basename $<)).42m'
-#replace all fglcomp lines with fakes, so we don't go trough actual compile:
-sed -e "s%fglcomp%$INCLCMT2%g" makefile.prep > $COMPOSITE.tmp
-
-#INCLCMT2='touch $(notdir $(basename $<)).42f'
-INCLCMT2='touch $(basename $<).42f'
-#replace all fglform lines with fakes, so we don't go trough actual compile:
-sed -e "s%fglform%$INCLCMT2%g" $COMPOSITE.tmp > makefile.prep
-
-INCLCMT2='touch $(basename $<).frm'
-sed -e "s%form4gl%$INCLCMT2%g" makefile.prep > $COMPOSITE.tmp
-
-cp $COMPOSITE.tmp makefile.prep
-################### end for GL #################################
-
-
-################### for winds #################################
-#we need all fglpc replaced with commands, since in winds most files
-#are not programs, but library functions.
-INCLCMT3='	genmake $(@F) $(^F) #'
-sed -e "s%fglpc%$INCLCMT3%g" makefile.prep > $COMPOSITE.tmp
-
-
-#but we also need to process fgllink, since it creates composite library
-#objects (.42x)
-
-cp $COMPOSITE.tmp makefile.prep
-
-
-#################### end for winds #############################
+}
 
 
 
-#2. run first "touch *.4gl" (to force all targets ito thinking they need
-#building) and then "make -f makefile.prep". This will create one make
-#file for each program defined in makefile.prep, named as <progname>.mk,
-#using script "genmake". Each .mk files will contain definitions of
-#include headers and footers, and names of source files needed to build
-#that program, and nothing else.
+########################
+function r_ln {
+########################
 
-touch *.4gl
-make -f makefile.prep
-RET=$?
+	#---------------------------------------------------------
+	TOREPLACE="ln "
+	INCLCMT='#'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+}
 
-echo " "
-if test $RET != "0"
-then
-    echo "Error preparing make file, see makefile.prep "
-    exit 1
-else
+########################
+function r_rm {
+########################
 
-	#if we created single libs file, we need to add footer at the end:
-	FOOTERNAME='${AUBITDIR}/incl/footer.mki'
+	#---------------------------------------------------------
+	TOREPLACE="rm "
+	INCLCMT='#'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+}
 
-	if [ -f $FILENAME ]
-    then
-		echo >> $FILENAME
-	    #echo "#-------------------------------------" >> $FILENAME
-		#echo >> $FILENAME
-		echo include $FOOTERNAME >> $FILENAME
-		echo >> $FILENAME
+
+########################
+function r_fgllink {
+########################
+
+	#replacing all "fgllink" lines with our command:
+	#INCLCMT='	genmake $(basename $(@F)) $(addsuffix .4gl,$(basename $(^F))) #'
+	#we don't want to rename ALL dependencies to .4gl they may be .per files!
+	#INCLCMT='	genmake $(basename $(@F)) $(^F) #'
+	#we alos don't want to strip extension from object name, it may be library
+	#target, not executable:
+	#---------------------------------------------------------
+	TOREPLACE=fgllink
+	INCLCMT='	genmake $(@F) $(^F) #'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+
+}
+
+########################
+function r_cat {
+########################
+
+	#commenting out all "cat" lines, so they don't get executed:
+	#---------------------------------------------------------
+	TOREPLACE="cat "
+	INCLCMT="#$TOREPLACE"
+	replace
+	#---------------------------------------------------------
+
+}
+
+#######################
+function r_fglcomp {
+#######################
+
+	#replace all fglcomp lines with fakes, so we don't go trough actual compile:
+	#INCLCMT='touch $(addsuffix .42m,$(basename $($<)))'
+	#INCLCMT='touch $(basename $<).42m'
+	#---------------------------------------------------------
+	TOREPLACE="fglcomp"
+	INCLCMT='touch $(notdir $(basename $<)).42m #'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+
+}
+
+#######################
+function r_fglform {
+#######################
+
+	#replace all fglform lines with fakes, so we don't go trough actual compile:
+	#INCLCMT='touch $(notdir $(basename $<)).42f'
+	#---------------------------------------------------------
+	TOREPLACE="fglform"
+	INCLCMT='touch $(basename $<).42f #'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+}
+
+#####################
+function r_form4gl {
+#####################
+
+	#---------------------------------------------------------
+	TOREPLACE="form4gl"
+	INCLCMT='touch $(basename $<).frm #'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+
+}
+
+#####################
+function r_fglpc {
+#####################
+
+	#we need all fglpc replaced with commands, since in winds most files
+	#are not programs, but library functions.
+	#---------------------------------------------------------
+	TOREPLACE="fglpc"
+	INCLCMT='	genmake $(@F) $(^F) #'$TOREPLACE
+	replace
+	#---------------------------------------------------------
+}
+
+
+########################
+#MAIN
+########################
+
+#############################
+#Configuration:
+	FILENAME=allsinglelibs.mk
+	rm -f $FILENAME
+	TMPCOMPOSITE=/tmp/makefile.1
+	RESULTMAKEFILE=makefile.prep
+	GENMAKE=genmake
+    SUBDIR=$1
+    DOALL=1
+
+	cp makefile $RESULTMAKEFILE
+
+    #add default rules, so make don't complain about missing rules
+    #or missing dependencies:
+
+    echo " " >> $RESULTMAKEFILE
+	echo ".SUFFIXES:   .ao .4gl .c .4ae .afr .per .iem .msg .hlp .4go .4gi .42m .42r" >> $RESULTMAKEFILE
+	echo " " >> $RESULTMAKEFILE
+	
+	#echo ".4gl:" >> $RESULTMAKEFILE
+    #echo "	touch $<" >> $RESULTMAKEFILE
+	#echo ".4go:" >> $RESULTMAKEFILE
+    #echo "	touch $<" >> $RESULTMAKEFILE
+	#echo ".4gi:" >> $RESULTMAKEFILE
+    #echo "	touch $<" >> $RESULTMAKEFILE
+	#echo ".4gl.4go:" >> $RESULTMAKEFILE
+    #echo "	touch $<" >> $RESULTMAKEFILE
+	#echo '$P/*.4go :' >> $RESULTMAKEFILE
+    #echo '	touch $P/$<' >> $RESULTMAKEFILE
+	#echo '$P/.4go :' >> $RESULTMAKEFILE
+    #echo '	touch $P/$<' >> $RESULTMAKEFILE
+
+    echo '%::' >> $RESULTMAKEFILE
+    echo '	touch $@' >> $RESULTMAKEFILE
+    echo '.DEFAULT:' >> $RESULTMAKEFILE
+    echo '	touch $@' >> $RESULTMAKEFILE
+	echo " " >> $RESULTMAKEFILE
+
+
+    r_ln
+    r_rm
+
+
+	if [ "$SUBDIR" = "ap" -o "$DOALL" = "1" ]
+	then
+		r_fgllink
+		r_cat
     fi
 
-	echo "'prepmake' completed. You can now run generated make files using "
-	echo "'amake' script. see 'amake -help' for instructions"
-	exit 0
-fi
+	if [ "$SUBDIR" = "gl" -o "$DOALL" = "1" ]
+	then
+		r_fglcomp
+		r_fglform
+		r_form4gl
+	fi
 
-#-------------------------- EOF -------------------------------
+	if [ "$SUBDIR" = "winds" -o "$DOALL" = "1" ]
+	then
+	    r_fglpc
+
+		#but we also need to process fgllink, since it creates composite library
+		#objects (.42x)
+	fi
+
+	if [ "$SUBDIR" = "main" -o "$DOALL" = "1" ]
+	then
+        touch $MAXDIR/prog/lic_calc.4go
+        touch $MAXDIR/prog/lic_check.4go
+        touch $MAXDIR/prog/lic_start.4go
+        touch $MAXDIR/prog/menuwind.4go
+	fi
+
+
+#############################################
+#Run prepared makefile, to create .mk files:
+
+	echo " "
+   	echo "------------------------- Running make ... ------------------------------"
+	echo " "
+
+	touch *.4gl
+	make -f $RESULTMAKEFILE
+	RET=$?
+
+   	echo "----------------------- Finished running make ---------------------------"
+
+	echo " "
+	if test $RET != "0"
+	then
+	    echo "Error preparing make file, see $RESULTMAKEFILE "
+	    exit 1
+	else
+
+		#if we created single libs file, we need to add footer at the end:
+		FOOTERNAME='${AUBITDIR}/incl/footer.mki'
+
+		if [ -f $FILENAME ]
+	    then
+			echo >> $FILENAME
+		    #echo "#-------------------------------------" >> $FILENAME
+			#echo >> $FILENAME
+			echo include $FOOTERNAME >> $FILENAME
+			echo >> $FILENAME
+	    fi
+
+		echo "'prepmake' completed. You can now run generated make files using "
+		echo "'amake' script. see 'amake -help' for instructions"
+		exit 0
+	fi
+
+#------------------------------ EOF -------------------------------------
