Windows port, dll enabled, phase 3 (istation)

diff --git a/aubit4glsrc/trunk/bin/4glpc b/aubit4glsrc/trunk/bin/4glpc
--- a/aubit4glsrc/trunk/bin/4glpc
+++ b/aubit4glsrc/trunk/bin/4glpc
@@ -30,7 +30,7 @@
 # +----------------------------------------------------------------------+
 
 #
-# $Id: 4glpc,v 1.51 2002-02-19 09:57:16 afalout Exp $
+# $Id: 4glpc,v 1.52 2002-02-22 13:22:23 afalout Exp $
 #
 
 ########################################################################
@@ -1241,7 +1241,10 @@ then
 						#GTKLIBS=`$PKG_CONFIG --cflags $GLIB_NAME`
                         GTKLIBS=`$PKG_CONFIG --cflags $GTK_NAME`
 	               else
-    					echo "ERROR: no PKG_CONFIG, no GTK_CONFIG. Stop."
+    					#echo "ERROR: no PKG_CONFIG, no GTK_CONFIG. Stop."
+                        #exit 78
+                        #use flags from aubitrc, inserted by aubitconf
+                        GTKLIBS="$MANUAL_GTK"
 				   fi
 		        fi
             fi
@@ -1277,6 +1280,7 @@ else  #UNIX
                     GTKLIBS=`$PKG_CONFIG --cflags $GTK_NAME`
                else
                     echo "ERROR: no PKG_CONFIG, no GTK_CONFIG. Stop."
+                    exit 78
 			   fi
 	        fi
 
