Separating Sun RPC, all compiles shared now

diff --git a/aubit4glsrc/trunk/bin/4glpc b/aubit4glsrc/trunk/bin/4glpc
--- a/aubit4glsrc/trunk/bin/4glpc
+++ b/aubit4glsrc/trunk/bin/4glpc
@@ -29,7 +29,7 @@
 # +----------------------------------------------------------------------+
 
 #
-# $Id: 4glpc,v 1.63 2002-03-25 10:15:18 afalout Exp $
+# $Id: 4glpc,v 1.64 2002-03-27 11:57:02 afalout Exp $
 #
 
 ########################################################################
@@ -46,16 +46,7 @@
     FGLCEXEC=4glc
 	OVERWRITE_CONFIG=0
 #	USE_CONFIGURE=1
-
-#FIXME: we should use shared linking on UNIX too:
-
-if [ ! "$COMSPEC" = "" ]
-then
 	USE_SHARED="Yes"
-fi
-
-#this still won't work on UNIX:
-#USE_SHARED="Yes"
 
 
 #############
@@ -422,39 +413,39 @@ else
 fi
 
 
-if [ "$ODBC_LIB_NAME" != "noodbc" ]
-then
-	if [ "$ODBC_LIB_NAME" = "" ]
-	then
-		if [ "$COMSPEC" = "" ]
-	    then
-			ODBC_LIB_NAME="iodbc"
-	    else
-	        ODBC_LIB_NAME="odbc32"
-	    fi
-	fi
-
-	if [ "$ODBC_LIB_DIR" = "" ]
-	then
-		if [ -d $AUBITDIR/extlibs ]
-		then
-			ODBC_LIB_DIR=$AUBITDIR/extlibs
-	    fi
-	fi
-
-	if [ "$ODBC_LIB_DIR" != "" ]
-    then
-		if [ "$ODBC_SHARED" = "" ]
-		then
-		        ODBC_SHARED="-L$ODBC_LIB_DIR"
-		fi
-
-		if [ "$ODBC_STATIC" = "" ]
-		then
-		        ODBC_STATIC="-L$ODBC_LIB_DIR"
-		fi
-    fi
-fi
+#if [ "$ODBC_LIB_NAME" != "noodbc" ]
+#then
+#	if [ "$ODBC_LIB_NAME" = "" ]
+#	then
+#		if [ "$COMSPEC" = "" ]
+#	    then
+#			ODBC_LIB_NAME="iodbc"
+#	    else
+#	        ODBC_LIB_NAME="odbc32"
+#	    fi
+#	fi
+#
+#	if [ "$ODBC_LIB_DIR" = "" ]
+#	then
+#		if [ -d $AUBITDIR/extlibs ]
+#		then
+#			ODBC_LIB_DIR=$AUBITDIR/extlibs
+#	    fi
+#	fi
+#
+#	if [ "$ODBC_LIB_DIR" != "" ]
+#    then
+#		if [ "$ODBC_SHARED" = "" ]
+#		then
+#		        ODBC_SHARED="-L$ODBC_LIB_DIR"
+#		fi
+#
+#		if [ "$ODBC_STATIC" = "" ]
+#		then
+#		        ODBC_STATIC="-L$ODBC_LIB_DIR"
+#		fi
+#    fi
+#fi
 
 #restore things from before reading .a4glrc that where in environment:
 #see if we are called form Aubit compiler makefiles:
@@ -469,44 +460,44 @@ fi
 #4glpc have make-compile flag, so we cannot rely on this:
 #if [ "$MAKE4GLPC" = "Yes" ]
 #MAKINGAUBIT will be exported in root makefile
-if test "$MAKINGAUBIT" = "1"
-then
-	if [ "$A4GLVERBOSE" = "yes" ]
-	then
-        echo "NOTE: invoked from Aubit compiler main makefile"
-    fi
-
-	if [ "$ODBC_LIB_NAME" != "noodbc" ]
-    then
-		if [ "$ENV_ODBC_LIB_DIR" != "" ]
-		then
-			ODBC_LIB_DIR="$ENV_ODBC_LIB_DIR"
-			ODBC_SHARED="-L$ENV_ODBC_LIB_DIR"
-			ODBC_STATIC="-L$ENV_ODBC_LIB_DIR"
-
-			echo "NOTE: using ODBC_LIB_DIR from environment: $ODBC_LIB_DIR"
-		fi
-
-		if [ "$ENV_ODBC_LIB_NAME" != "" ]
-		then
-			ODBC_LIB_NAME=$ENV_ODBC_LIB_NAME
-		    echo "NOTE: using ODBC_LIB_NAME from environment: $ODBC_LIB_NAME"
-		fi
-    fi
-fi
+#if test "$MAKINGAUBIT" = "1"
+#then
+#	if [ "$A4GLVERBOSE" = "yes" ]
+#	then
+#        echo "NOTE: invoked from Aubit compiler main makefile"
+#    fi
+#
+#	if [ "$ODBC_LIB_NAME" != "noodbc" ]
+#    then
+#		if [ "$ENV_ODBC_LIB_DIR" != "" ]
+#		then
+#			ODBC_LIB_DIR="$ENV_ODBC_LIB_DIR"
+#			ODBC_SHARED="-L$ENV_ODBC_LIB_DIR"
+#			ODBC_STATIC="-L$ENV_ODBC_LIB_DIR"
+#
+#			echo "NOTE: using ODBC_LIB_DIR from environment: $ODBC_LIB_DIR"
+#		fi
+#
+#		if [ "$ENV_ODBC_LIB_NAME" != "" ]
+#		then
+#			ODBC_LIB_NAME=$ENV_ODBC_LIB_NAME
+#		    echo "NOTE: using ODBC_LIB_NAME from environment: $ODBC_LIB_NAME"
+#		fi
+#    fi
+#fi
 
 LAST=""
 INCLDIR="-I$AUBITDIR/incl"
 
-#GCC and CC are set via aubitrc config file:
+#CC is set via aubitrc config file:
 #if [ "$COMSPEC" = "" ]
 #then
-#	GCC=${GCC:-"cc"}
+#	CC=${CC:-"cc"}
 #else
-#	GCC=${GCC:-"gcc"}
+#	CC=${CC:-"gcc"}
 #fi
 
-GCC="$GCC -O2 -g"
+CC="$CC -O2 -g"
 
 #This may help while compiling, but compiled programs will not run
 #if it's not in his environmnet. So set your environment!
@@ -522,10 +513,10 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ADD_LD_LIBRARY_PATH
 
 
 
-if [ "$ODBC_LIB_NAME" != "noodbc" ]
-then
-	export LD_LIBRARY_PATH=$ODBC_LIB_DIR:$LD_LIBRARY_PATH
-fi
+#if [ "$ODBC_LIB_NAME" != "noodbc" ]
+#then
+#	export LD_LIBRARY_PATH=$ODBC_LIB_DIR:$LD_LIBRARY_PATH
+#fi
 
 counter=0
 
@@ -631,131 +622,6 @@ do
 			exit 0
         fi
 
-   ;;
-
-   -overwrite_config)
-		OVERWRITE_CONFIG=1
-   ;;
-
-   -config)
-
-		if [ "$2" = "-overwrite_config" ]
-        then
-			OVERWRITE_CONFIG=1
-        fi
-
-        if [ ! -d $AUBITETC ]
-        then
-			mkdir $AUBITETC
-        fi
-
-
-		if [ "$AUBITDIR" = "" ]
-        then
-            echo "Error: AUBITDIR is not set"
-            exit 14
-        else
-
-			#we will use config files created with "configure" in the future
-            #if [ "$USE_CONFIGURE" = "1" ]
-            #then
-				cd $AUBITDIR
-	            ./configure
-				AUBITENVSRC=aubitenv
-				AUBITBUILDSRC=aubitbuild.mk
-				A4GLRCSRC=a4glrc
-                AUBITRCSRC=aubitrc
-
-                #configure still does not create aubitrc, so:
-                cp $AUBITDIR/etc/$AUBITRCSRC.in $AUBITDIR/etc/$AUBITRCSRC
-
-            #else
-			#	AUBITENVSRC=aubitenv.example
-			#	AUBITBUILDSRC=aubitbuild.mk.example
-			#	A4GLRCSRC=a4glrc.example
-            #fi
-
-
-			if [ -f $AUBITETC/aubitrc ] && [ "$OVERWRITE_CONFIG" = "0" ]
-            then
-                echo "Error: $AUBITETC/aubitrc exists - will not overwrite."
-                exit 14
-            else
-                #Fix AUBITDIR
-                #FIXME: this should be in autoconf!
-				TOREPLACE="^AUBITDIR"
-                INFILE=$AUBITDIR/etc/$AUBITRCSRC
-				OLDVALUE=$(grep "$TOREPLACE" $INFILE | awk '{print $1}' | sed -e "s/\//\\\\\//g")
-				NEWVALUE=$(echo "AUBITDIR=$AUBITDIR" | sed -e "s/\//\\\\\//g")
-				STARTWITH="^$OLDVALUE"
-				REPLACEWITH="$NEWVALUE"
-				sed -e "/$STARTWITH/s/$STARTWITH/$REPLACEWITH/" $INFILE > $AUBITETC/aubitrc
-		        chmod a+r $AUBITETC/aubitrc
-
-                #we need to delete this file because AUBITDIR was not
-				#changed in it, and it would override settings from main
-                #file, which can confuse user if he is not aware of it:
-                rm $INFILE
-            fi
-
-
-			#We should not longer ned to use aubitenv
-			#if [ -f $AUBITETC/aubitenv ] && [ "$OVERWRITE_CONFIG" = "0" ]
-            #then
-            #    echo "Error: $AUBITETC/aubitenv exists - will not overwrite."
-            #    exit 14
-            #else
-            #    #Fix AUBITDIR
-			#	TOREPLACE="^export AUBITDIR"
-            #    INFILE=$AUBITDIR/etc/$AUBITENVSRC
-			#	OLDVALUE=$(grep "$TOREPLACE" $INFILE | awk '{print $2}' | sed -e "s/\//\\\\\//g")
-			#	NEWVALUE=$(echo $AUBITDIR | sed -e "s/\//\\\\\//g")
-            #    STARTWITH="^export $OLDVALUE"
-			#	REPLACEWITH="export AUBITDIR=$NEWVALUE"
-			#	sed -e "/$STARTWITH/s/$STARTWITH/$REPLACEWITH/" $INFILE > $AUBITETC/aubitenv
-		    #    chmod +x $AUBITETC/aubitenv
-            #fi
-
-            #We should no longer need to use a4glrc:
-			#if [ -f $AUBITETC/a4glrc ] && [ "$OVERWRITE_CONFIG" = "0" ]
-            #then
-            #    echo "Error: $AUBITETC/a4glrc exists - will not overwrite."
-            #    exit 14
-            #else
-			#	cp $AUBITDIR/etc/$A4GLRCSRC $AUBITETC/a4glrc
-            #fi
-
-
-			#if [ -f $AUBITETC/aubitbuild.mk ] && [ "$OVERWRITE_CONFIG" = "0" ]
-            #then
-            #    echo "Error: $AUBITETC/aubitbuild.mk exists - will not overwrite."
-            #    exit 14
-            #else
-		    #    cp $AUBITDIR/etc/$AUBITBUILDSRC $AUBITETC/aubitbuild.mk
-            #fi
-
-            #Dynamic linking obsoleted use of aubitbuild-multi.mk
-			#if [ -f $AUBITETC/aubitbuild-multi.mk ] && [ "$OVERWRITE_CONFIG" = "0" ]
-            #then
-            #    echo "Error: $AUBITETC/aubitbuild-multi.mk exists - will not overwrite."
-            #    exit 14
-            #else
-			#	cp $AUBITDIR/etc/aubitbuild-multi.mk.example $AUBITETC/aubitbuild-multi.mk
-            #fi
-
-			echo ""
-			echo "Example configuration file 'aubitrc' placed in $AUBITETC"
-			#echo "'aubitrc' and 'aubitbuild.mk'" # 'aubitenv' 'a4glrc' and 'aubitbuild-multi.mk'"
-	        echo "Please edit it to reflect your configuration."
-			#echo "Then, execute: '. $AUBITETC/aubitenv' to set your environment."
-			echo ""
-
-			#we cannot execute aubitenv from here, because it will not be
-            #propageted to current user's shell, unless this script was invoked
-            #as ". 4glpc" and it probably was not
-
-			exit 0
-        fi
    ;;
 
    *.a) COMPCC="$COMPCC $a"
@@ -993,9 +859,9 @@ do
                 #for linking to succedde:
 				if [ "$COMSPEC" = "" ]
 				then
-					EXEC="$DOIT $GCC $fname.c -c -o $fname.ao $INCLDIR 2> $fname.err"
+					EXEC="$DOIT $CC $fname.c -c -o $fname.ao $INCLDIR 2> $fname.err"
 				else
-					EXEC="$DOIT $GCC $fname.c -o $fname.ao -c $INCLDIR 2> $fname.err"
+					EXEC="$DOIT $CC $fname.c -o $fname.ao -c $INCLDIR 2> $fname.err"
 				fi
                 # cc -O  ./P12.c -c -o  P12.ao -I/usr/aubit/aubit4glsrc/incl
 
@@ -1080,30 +946,6 @@ do
    ;;
 
 
-   -gtk) 	export GTKGUI="Yes"
-			export ui="gui"
-   ;;
-
-   -nogtk) 	export GTKGUI="no"
-			export ui=""
-
-			#FIXME: remove this:
-			#temp fix for bug
-			#>   if (getenv ("GTKGUI"))
-			#>     fprintf (hfile, "#include <acl4glgui.h>\n");
-			#unset GTKGUI
-
-   ;;
-
-
-#   -pdf) 	export USE_PDF="yes"
-#   ;;
-#
-#   -nopdf) 	export USE_PDF="no"
-#            #echo Set USE_PDF to $USE_PDF
-#   ;;
-
-
    -verbose) 	export A4GLVERBOSE="yes"
 				SHOWERRCODE=1
    ;;
@@ -1133,25 +975,6 @@ do
            export DEBUG=ALL
 		   #DDEBUG="_g"
            COMPCC="$COMPCC -g"
-   ;;
-
-   -udbc) ODBC_LIB_NAME="udbc"
-   ;;
-
-   -odbc) if [ "$COMSPEC" = "" ]
-		then
-		   ODBC_LIB_NAME="iodbc"
-        else
-			ODBC_LIB_NAME="odbc32"
-        fi
-   ;;
-
-   -noodbc)		ODBC_LIB_NAME=noodbc
-                ODBCFLAG=-noodbc
-				unset ODBC_LIB_DIR
-		        unset ODBC_SHARED
-	    	    unset ODBC_STATIC
-                FGLCEXEC=4glc-noodbc
    ;;
 
    -as-dll)		#creates shared library- .so on UNIX, .dll on Windows
@@ -1212,89 +1035,77 @@ do
 done
 ####
 
-if  [ ! "$COMSPEC" = "" ]
-then
-	#WARNING! on CyGwin ORDER OF LIBS IS IMPORTANT
-	if [  "$GTKGUI" = "Yes" ]
-    then
-
-		#if [ "$GLIBVER" = "old" -o "$GLIBVER" = "" ]
-		if [ "$GLIBVER" = "old" ]
-        then
-			GTKLIBS="-lgdk -lgtk -lglib"
-			#GTKLIBS="-lgdk-1.3 -lgtk-1.3 -lglib-1.3"
-	    else
-			if [ "$GLIBVER" != "" ]
-            then
-				#GLIB_LIBS=`pkg-config --libs $GLIBVER`
-				#GLIB_CFLAGS=`pkg-config --cflags $GLIBVER`
-				#GDKLIB_LIBS=`pkg-config --libs $GDKVER`
-				#GDKLIB_CFLAGS=`pkg-config --cflags $GDKVER`
-				GTKLIB_LIBS=`pkg-config --libs $GTKVER`
-				GTKLIB_CFLAGS=`pkg-config --cflags $GTKVER`
-				#GTKLIBS="$GLIB_LIBS $GLIB_CFLAGS $GDKLIB_LIBS $GDKLIB_CFLAGS $GTKLIB_LIBS $GTKLIB_CFLAGS"
-	            GTKLIBS="$GTKLIB_LIBS $GTKLIB_CFLAGS"
-			else
-				if [ "$GTK_CONFIG" != "no" ]
-				then
-					GTKLIBS=`$GTK_CONFIG --cflags`
-                    echo GTKLIBS = $GTKLIBS
-		        else
-					if [ "$PKG_CONFIG" != "no" ]
-                   then
-						#GTK_NAME="@GTK_NAME@"
-						#GDK_NAME="@GDK_NAME@"
-						#GLIB_NAME="@GLIB_NAME@"
-						#GTKLIBS=`$PKG_CONFIG --cflags $GLIB_NAME`
-                        GTKLIBS=`$PKG_CONFIG --cflags $GTK_NAME`
-	               else
-    					#echo "ERROR: no PKG_CONFIG, no GTK_CONFIG. Stop."
-                        #exit 78
-                        #use flags from aubitrc, inserted by aubitconf
-                        GTKLIBS="$MANUAL_GTK"
-				   fi
-		        fi
-            fi
-	    fi
-
-		#if  [ "$MAKE4GLPC" != "Yes" ]
-		#then
-        #    GTKLIBS="-lgtk4gl -lgtk4gl_x $GTKLIBS"
-        #fi
-    fi
-else  #UNIX
-	if [  "$GTKGUI" = "Yes" ]
-    then
-		GTKLIBS="-lgdk -lgtk -lglib"
-		#if  [ "$MAKE4GLPC" != "Yes" ]
-		#then
-		#	GTKLIBS="$GTKLIBS -lgtk4gl -lgtk4gl_x"
-    	#fi
-
-		if [ "$GLIBVER" != "old" ]
-        then
-			if [ "$GTK_CONFIG" != "no" ]
-            then
-				GTKCFLAGS=`$GTK_CONFIG --cflags`
-				#echo GTKCFLAGS = $GTKCFLAGS
-	        else
-				if [ "$PKG_CONFIG" != "no" ]
-               then
-					#GTK_NAME="@GTK_NAME@"
-					#GDK_NAME="@GDK_NAME@"
-					#GLIB_NAME="@GLIB_NAME@"
-					#GTKLIBS=`$PKG_CONFIG --cflags $GLIB_NAME`
-                    GTKLIBS=`$PKG_CONFIG --cflags $GTK_NAME`
-               else
-                    echo "ERROR: no PKG_CONFIG, no GTK_CONFIG. Stop."
-                    exit 78
-			   fi
-	        fi
-
-			GTKLIBS="$GTKLIBS $GTKCFLAGS"
-		fi
-    fi
-fi
+#if  [ ! "$COMSPEC" = "" ]
+#then
+#	#WARNING! on CyGwin ORDER OF LIBS IS IMPORTANT
+#	if [  "$GTKGUI" = "Yes" ]
+#    then
+#
+#		#if [ "$GLIBVER" = "old" -o "$GLIBVER" = "" ]
+#		if [ "$GLIBVER" = "old" ]
+#        then
+#			GTKLIBS="-lgdk -lgtk -lglib"
+#			#GTKLIBS="-lgdk-1.3 -lgtk-1.3 -lglib-1.3"
+#	    else
+#			if [ "$GLIBVER" != "" ]
+#            then
+#				GTKLIB_LIBS=`pkg-config --libs $GTKVER`
+#				GTKLIB_CFLAGS=`pkg-config --cflags $GTKVER`
+#	            GTKLIBS="$GTKLIB_LIBS $GTKLIB_CFLAGS"
+#			else
+#				if [ "$GTK_CONFIG" != "no" ]
+#				then
+#					GTKLIBS=`$GTK_CONFIG --cflags`
+#                    echo GTKLIBS = $GTKLIBS
+#		        else
+#					if [ "$PKG_CONFIG" != "no" ]
+#                   then
+#                        GTKLIBS=`$PKG_CONFIG --cflags $GTK_NAME`
+#	               else
+#                        GTKLIBS="$MANUAL_GTK"
+#				   fi
+#		        fi
+#            fi
+#	    fi
+#
+#		#if  [ "$MAKE4GLPC" != "Yes" ]
+#		#then
+#        #    GTKLIBS="-lgtk4gl -lgtk4gl_x $GTKLIBS"
+#        #fi
+#    fi
+#else  #UNIX
+#	if [  "$GTKGUI" = "Yes" ]
+#    then
+#		GTKLIBS="-lgdk -lgtk -lglib"
+#		#if  [ "$MAKE4GLPC" != "Yes" ]
+#		#then
+#		#	GTKLIBS="$GTKLIBS -lgtk4gl -lgtk4gl_x"
+#    	#fi
+#
+#		if [ "$GLIBVER" != "old" ]
+#        then
+#			if [ "$GTK_CONFIG" != "no" ]
+#            then
+#				GTKCFLAGS=`$GTK_CONFIG --cflags`
+#				#echo GTKCFLAGS = $GTKCFLAGS
+#	        else
+#				if [ "$PKG_CONFIG" != "no" ]
+#               then
+#					#GTK_NAME="@GTK_NAME@"
+#					#GDK_NAME="@GDK_NAME@"
+#					#GLIB_NAME="@GLIB_NAME@"
+#					#GTKLIBS=`$PKG_CONFIG --cflags $GLIB_NAME`
+#                    GTKLIBS=`$PKG_CONFIG --cflags $GTK_NAME`
+#               else
+#                    echo "ERROR: no PKG_CONFIG, no GTK_CONFIG. Stop."
+#                    exit 78
+#			   fi
+#	        fi
+#
+#			GTKLIBS="$GTKLIBS $GTKCFLAGS"
+#		fi
+#    fi
+#fi
 
 
 #if [ "$A4GLDEBUG" = "yes" ]
@@ -1386,12 +1197,12 @@ fi
 
 if [ "$ISMAKE" != "1" ]
 then
-#	EXEC="$DOIT $GCC $COMPCC -c $INCLDIR $LAST"
+#	EXEC="$DOIT $CC $COMPCC -c $INCLDIR $LAST"
 	if [ "$COMSPEC" = "" ]
 	then
-		EXEC="$DOIT $GCC $COMPCC $INCLDIR $LAST"
+		EXEC="$DOIT $CC $COMPCC $INCLDIR $LAST"
     else
-        EXEC="$DOIT $GCC $COMPCC -c $INCLDIR $LAST"
+        EXEC="$DOIT $CC $COMPCC -c $INCLDIR $LAST"
     fi
 
    if [ "$A4GLVERBOSE" = "yes" ]
@@ -1424,9 +1235,9 @@ else
 
    if [ "$A4GLVERBOSE" = "yes" ]
    then
-	   echo "executing (2) : $DOIT $GCC $COMPCC $INCLDIR $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $GTKLIBS $LAST"
+	   echo "executing (2) : $DOIT $CC $COMPCC $INCLDIR $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $GTKLIBS $LAST"
 #	   echo $DOIT
-#	   echo $GCC
+#	   echo $CC
 #	   echo $COMPCC
 #	   echo $INCLDIR
 #	   echo $FGLLIBSDIR
@@ -1442,10 +1253,10 @@ else
 
 #    if [ "$COMSPEC" = "" ]
 #    then
-#		eval  $DOIT $GCC $COMPCC $INCLDIR $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $GTKLIBS $LAST
+#		eval  $DOIT $CC $COMPCC $INCLDIR $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $GTKLIBS $LAST
 #       	err_code=$?
 #    else
-		eval "$DOIT $GCC $COMPCC $INCLDIR $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $GTKLIBS $LAST"
+		eval "$DOIT $CC $COMPCC $INCLDIR $FGLLIBSDIR $FGLLIBS $LIBSDIR $LIBS $GTKLIBS $LAST"
 		err_code=$?
 #    fi
 
