Updates and fixes

diff --git a/aubit4glsrc/trunk/bin/amake b/aubit4glsrc/trunk/bin/amake
--- a/aubit4glsrc/trunk/bin/amake
+++ b/aubit4glsrc/trunk/bin/amake
@@ -12,7 +12,7 @@
 #that make a program, one program per .mk file. See examples in $AUBITDIR/incl
 #and $AUBITDIT/tools/test
 
-# $Id: amake,v 1.13 2003-01-07 03:59:34 afalout Exp $
+# $Id: amake,v 1.14 2003-01-21 08:25:48 afalout Exp $
 
 #####################################################################
 
@@ -20,6 +20,17 @@
 #Specifies a directory dir to search for included makefiles. See section
 #Including Other Makefiles. If several `-I' options are used to specify
 #several directories, the directories are searched in the order specified.
+
+if [ "$AUBITDIR" = "" ]; then
+    AUBITDIR=`aubit-config AUBITDIR`
+	if [ "$AUBITDIR" = "" ]; then
+        echo "ERROR: AUBITDIR not set. Stop."
+        exit 43
+    else
+        export AUBITDIR
+	fi
+fi
+
 
 #defaults:
 LOG="0"
@@ -97,7 +108,36 @@ else
 	for a in $@
     ###########
 	do
-		a=`basename $a .mk`
+		FULLPARAM=$a
+		a=`basename $FULLPARAM $MK`
+        NOPATH=`basename $FULLPARAM`
+
+#        echo FULLPARAM=$FULLPARAM
+#		echo a=$a
+#        echo NOPATH=$NOPATH
+
+#FULLPARAM=./src/gl/GXX.mk
+#a=GXX
+#NOPATH=GXX.mk
+
+		if [ "$FULLPARAM" != "$a" ]; then
+            #param had a path, a .mk extension, or both
+            if [ "$NOPATH" != "$FULLPARAM" ]; then
+				#echo "param had a path"
+                HAS_PATH=1
+				PARAM_PATH=`echo $FULLPARAM | sed -e "s/$NOPATH//"`
+                #strip trailing slash:
+				#PARAM_PATH=`basename $PARAM_PATH`
+                #PARAM_PATH=`echo $PARAM_PATH | sed -e "s/&\///"`
+				if [ "$VERBOSE" = "1" ]; then
+					echo "PATH is $PARAM_PATH"
+                fi
+			fi
+            if [ "$NOPATH" != "$a" ]; then
+                #echo "param had a .mk extension"
+                HAS_MK_EXT=1
+            fi
+		fi
 
 		let cnt=cnt+1
 
@@ -125,13 +165,16 @@ else
                 ;;
 
 
-		*)  if [ -f $a$MK ]
+		*)  if [ -f "$PARAM_PATH$a$MK" ]
 			then
-			    
+                #this is a .mk file name:
+
                 if [ "$PROGS" = "" ]
                 then
-					PROGS="$a$MK"
+					#PROGS="$PARAM_PATH$a$MK"
+                    PROGS="$a$MK"
                 else
+					PROGS="$PARAM_PATH$a$MK $PROGS"
 					PROGS="$a$MK $PROGS"
                 fi
 			else
@@ -196,7 +239,7 @@ else
 #4glpc   -o AS1b.4ae AS1b.ao
 
 #OK:
-#amake AS1b  -verbose 
+#amake AS1b  -verbose
 #Command is: make -f AS1b.mk
 #4glpc   -o AS1b.4ae AS1b.ao
 
@@ -265,6 +308,10 @@ fi
     #####################
     do
         echo "aMaking $ONEPROG"
+
+		if [ "$PARAM_PATH" != "" ]; then
+            cd $PARAM_PATH
+        fi
 
 		COMPOSITE=/tmp/$USER-$ONEPROG
 
@@ -344,6 +391,9 @@ fi
             fi
 			if ! [ "$IGNOREERROR" = "1" ]
             then
+				if [ "$PARAM_PATH" != "" ]; then
+		            cd -
+        		fi
 				exit 1
             fi
 		fi
@@ -351,5 +401,11 @@ fi
     ####
 	done
     ####
+
+if [ "$PARAM_PATH" != "" ]; then
+    cd -
+fi
+
+
 #------------------------------- EOF ----------------------------------
 
