commit.build

diff --git a/aubit4glsrc/trunk/bin/amake b/aubit4glsrc/trunk/bin/amake
--- a/aubit4glsrc/trunk/bin/amake
+++ b/aubit4glsrc/trunk/bin/amake
@@ -21,7 +21,7 @@
 #defaults:
 LOG="0"
 LOGFILE=amake.log
-OVERRIDEINCLUDE="0"
+OVERRIDEINCLUDE=0
 #HEADER="./header.mki"
 #FOOTER="./footer.mki"
 HEADER="$AUBITDIR/incl/header.mki"
@@ -79,7 +79,15 @@ CLEANTARGET=0
 
 if [ $# -lt 1 ]
 then
-    PROGS=`ls *$MK`
+	ls *.mk > /dev/null 2>&1
+	RET=$?
+	if test $RET = "0"
+	then
+		PROGS=`ls *$MK`
+    else
+        echo "ERROR: No .mk files in $PWD"
+        exit 34
+    fi
 else
 	cnt=0
 	###########
@@ -116,14 +124,30 @@ else
 
 		*)  if [ -f $a$MK ]
 			then
-			    PROGS="$a$MK $PROGS"
+			    
+                if [ "$PROGS" = "" ]
+                then
+					PROGS="$a$MK"
+                else
+					PROGS="$a$MK $PROGS"
+                fi
 			else
 	           ##########
 			   case $a in
 	           ##########
 
 			   #################this are parameters to this script:##########
-			   -all) 		PROGS=`ls *$MK`
+			   -all)
+					ls *.mk > /dev/null 2>&1
+					RET=$?
+					if test $RET = "0"
+					then
+						PROGS=`ls *$MK`
+				    else
+				        echo "ERROR: No .mk files in $PWD"
+				        exit 34
+				    fi
+
 			   ;;
 
 			   -log) 		LOG="1"
@@ -133,7 +157,7 @@ else
                     		MAKE="$MAKE -k"
 			   ;;
 
-			   -defaultinclude) OVERRIDEINCLUDE="0"
+			   -defaultinclude) OVERRIDEINCLUDE=0
 			   ;;
 
 			   -verbose) 	VERBOSE="1"
@@ -141,14 +165,14 @@ else
 							#MKFLAGS="$MKFLAGS -verbose"
 			   ;;
 
-			   -header) 	OVERRIDEINCLUDE="1"
+			   -header) 	OVERRIDEINCLUDE=1
 	                		#HEADER=<next parameter>
 							#let next=cnt+1
 	                		NEXT=HEADER
 
 			   ;;
 
-			   -footer) 	OVERRIDEINCLUDE="1"
+			   -footer) 	OVERRIDEINCLUDE=1
 	                		#FOOTER=<next parameter>
                     		NEXT=FOOTER
                ;;
@@ -179,6 +203,19 @@ else
 			   ;;
 
 
+               d4gl-pcode) DEFAULT=d4gl-pcode
+               ;;
+               d4gl-ccode) DEFAULT=d4gl-ccode
+               ;;
+               i4gl-pcode) DEFAULT=i4gl-pcode
+               ;;
+               i4gl-pcode) DEFAULT=i4gl-ccode
+               ;;
+               aubit) DEFAULT=aubit
+               ;;
+               querix) DEFAULT=querix
+               ;;
+
 			   ################anything else is make parameter:##############
 			   *)   		PARAMS="$a $PARAMS"
 
@@ -199,9 +236,19 @@ else
     ####
 fi
 
+	if [ "$DEFAULT" = "" ]
+    then
+        #we need to explicitly sent this as variable to makefiele, because
+        #make don't store targets in MAKEFLAGS, so we would have no way
+        #to recognise which compielr we are using:
+		DEFAULT=aubit
+    fi
+
+
 	if [ "$PROGS" = "" ]
 	then
 	    echo "Please specify one or more .mk file names (without .mk extension)"
+        echo "In command line '$@', there was no .mk file that is in this directory"
 	    exit 1
 	fi
 
@@ -214,52 +261,62 @@ fi
 	for ONEPROG in $PROGS
     #####################
     do
+        echo "aMaking $ONEPROG"
 
 		if test "$CLEANOBJECTS" = "1"
 	    then
-            make -f $ONEPROG clean > /dev/null
+            make -f $ONEPROG clean DEFAULT=$DEFAULT
         fi
 
 		if test "$CLEANTARGET" = "1"
 	    then
-            #fixme: this should be doen like that:
-            #make -f $ONEPROG cleantarget
-            rm $ONEPROG.4ae
+            make -f $ONEPROG clean.target DEFAULT=$DEFAULT
         fi
 
-		#see if we have include command in this .mk :
-		grep include $ONEPROG > /dev/null
-		RET=$?
-		if test $RET != "0"
-		then
-			OVERRIDEINCLUDE="1"
+		if [ "$ONEPROG" = "allsinglelibs.mk" ]
+        then
+			if [ "$ONEPROG" != "$PROGS" ]
+            then
+				#echo x"$ONEPROG"x != x"$PROGS"x
+				echo "Ignoring $ONEPROG"
+				continue
+            fi
 		fi
 
-		if [ "$OVERRIDEINCLUDE" = "1" ]
+		if test "$OVERRIDEINCLUDE" = "1"
         then
+			#see if we have include command in this .mk :
+			#grep include $ONEPROG > /dev/null
+			#RET=$?
+			#if test $RET != "0"
+			#then
+			#	OVERRIDEINCLUDE=1
+			#fi
+
 			if [ "$VERBOSE" = "1" ]
             then
-				echo "Overriding include..."
+					echo "Overriding include..."
             fi
+			
 			INCLCMT="#include"
 			COMPOSITE=/tmp/$USER-$ONEPROG
 			sed -e "s%include%$INCLCMT%g" $ONEPROG > $COMPOSITE.tmp
 	        cat $HEADER $COMPOSITE.tmp $FOOTER > $COMPOSITE
-        else
+
+		else
 			COMPOSITE=$ONEPROG
 		fi
 
 		if [ "$VERBOSE" = "1" ]
         then
-            echo Command is: $MAKE $MKFLAGS -f $COMPOSITE $PARAMS
+            echo Command is: $MAKE $MKFLAGS -f $COMPOSITE $PARAMS DEFAULT=$DEFAULT
         fi
-
 
 		if [ "$LOG" = "1" ]
 		then
-			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS > $LOGFILE 2>&1
+			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS DEFAULT=$DEFAULT > $LOGFILE 2>&1
         else
-			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS
+			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS DEFAULT=$DEFAULT
         fi
 
 		RET=$?
diff --git a/aubit4glsrc/trunk/bin/genmake b/aubit4glsrc/trunk/bin/genmake
--- a/aubit4glsrc/trunk/bin/genmake
+++ b/aubit4glsrc/trunk/bin/genmake
@@ -40,17 +40,44 @@ fi
             then
 	            if [ "$DIRNAME" != "$PWD" ]
     	        then
-					#PROBLEMFILE=`echo $X | sed -e "/./s/\]//"`
-					#LASTDIR=`echo $DIRNAME | sed -e "/$MAXDIR/s/$MAXDIR//"`
-					A1=$(echo $MAXDIR | sed -e "s/\//\\\\\//g")
-					A2=$(echo $DIRNAME | sed -e "s/$A1//")
+					if [ "$MAXDIR" != "" ]
+                    then
+						A1=$(echo $MAXDIR | sed -e "s/\//\\\\\//g")
+                    else
+                        echo "FIXME: cannot do this without MAXDIR"
+                        exit 99
+                    fi
+					A3=$(echo $DIRNAME | sed -e "s/$A1//")
+					A2=$(echo $A3 | sed -e "/../s/..//")
 					#echo "DIRNAME = $DIRNAME"
                     #echo "LASTDIR = $LASTDIR"
-					if [ "$A2" != "/gprog" ] && [ "$A2" != "/gform" ]
+
+					#current dir:
+					B1=$(echo $PWD | sed -e "s/$A1//")
+
+                    #if [ "B1" = "/cm/source" ]
+                    #then
+						#../../gprog/contact.42r points outside current dir (/cm/source), to /../gprog
+						TMP=$A2
+						A2=$(echo $A2 | sed -e "/../s/\/\.\.//")
+					#fi
+
+
+                    #../winds/invwind.42x points outside current dir, to ../winds. STOP.
+					if [ "$A2" != "/gprog" ] && [ "$A2" != "prog" ] && [ "$A2" != "/gform" ]  && [ "$A2" != "$B1" ]
                     then
 						#if this happens, add it to vpath
-						echo "$FULLNAME points outside current dir, to $A2. STOP."
+						echo "$FULLNAME points outside current dir ($B1), to $A2. STOP."
+                        echo $TMP
     	                exit 67
+
+
+                        #FIXME:
+                        #Maximise makefiles sometimes expect object to allreadu be
+                        #in ../prog or ../gprog:
+						#we should actually check if this file is in current dir,
+                        #and if not, look for it, and add vpath to that place
+
                     fi
                 fi
             fi
@@ -58,30 +85,45 @@ fi
 			CMDLINE="$CMDLINE $a"
 			CMDLINEBASENAME="$CMDLINEBASENAME $STRIPPATH"
 
-   			#first and  second can't be .42x
+   			#second can't be .42x
             ##########
 			case $a in
             ##########
 
             *.42x)
-				if test "$CNT" = "1" -o "$CNT" = "2"
+				if test "$CNT" = "1"
                 then
-                    echo "Got $a in first or second position. STOP"
-                    exit 56
+                    #We are supposed to make library:
+	                FIRST=$a
+				fi
+
+				#second is treated a GLOBALS, and lib cannot be GLOBAL file(?)
+				if test "$CNT" = "2"
+                then
+                    echo "Got $a in second position."
+                    #exit 56
+                    GLOBNAME=1
                 fi
             ;;
 
             *)
-				if test "$CNT" = "1"
+				if test "$GLOBNAME" = "1"
 	            then
-					#FIRST=`basename $a`
-	                FIRST=$a
-	            fi
-	            if test "$CNT" = "2"
-	            then
-					#SECOND=`basename $a`
-	                SECOND=$a
-	            fi
+                    #This will happen if we cannot use second param for GLOBALS
+                    #because it's not 4gl file:
+					GLOBNAME=$a
+                else
+					if test "$CNT" = "1"
+		            then
+						#FIRST=`basename $a`
+		                FIRST=$a
+		            fi
+		            if test "$CNT" = "2"
+		            then
+						#SECOND=`basename $a`
+		                SECOND=$a
+		            fi
+                fi
 	        ;;
 
 			####
@@ -106,6 +148,7 @@ then
     OBJEXT=4go
     PROGEXT=4gi
 	LIBEXT=4go
+	FRMEXT=frm
 
 else
 	PROG=`basename $FIRST .42m`
@@ -117,11 +160,23 @@ else
         OBJEXT=42m
         PROGEXT=42r
 	    LIBEXT=42x
-
+		FRMEXT=42f
     else
-	    IS4GO="0"
-	    IS42M="0"
-		ISLIB="0"
+		PROG=`basename $FIRST .42x`
+		if [ "$PROG" != "$FIRST" ]
+		then
+		    IS4GO="0"
+		    IS42M="0"
+	    	ISLIB="1"
+	        OBJEXT=42m
+	        PROGEXT=42r
+		    LIBEXT=42x
+           	FRMEXT=42f
+	    else
+		    IS4GO="0"
+	    	IS42M="0"
+			ISLIB="0"
+        fi
     fi
 fi
 
@@ -135,6 +190,7 @@ then
         OBJEXT=4go
         PROGEXT=4gi
 		LIBEXT=4go
+       	FRMEXT=frm
 	else
 		PROG=`basename $FIRST .42r`
 		if [ "$PROG" != "$FIRST" ]
@@ -146,6 +202,7 @@ then
             OBJEXT=42m
             PROGEXT=42r
 	        LIBEXT=42x
+			FRMEXT=42f
         else
 			echo "Cannot recognise extension of $FIRST STOP."
     	    exit 4
@@ -180,6 +237,7 @@ then
 		echo "PROG		= dummy.lib"  >> $FILENAME
 		echo >> $FILENAME
 		echo "GLOBALS.4gl	= $fname.4gl" >> $FILENAME
+        GLOBFILE=$fname.4gl
 		echo >> $FILENAME
 		echo 'FILES.4gl	= \' >> $FILENAME
 		echo '		${GLOBALS.4gl} \' >> $FILENAME
@@ -203,87 +261,94 @@ else
     fi
 	echo >> $FILENAME
 
-	fname=`basename $SECOND .$OBJEXT`
+	if [ "$GLOBNAME" != "" ]
+    then
+		#if we received non-4gl dile as second param:
+		fname=`basename $GLOBNAME .$OBJEXT`
+    else
+		fname=`basename $SECOND .$OBJEXT`
+    fi
+
 	fname=`basename $fname .4gl`
 	echo "GLOBALS.4gl	= $fname.4gl" >> $FILENAME
+    GLOBFILE=$fname.4gl
 	echo >> $FILENAME
 
 	##################
 	for a in $CMDLINE
     ##################
 	do
-		if ! [ "$FIRST" = $a ] 		#it's program name
+		if [ "$FIRST" != "$a" ] 		#it's program name
         then
-	        if ! [ "$SECOND" = $a ]  #it's GLOBALS file
+	        if [ "$GLOBNAME" != "$a" ] #it's GLOBALS file
             then
-
-			##########
-			case $a in
-	        ##########
-
-			#*.42m) || *.4go) HOW THE HELL DO YOU DO _OR_here ?
-			#*.4go)
-            *.$OBJEXT)
-				fname=`basename $a .$OBJEXT`
-                #EXT=ao
-                EXT=4gl
-
-				#cinqwind is BOTH a 4gl and library (.42x, .aox) name
-                #which is VERY stupid thing to do, and should be fixed in Maximise;
-                #since I will have dependencies listeds with .4go in Maximise makefile,
-                #(there will be .42x in 4Js link line, but I'm not looking at that...
-				#Maybe I shoud use "fgllink..." line to get files, and not dependencies?)
-				if [ "$fname" = "cinqwind" -o "$fname" = "invwind" -o "$fname" = "lic_keys" -o "$fname" = "pinqwind" -o "$fname" = "wcustwind" -o "$fname" = "wordrwin" -o "$fname" = "wpinqwind" ]
+				if [ "$SECOND" != "$a" -o "$GLOBNAME" != "" ]
                 then
-					if [ "$OBJEXT" = "4go" ]
-                    then
-						#EXT=aox
-						#if [ "$LIBLIST" = "" ]
-					    #then
-						#	#echo '		${FILES.lib} \' >> $FILENAME
-                	    #fi
-						LIBLIST="$LIBLIST $fname.lib"
-                    else
-    	                FGLLIST="$FGLLIST $fname.$EXT"
-                    fi
-                else
-                    FGLLIST="$FGLLIST $fname.$EXT"
+
+				##########
+				case $a in
+		        ##########
+
+				#*.42m) || *.4go) HOW THE HELL DO YOU DO _OR_here ?
+				#*.4go)
+	            *.$OBJEXT)
+					fname=`basename $a .$OBJEXT`
+	                #EXT=ao
+	                EXT=4gl
+
+					#cinqwind is BOTH a 4gl and library (.42x, .aox) name
+	                #which is VERY stupid thing to do, and should be fixed in Maximise;
+	                #since I will have dependencies listeds with .4go in Maximise makefile,
+	                #(there will be .42x in 4Js link line, but I'm not looking at that...
+					#Maybe I shoud use "fgllink..." line to get files, and not dependencies?)
+					if [ "$fname" = "cinqwind" -o "$fname" = "invwind" -o "$fname" = "lic_keys" -o "$fname" = "pinqwind" -o "$fname" = "wcustwind" -o "$fname" = "wordrwin" -o "$fname" = "wpinqwind" ]
+	                then
+						if [ "$OBJEXT" = "4go" ]
+	                    then
+							#EXT=aox
+							#if [ "$LIBLIST" = "" ]
+						    #then
+							#	#echo '		${FILES.lib} \' >> $FILENAME
+	                	    #fi
+							LIBLIST="$LIBLIST $fname.lib"
+	                    else
+	    	                FGLLIST="$FGLLIST $fname.$EXT"
+	                    fi
+	                else
+	                    FGLLIST="$FGLLIST $fname.$EXT"
+	                fi
+
+				;;
+
+	            *.$LIBEXT)
+					fname=`basename $a .$LIBEXT`
+	                LIBLIST="$LIBLIST $fname.lib"
+	            ;;
+
+				#*.42f) || *.frm)
+		        #*.frm)
+                *.$FRMEXT)
+					fname=`basename $a .$FRMEXT`
+		            FORMFILES="$FORMFILES $fname.per"
+		        ;;
+
+		        *)
+					echo "ERROR: what the hell is $a"
+					echo "IS4GO = $IS4GO IS42M = $IS42M ISLIB = $ISLIB"
+			        echo "$OBJEXT $PROGEXT $LIBEXT"
+	                echo "---------------------------x"
+					echo $CMDLINEBASENAME
+	                echo "---------------------------x"
+	                echo FIRST = $FIRST SECOND = $SECOND
+					#echo $@
+					exit 1
+		        ;;
+
+				####
+				esac
+				####
                 fi
-
-			;;
-
-            *.$LIBEXT)
-				fname=`basename $a .$LIBEXT`
-                LIBLIST="$LIBLIST $fname.lib"
-            ;;
-
-			#*.42f) || *.frm)
-	        *.frm)
-				fname=`basename $a .frm`
-	            FORMFILES="$FORMFILES $fname.per"
-	        ;;
-
-	        *) echo "ERROR: what the hell is $a"
-
-				echo "IS4GO = $IS4GO"
-			    echo "IS42M = $IS42M"
-		    	echo "ISLIB = $ISLIB"
-		        echo "$OBJEXT"
-		        echo "$PROGEXT"
-			    echo "$LIBEXT"
-                echo "---------------------------x"
-				echo $CMDLINEBASENAME
-                echo "---------------------------x"
-                echo $FIRST $SECOND
-				#echo $@
-				exit 1
-
-	        ;;
-
-			####
-			esac
-			####
-            fi
+			fi
         fi
 	####
 	done
@@ -333,10 +398,33 @@ else
         ####
 
 		echo >> $FILENAME
-    #else
+    else
         #This can happen with porgrams that have only one 4gl file
 		#echo FGLLIST is empty
-        #exit 44
+
+	    grep -i "end main" $GLOBFILE > /dev/null
+
+		RET=$?
+		if test $RET != "0"
+		then
+            echo "no END MAIN in $GLOBFILE"
+
+            #is this one of 0 size 4gl files?
+			FGLFILESIZE=$(ls -al $GLOBFILE | awk '{print $5}')
+    		if [ "$VERBOSE" = "1" ]
+	    	then
+				echo FGLFILESIZE of $GLOBFILE is $FGLFILESIZE
+            fi
+            if [ "$FGLFILESIZE" = "0" ]
+            then
+        	    echo "This is zero size file, ignoring."
+            fi
+			
+			rm $FILENAME
+            exit 0
+	    else
+			echo 'FILES.4gl	= ${GLOBALS.4gl} ' >> $FILENAME
+        fi
 
 	fi
 
diff --git a/aubit4glsrc/trunk/bin/prepmake b/aubit4glsrc/trunk/bin/prepmake
--- a/aubit4glsrc/trunk/bin/prepmake
+++ b/aubit4glsrc/trunk/bin/prepmake
@@ -30,12 +30,6 @@
 #Compile modules in this order:
 #	winds csimods main ar eo fa gl in jm lc qe re ss ap pu wo
 #
-#Confirmed to work in $MAXDIR:
-#
-#	winds
-#   ar
-#	gl
-#	ap
 #
 ##########################################################################
 
@@ -43,7 +37,10 @@
 function replace {
 ########################
 
-    echo "Replacing    [$TOREPLACE]	with	[$INCLCMT]"
+	if test "$QUIET" = "0"
+    then
+	    echo "Replacing    [$TOREPLACE]	with	[$INCLCMT]"
+    fi
 	sed -e "s%$TOREPLACE%$INCLCMT%g" $RESULTMAKEFILE > $TMPCOMPOSITE
 	mv $TMPCOMPOSITE $RESULTMAKEFILE
 
@@ -67,7 +64,9 @@ function r_rm {
 ########################
 
 	#---------------------------------------------------------
-	TOREPLACE="rm "
+	#fonflicts with "fglfo-rm"
+	#TOREPLACE="rm "
+    TOREPLACE='	rm '
 	INCLCMT='#'$TOREPLACE
 	replace
 	#---------------------------------------------------------
@@ -128,6 +127,29 @@ function r_fglcomp {
 
 }
 
+
+#######################
+function r_fgl2p {
+#######################
+
+	#---------------------------------------------------------
+	#this is usefull only in CM, and I want form file names, so I'll
+    #get this from dependencies anyway:
+	#if test "$FROMDEPS" = "1"
+	if test "1" = "1"
+    then
+		TOREPLACE='	fgl2p'
+		INCLCMT='	genmake $(@F) $(^F) #'$TOREPLACE
+    else
+		TOREPLACE='	fgl2p -o'
+		INCLCMT='	genmake '
+    fi
+	replace
+	#---------------------------------------------------------
+
+}
+
+
 #######################
 function r_fglform {
 #######################
@@ -174,73 +196,37 @@ function r_fglpc {
 }
 
 
-########################
-#MAIN
-########################
+#################
+function doit {
+#################
 
-#############################
-#Configuration:
-	FILENAME=allsinglelibs.mk
-	rm -f $FILENAME
-	TMPCOMPOSITE=/tmp/makefile.1
-	RESULTMAKEFILE=makefile.prep
-	GENMAKE=genmake
-    DOALL=1
+	if test "$SKIP" = "1"
+    then
+        if [ -f $RESULTMAKEFILE ]
+        then
+            echo "SKIP is on, $RESULTMAKEFILE exists - skipping..."
+            return
+        fi
+    fi
 
-
-    #If you want to extract components from list of dependencies, instead
-	#directly form link line, change this to 1:
-    FROMDEPS=0
-
-	###########
-	for a in $@
-    ###########
-	do
-		##########
-		case $a in
-	    ##########
-
-                -help)
-                    echo " "
-                    echo " -verbose"
-                    echo " -clean"
-					echo " -all"
-                    echo " Maximise module/subdir name"
-                    echo " "
-                    exit 1
-                ;;
-
-
-			   -verbose) 	VERBOSE=1
-			   ;;
-
-			   -clean) 		CLEAN=1
-			   ;;
-
-
-			   -all) 		DOALL=1
-			   ;;
-
-
-			   *)         	SUBDIR=$a
-               ;;
-
-			   #*)           echo "ERROR: parameter $a not recognised"
-               #             exit 1
-        	   #;;
-		  ####
-		  esac
-          ####
-	####
-	done
-    ####
-
-    if [ ! -f makefile ]
+	if [ ! -f makefile ]
     then
 	    if [ ! -f Makefile ]
     	then
-			echo "ERROR: there is no file called 'M/makefile' in $PWD"
-	        exit 1
+			echo "WARNING: no file called 'M/makefile' in $PWD"
+	        EXITCODE=1
+
+            if test "$RECURSIVE" = "0"
+            then
+				exit $EXITCODE
+            else
+				if test "$STOPONERROR" = "1"
+    	        then
+					#exit $EXITCODE
+                    return
+                fi
+			fi
+            return
         else
 			cp Makefile $RESULTMAKEFILE
 		fi
@@ -250,7 +236,8 @@ function r_fglpc {
 
 	if test "$CLEAN" = "1"
 	then
-        rm -f *.mk
+        echo "Deleting all .mk files ..."
+		rm -f *.mk
     fi
 
     #add default rules, so make don't complain about missing rules
@@ -305,38 +292,65 @@ function r_fglpc {
 		#objects (.42x)
 	fi
 
+	#in CM:
+	r_fgl2p
+
+
 	if [ "$SUBDIR" = "main" -o "$DOALL" = "1" ]
 	then
-        touch $MAXDIR/prog/lic_calc.4go
-        touch $MAXDIR/prog/lic_check.4go
-        touch $MAXDIR/prog/lic_start.4go
-        touch $MAXDIR/prog/menuwind.4go
+		if [ "$MAXDIR" != "" ]
+        then
+			touch $MAXDIR/prog/lic_calc.4go
+	        touch $MAXDIR/prog/lic_check.4go
+	        touch $MAXDIR/prog/lic_start.4go
+	        touch $MAXDIR/prog/menuwind.4go
+        fi
 	fi
 
 
 #############################################
 #Run prepared makefile, to create .mk files:
 
-	echo " "
-   	echo "------------------------- Running make ... ------------------------------"
-	echo " "
+	if test "$VERBOSE" = "1"
+	then
+		echo " "
+	   	echo "-------------- Running make -f $RESULTMAKEFILE --------------------"
+		echo " "
+	else
+		if test "$QUIET" = "0"
+    	then
+			echo "Running make -f $RESULTMAKEFILE ..."
+        fi
+	fi
 
 	touch *.4gl
+	touch *.per
+	touch *.msg
 	make -f $RESULTMAKEFILE > prepmake.log 2>&1
 	RET=$?
-	
-	echo " "
+
 	if test "$RET" != "0"
 	then
 	    if test "$VERBOSE" = "1"
         then
-            tail prepmake.log
+			tail prepmake.log
 		   	echo "----------------------- Finished running make ---------------------------"
+            echo "PWD = $PWD"
 		fi
 		echo "Error preparing make file, see $RESULTMAKEFILE and prepmake.log"
-	    exit 1
+	    EXITCODE=1
+
+		if test "$STOPONERROR" = "1"
+        then
+	        exit $EXITCODE
+        else
+			return
+        fi
 	else
-	   	echo "----------------------- Finished running make ---------------------------"
+		if test "$QUIET" = "0"
+    	then
+			echo "----------------------- Finished running make ---------------------------"
+        fi
 		#if we created single libs file, we need to add footer at the end:
 		FOOTERNAME='${AUBITDIR}/incl/footer.mki'
 
@@ -349,9 +363,151 @@ function r_fglpc {
 			echo >> $FILENAME
 	    fi
 
+		ls *.mk > /dev/null 2>&1
+		RET=$?
+		if test $RET != "0"
+		then
+	        echo "ERROR(?): No .mk files created in in $PWD"
+	    fi
+
+		if test "$QUIET" = "0"
+    	then
+            echo "Done in $PWD"
+            EXITCODE=0
+			return
+        fi
+	fi
+
+}
+
+
+########################
+#MAIN
+########################
+
+#############################
+#Configuration:
+	FILENAME=allsinglelibs.mk
+	rm -f $FILENAME
+	TMPCOMPOSITE=/tmp/makefile.1
+	RESULTMAKEFILE=makefile.prep
+	GENMAKE=genmake
+    DOALL=1
+	QUIET=0
+	RECURSIVE=0
+    STOPONERROR=1
+
+    #If you want to extract components from list of dependencies, instead
+	#directly form link line, change this to 1:
+    #This is a tradeoff, at least with Maximise: if you take names from
+    #command line, you will loose form files names, that can be listed
+    #only as dependencies; but if you take names from dependencies, you
+    #will not get distiction between library extensions (.42x/.42o)
+	FROMDEPS=0
+
+	###########
+	for a in $@
+    ###########
+	do
+		##########
+		case $a in
+	    ##########
+
+                -help)
+                    echo " prepmake [options] [name]"
+                    echo " -verbose"
+                    echo ' -quiet'
+                    echo " -clean"
+                    echo ' -skip'
+					echo " -all"
+                    echo ' -r'
+                    echo " name = Maximise module/subdir name"
+                    echo " "
+                    exit 1
+                ;;
+
+
+			   	-verbose) 	VERBOSE=1
+			   	;;
+
+				-quiet)  	VERBOSE=0
+                            QUIET=1
+               	;;
+
+			   	-clean) 	CLEAN=1
+			   	;;
+
+			   	-skip) 		SKIP=1
+			   	;;
+
+
+			   	-all) 		DOALL=1
+			   	;;
+
+			   	-r) 		RECURSIVE=1
+			   	;;
+
+			   	*)
+			   				if [ -d $a ]
+							then
+								SUBDIR=$a
+                            else
+								echo "ERROR: parameter $a not recognised - not subdir"
+								exit 1
+                            fi
+               	;;
+
+
+		  ####
+		  esac
+          ####
+	####
+	done
+    ####
+
+    echo "Processing \"$PWD\""
+
+    ####
+	doit
+    ####
+
+
+    if test "$RECURSIVE" = "1"
+    then
+
+	    ROOTDIR=$PWD
+		ALLSUBDIRS=`ls -l | grep "^d" | awk '{print $NF}'`
+
+		################################
+        for subsystem in $ALLSUBDIRS; do
+		################################
+
+            echo "Processing \"$subsystem\""
+			cd $ROOTDIR/$subsystem ;
+
+            if [ "$subsystem" = "cm" ]
+            then
+				cd $ROOTDIR/$subsystem/source
+            fi
+
+		    ####
+			doit
+		    ####
+
+        ####
+        done
+        ####
+
+    fi
+
+	if test "$QUIET" = "0"
+   	then
 		echo "'prepmake' completed. You can now run generated make files using "
 		echo "'amake' script. see 'amake -help' for instructions"
-		exit 0
-	fi
+    else
+        echo "prepmake: OK"
+    fi
+
+	exit 0
 
 #------------------------------ EOF -------------------------------------
