mkproject and amake/amakeallo testing

diff --git a/aubit4glsrc/trunk/bin/amakeallo b/aubit4glsrc/trunk/bin/amakeallo
--- a/aubit4glsrc/trunk/bin/amakeallo
+++ b/aubit4glsrc/trunk/bin/amakeallo
@@ -1035,11 +1035,39 @@ function compglobals {
 function runamake {
 ###################
 
+                #allsinglelibs.mk is just a collector for all single
+                #file compilations, when using prepmake:
+                if [ "$i" = "allsinglelibs.mk" ]
+                then
+                    return
+                fi
+
                 #########################################################
-				#it can also be .aox and dummy.ao (allsinglelibs.mk) !!!
+				#set filename of resulting target:
                 #########################################################
+				#FIXME: it can also be dummy.ao (allsinglelibs.mk) !!!
 				EXECFILE=`basename $i .mk`.4ae;
 				EXECFILEAOX=`basename $i .mk`.aox;
+
+                #########################################################
+                #Clean targed and objects as configured:
+                #########################################################
+				if test "$FULLCLEAN" = "1"
+                then
+					amake $i clean
+				fi
+
+				if test "$TARGETCLEAN" = "1"
+                then
+					#pass -cleantarget to amake instead
+					#if [ -f $EXECFILE ]
+	                #then
+					#	rm $EXECFILE
+	                #fi
+					#FIXME: need to code it!
+					amake $i cleantarget
+                fi
+
 
                 #########################################################
 				#if we allrealy have this one linked in storrage dir, skip it:
@@ -1076,14 +1104,6 @@ function runamake {
                     fi
 					return
                 fi
-
-                #########################################################
-                #pass -cleantarget to amake instead
-                #########################################################
-				#if [ -f $EXECFILE ]
-                #then
-				#	rm $EXECFILE
-                #fi
 
 				let ATTEMPTED=ATTEMPTED+1
 
@@ -1154,35 +1174,6 @@ function runamake {
 					cat $i.make.log >> /tmp/allmakeerr.log
 
                     #########################################################
-                    #can we link with alt compiler?
-                    #########################################################
-                    #if -compatfile was specified
-
-					if test "$USECOMPATFILE" = "1"
-		            then
-						amake -verbose $i d4gl-pcode > $i.alt.log 2> $i.make.alt.log
-						RET=$?
-
-						if test $RET != "0"
-						then
-			                let FAILCOMPATIBLE=FAILCOMPATIBLE+1
-							if [ "$VERBOSE" = "1" ]
-						    then
-								echo "Ignoring error - $i fails to link with alt compiler too."
-		                    fi
-							echo "Ignoring error - $i fails to link with alt compiler too." >> $AMAKEERRORLOG
-		                    echo $i >> $ALTLINKFAILLIST
-							return
-                        else
-							if [ "$VERBOSE" = "1" ]
-						    then
-								echo "Links OK with alt compiler: $i."
-		                    fi
-							echo "Links OK with alt compiler: $i." >> $AMAKEERRORLOG
-						fi
-					fi
-
-                    #########################################################
 					#get name make failed on:
                     #########################################################
 					PROBLEMFILE=$(cat $i.make.log | grep "make: ***" | awk '{print $3}')
@@ -1190,7 +1181,7 @@ function runamake {
 
 					if test $RET != "0"
 					then
-		                echo "error in: PROBLEMFILE=$(cat $i.make.log | grep "make: ***" | awk '{print $3}')"
+		                echo "error in PROBLEMFILE formula"
         		        exit 44
 		            fi
 
@@ -1198,7 +1189,7 @@ function runamake {
 					PROBLEMFILE=`echo $X | sed -e "/./s/\]//"`
 					if [ "$SCRIPTDEBUG" = "1" ]
 				    then
-						echo 1 $PROBLEMFILE
+						echo Problem file name was $PROBLEMFILE
                     fi
 
 					#/usr/aubit/aubit4glsrc/bin/amakeallo: /usr/aubit/aubit4glsrc/bin/amake: Text file busy
@@ -1215,7 +1206,7 @@ function runamake {
                         #we did have .ao, so we failed on 4gl compile
 						if [ "$SCRIPTDEBUG" = "1" ]
 					    then
-							echo "was 4gl"
+							echo "Problem file was 4gl"
                         fi
 						PROBLEMFILE=$Y.4gl;
 
@@ -1233,7 +1224,7 @@ function runamake {
                         	#we did have .4ae, so we failed on maikng executable.
 							if [ "$SCRIPTDEBUG" = "1" ]
 						    then
-								echo "was exec"
+								echo "Problem file was exec"
                             fi
 							PROBLEMFILE=$Y.exec;
                         else
@@ -1244,10 +1235,22 @@ function runamake {
 	                        	#we did have .aox, so we failed on linking library.
 								if [ "$SCRIPTDEBUG" = "1" ]
 							    then
-									echo "was lib"
+									echo "Problem file was lib"
                                 fi
 								PROBLEMFILE=$Y.lib;
                             else
+
+#------------------- Running amake -verbose A1F.mk ----------------------
+#1 No
+#Failed on No, not .ao, .aox or .4ae ? STOP.
+								
+# amake -verbose A1F.mk
+#Command is: make -f A1F.mk
+#make: *** No rule to make target `pinqwind.aox', needed by `A1F.4ae'.  Stop.
+#ERROR: amake failed.
+
+#FIXME : add -quiet to prepmake
+
 								echo "Failed on $PROBLEMFILE, not .ao, .aox or .4ae ? STOP."
     	                        exit 33
                             fi
@@ -1363,7 +1366,8 @@ function runamake {
 
 					if test "$USECOMPATFILE" = "1"
 		            then
-						amake -verbose $i d4gl-pcode > $i.alt.log 2> $i.make.alt.log
+						#amake -verbose $i d4gl-pcode > $i.alt.log 2> $i.make.alt.log
+                        amake -verbose $i d4gl-pcode > $i.alt.log 2>&1
 						RET=$?
 
 						if test $RET != "0"
@@ -1373,9 +1377,15 @@ function runamake {
 						    then
 								echo "Ignoring error - $i fails to link with alt compiler too."
 		                    fi
-							echo "Ignoring error - $i fails to link with alt compiler too." >> $AMAKEERRORLOG
-		                    echo $i >> $ALTLINKFAILLIST
-							return
+							if [ "$SCRIPTDEBUG" = "1" ]
+						    then
+								echo "Ignoring error - $i fails to link with alt compiler too:" >> $AMAKEERRORLOG
+			                    echo $i >> $ALTLINKFAILLIST
+								echo "################################################# $PWD/$i" >> $AMAKEERRORLOG 2>&1
+	                            cat $i.alt.log >> $AMAKEERRORLOG
+								echo "#########################################################" >> $AMAKEERRORLOG 2>&1
+                            fi
+        					return
                         else
 							if [ "$VERBOSE" = "1" ]
 						    then
@@ -1442,10 +1452,12 @@ function makecurrentdir {
 				then
                     echo "Text file busy =  Error 126"
 					echo "Text file busy =  Error 126" >> $AMAKEERRORLOG
-                    return
+                    exit 11
+                    #return
                 else
-					echo "prepmake failed"
-					echo "prepmake failed"  >> $AMAKEERRORLOG
+					echo "prepmake failed ($RET)"
+					echo "prepmake failed ($RET)"  >> $AMAKEERRORLOG
+                    #exit 12
         	        return
                 fi
             fi
@@ -1603,7 +1615,8 @@ function doit {
 	GOBACKLINES=20
 	GOAFTERLINES=10
     FULLCLEAN=0
-    COMPATIBLE=0
+	TARGETCLEAN=0
+	COMPATIBLE=0
 	USECOMPATFILE=0
     VERBOSE=0
     SCRIPTDEBUG=0
@@ -1612,6 +1625,7 @@ function doit {
 	TESTCONTINUE=0
 	AMAKE=0
 	MOVETOSTORE=1
+
 
     #------------- strings: ------------------
 
@@ -1655,6 +1669,37 @@ function doit {
 	   ##########
 	   case $a in
 	   ##########
+
+       -cmp)     	#amakeallo -r -compatfile -maxmodeminimal -nonglob
+		            RECURSIVE=1
+					COMPATIBLE=1
+					USECOMPATFILE=1
+	                MAXMODE=1
+					MAXMODE2=1
+					NONGLOBAFTERGLOBERR=1
+
+					VERBOSE=1
+                    SCRIPTDEBUG=1
+
+	   ;;
+
+
+       -link)
+					#amakeallo -r -compatfile -maxmodeminimal -amake
+		            RECURSIVE=1
+					COMPATIBLE=1
+					USECOMPATFILE=1
+	                MAXMODE=1
+					MAXMODE2=1
+					AMAKE=1
+
+					#TARGETCLEAN=1
+					FULLCLEAN=1
+					CLEANMK=1
+					VERBOSE=1
+                    SCRIPTDEBUG=1
+
+	   ;;
 
 	   -x)
 	        for file in *.ae; do
diff --git a/aubit4glsrc/trunk/bin/genmake b/aubit4glsrc/trunk/bin/genmake
--- a/aubit4glsrc/trunk/bin/genmake
+++ b/aubit4glsrc/trunk/bin/genmake
@@ -19,21 +19,137 @@ then
     exit 2
 fi
 
-FIRST=`basename $1`
+	#filer out crap:
+    CMDLINE=
+    CMDLINEBASENAME=
+	CNT=0
+    CNTALL=0
+    CNTSKIP=0
+	###########
+	for a in $@
+    ###########
+	do
+        let CNTALL=CNTALL+1
+		DIRNAME=`dirname $a`
+        FULLNAME=$a
+		a=`basename $a`
+		if ! [ "$a" = "libfgl4js.42x" -o "$a" = "crap" ]
+        then
+	        let CNT=CNT+1
+            if [ "$DIRNAME" != "" ] && [ "$DIRNAME" != "." ]
+            then
+	            if [ "$DIRNAME" != "$PWD" ]
+    	        then
+					#PROBLEMFILE=`echo $X | sed -e "/./s/\]//"`
+					#LASTDIR=`echo $DIRNAME | sed -e "/$MAXDIR/s/$MAXDIR//"`
+					A1=$(echo $MAXDIR | sed -e "s/\//\\\\\//g")
+					A2=$(echo $DIRNAME | sed -e "s/$A1//")
+					#echo "DIRNAME = $DIRNAME"
+                    #echo "LASTDIR = $LASTDIR"
+					if [ "$A2" != "/gprog" ] && [ "$A2" != "/gform" ]
+                    then
+						#if this happens, add it to vpath
+						echo "$FULLNAME points outside current dir, to $A2. STOP."
+    	                exit 67
+                    fi
+                fi
+            fi
+			STRIPPATH=`basename $a`
+			CMDLINE="$CMDLINE $a"
+			CMDLINEBASENAME="$CMDLINEBASENAME $STRIPPATH"
+
+   			#first and  second can't be .42x
+            ##########
+			case $a in
+            ##########
+
+            *.42x)
+				if test "$CNT" = "1" -o "$CNT" = "2"
+                then
+                    echo "Got $a in first or second position. STOP"
+                    exit 56
+                fi
+            ;;
+
+            *)
+				if test "$CNT" = "1"
+	            then
+					#FIRST=`basename $a`
+	                FIRST=$a
+	            fi
+	            if test "$CNT" = "2"
+	            then
+					#SECOND=`basename $a`
+	                SECOND=$a
+	            fi
+	        ;;
+
+			####
+			esac
+			####
+
+
+
+        else
+            let CNTSKIP=CNTSKIP+1
+		fi
+    ####
+	done
+    ####
 
 PROG=`basename $FIRST .4go`
 if [ "$PROG" != "$FIRST" ]
 then
     IS4GO="1"
+    IS42M="0"
     ISLIB="1"
+    OBJEXT=4go
+    PROGEXT=4gi
+	LIBEXT=4go
+
 else
+	PROG=`basename $FIRST .42m`
+	if [ "$PROG" != "$FIRST" ]
+	then
+	    IS4GO="0"
+	    IS42M="1"
+    	ISLIB="1"
+        OBJEXT=42m
+        PROGEXT=42r
+	    LIBEXT=42x
+
+    else
+	    IS4GO="0"
+	    IS42M="0"
+		ISLIB="0"
+    fi
+fi
+
+if test "$ISLIB" = "0"
+then
 	PROG=`basename $FIRST .4gi`
 	if [ "$PROG" != "$FIRST" ]
 	then
 	    IS4GI="1"
+		FJSLINKLINE=0
+        OBJEXT=4go
+        PROGEXT=4gi
+		LIBEXT=4go
 	else
-        echo "Cannot recognise extension of $1. STOP."
-        exit 4
+		PROG=`basename $FIRST .42r`
+		if [ "$PROG" != "$FIRST" ]
+		then
+		    IS4GI="1"
+            #we are extracting components from 4Js link line, not from
+            #dependencies list:
+			FJSLINKLINE=1
+            OBJEXT=42m
+            PROGEXT=42r
+	        LIBEXT=42x
+        else
+			echo "Cannot recognise extension of $FIRST STOP."
+    	    exit 4
+        fi
 	fi
 fi
 
@@ -41,6 +157,8 @@ fi
 	#HEADERNAME=header.mki
 	FOOTERNAME='${AUBITDIR}/incl/footer.mki'
 	FORMFILES=
+    LIBLIST=
+    FGLLIST=
 
 
 #if we revceived only prog name and one 4gl file, AND program name is one
@@ -49,16 +167,16 @@ if [ $# = "2" ] && [ "$ISLIB" = "1" ]
 then
     IS_SINGLE_LIB="1"
 	FILENAME=allsinglelibs.mk
-	fname=`basename $2 .4go`
+	fname=`basename $SECOND .$OBJEXT`
 	fname=`basename $fname .4gl`
 
     if ! [ -f $FILENAME ]
     then
 		echo include $HEADERNAME > $FILENAME
 		echo >> $FILENAME
-		echo #we are using this dummy name only to get all in objects- >> $FILENAME
-        echo #it will not be used for anything - and it will possibly >> $FILENAME
-        echo #even fail to link: >> $FILENAME
+		echo '#we are using this dummy name only to get all in objects-' >> $FILENAME
+        echo '#it will not be used for anything - and it will possibly' >> $FILENAME
+        echo '#even fail to link:' >> $FILENAME
 		echo "PROG		= dummy.lib"  >> $FILENAME
 		echo >> $FILENAME
 		echo "GLOBALS.4gl	= $fname.4gl" >> $FILENAME
@@ -85,20 +203,18 @@ else
     fi
 	echo >> $FILENAME
 
-	fname=`basename $2 .4go`
+	fname=`basename $SECOND .$OBJEXT`
 	fname=`basename $fname .4gl`
 	echo "GLOBALS.4gl	= $fname.4gl" >> $FILENAME
-
 	echo >> $FILENAME
-	echo 'FILES.4gl	= \' >> $FILENAME
-	echo '		${GLOBALS.4gl} \' >> $FILENAME
-	###########
-	for a in $@
-    ###########
+
+	##################
+	for a in $CMDLINE
+    ##################
 	do
-		if ! [ "$1" = $a ] 		#it's program name
+		if ! [ "$FIRST" = $a ] 		#it's program name
         then
-	        if ! [ "$2" = $a ]  #it's GLOBALS file
+	        if ! [ "$SECOND" = $a ]  #it's GLOBALS file
             then
 
 			##########
@@ -106,9 +222,11 @@ else
 	        ##########
 
 			#*.42m) || *.4go) HOW THE HELL DO YOU DO _OR_here ?
-			*.4go)
-				fname=`basename $a .4go`
-                EXT=ao
+			#*.4go)
+            *.$OBJEXT)
+				fname=`basename $a .$OBJEXT`
+                #EXT=ao
+                EXT=4gl
 
 				#cinqwind is BOTH a 4gl and library (.42x, .aox) name
                 #which is VERY stupid thing to do, and should be fixed in Maximise;
@@ -117,12 +235,27 @@ else
 				#Maybe I shoud use "fgllink..." line to get files, and not dependencies?)
 				if [ "$fname" = "cinqwind" -o "$fname" = "invwind" -o "$fname" = "lic_keys" -o "$fname" = "pinqwind" -o "$fname" = "wcustwind" -o "$fname" = "wordrwin" -o "$fname" = "wpinqwind" ]
                 then
-					EXT=aox
+					if [ "$OBJEXT" = "4go" ]
+                    then
+						#EXT=aox
+						#if [ "$LIBLIST" = "" ]
+					    #then
+						#	#echo '		${FILES.lib} \' >> $FILENAME
+                	    #fi
+						LIBLIST="$LIBLIST $fname.lib"
+                    else
+    	                FGLLIST="$FGLLIST $fname.$EXT"
+                    fi
+                else
+                    FGLLIST="$FGLLIST $fname.$EXT"
                 fi
 
-	            echo "			$fname.$EXT \\" >> $FILENAME
-
 			;;
+
+            *.$LIBEXT)
+				fname=`basename $a .$LIBEXT`
+                LIBLIST="$LIBLIST $fname.lib"
+            ;;
 
 			#*.42f) || *.frm)
 	        *.frm)
@@ -131,7 +264,19 @@ else
 	        ;;
 
 	        *) echo "ERROR: what the hell is $a"
-	            exit 1
+
+				echo "IS4GO = $IS4GO"
+			    echo "IS42M = $IS42M"
+		    	echo "ISLIB = $ISLIB"
+		        echo "$OBJEXT"
+		        echo "$PROGEXT"
+			    echo "$LIBEXT"
+                echo "---------------------------x"
+				echo $CMDLINEBASENAME
+                echo "---------------------------x"
+                echo $FIRST $SECOND
+				#echo $@
+				exit 1
 
 	        ;;
 
@@ -145,7 +290,60 @@ else
     ####
 
 	echo >> $FILENAME
-   	if [ "$ISLIB" != "1" ]
+
+    ############################
+	#Write all libs to makefile:
+    ############################
+	if [ "$LIBLIST" != "" ]
+    then
+
+		echo 'FILES.lib	= \' >> $FILENAME
+		#################
+		for a in $LIBLIST
+	    #################
+		do
+            echo "			$a \\" >> $FILENAME
+        ####
+        done
+        ####
+
+		echo >> $FILENAME
+    fi
+
+    ############################
+	#Write all 4gl's to makefile:
+    ############################
+	if [ "$FGLLIST" != "" ]
+    then
+		echo 'FILES.4gl	= \' >> $FILENAME
+		echo '			${GLOBALS.4gl} \' >> $FILENAME
+
+		#if [ "$LIBLIST" != "" ]
+		#then
+		#	echo '			${FILES.lib} \' >> $FILENAME
+        #fi
+
+		#################
+		for a in $FGLLIST
+	    #################
+		do
+            echo "			$a \\" >> $FILENAME
+        ####
+		done
+        ####
+
+		echo >> $FILENAME
+    #else
+        #This can happen with porgrams that have only one 4gl file
+		#echo FGLLIST is empty
+        #exit 44
+
+	fi
+
+    ############################
+	#Write all forms to makefile:
+    ############################
+	if [ "$ISLIB" != "1" ]
     then
 
 		if [ "$FORMFILES" = "" ]
@@ -164,6 +362,9 @@ else
 	    fi
     fi
 	
+    ############################
+	#Write footer to makefile:
+    ############################
 	echo >> $FILENAME
     #echo "#-------------------------------------" >> $FILENAME
 	#echo >> $FILENAME
