iamakeallo and new regression-fails

diff --git a/aubit4glsrc/trunk/bin/amakeallf b/aubit4glsrc/trunk/bin/amakeallf
--- a/aubit4glsrc/trunk/bin/amakeallf
+++ b/aubit4glsrc/trunk/bin/amakeallf
@@ -1,7 +1,37 @@
 #!/bin/sh
-
+######################################################################
 #Aubit 4gl
 #Compiles all per files in current directory to objects
+#
+#Very usefull for finding compiler syntax errors on large number of per
+#files. Run it in your form files directory, and it will generate
+#log of all compiles, and copy all problematic files in separate
+#directory, including err and c files.
+#
+#
+#
+######################################################################
+
+
+
+############################
+function stats {
+############################
+	echo "$COMPSUCCESS sucessfully compiled, $COMPFAILPER failed in form compiler, $COMPBEFORE already compiled."
+    echo "$COMPFAILCCOMP failed in C compiler, $COMPFAILCORE dumped core, $COMPFAILUNKNOWN failed for unknown reason."
+	let TOTALFAILED=COMPFAILPER+COMPFAILCCOMP+COMPFAILCORE+COMPFAILUNKNOWN
+    echo "$TOTALFAILED total failed."
+
+}
+
+############################
+function shortstats {
+############################
+	echo "OK= $COMPSUCCESS 4gl= $COMPFAILPER skip= $COMPBEFORE c= $COMPFAILCCOMP core= $COMPFAILCORE ?= $COMPFAILUNKNOWN "
+
+}
+
+
 
 ###################
 function doit {
@@ -69,7 +99,8 @@ function compper {
 		if [ -f $MAXDIR/$DESTDIR/$X ]
 		then
 			#echo "$MAXDIR/$DESTDIR/$X exists - skip is on"
-	        continue
+			let COMPBEFORE=COMPBEFORE+1
+			continue
 		else
 			#echo "#------- Running $FORMCOMPILER $i in $PWD : -------------"  >> $ERRORLOG
 			echo Running $FORMCOMPILER $i in $PWD:;
@@ -95,9 +126,18 @@ function compper {
 		    echo "$ERR was generated."
 			cp $ERR $ALLERRDIR
 	        cat $ERR | grep -B 3 $ERRCHAR >> $ERRORLOG
+			let COMPFAILPER=COMPFAILPER+1
 		else
 	        echo "ERR file was __NOT__ generated."
 	        echo "ERR file was __NOT__ generated." >> $ERRORLOG
+
+            if [ -f core ]
+            then
+                let COMPFAILCORE=COMPFAILCORE+1
+                rm -f core
+            else
+				let COMPFAILPER=COMPFAILPER+1
+            fi
 		fi;
         echo "##########################################################" >> $ERRORLOG
 	    if test $STOPONERROR = "1"
@@ -107,15 +147,14 @@ function compper {
 	    else
 	        continue
 		fi
-	#else
-	#	echo "$FORMCOMPILER succeded, return code is $RET"
 	fi;
 
-	if [ -f $X ]
+	if [ -f $X ]  #no err code, but did we generate the object?
 	then
 	    mv $X $MAXDIR/$DESTDIR
 		if [ -f $ERR ]
 		then
+			let COMPFAILPER=COMPFAILPER+1
 			echo "#$PWD/$i failed, return code is $RET"  >> $ERRORLOG
 			echo "$ERR _AND_ $X was generated, but $FORMCOMPILER did not return error code."
 		    echo "#$ERR _AND_ $X was generated, but $FORMCOMPILER did not return error code."  >> $ERRORLOG
@@ -142,9 +181,17 @@ function compper {
 		    echo "$ERR was generated."
 			cp $ERR $ALLERRDIR
 	        cat $ERR | grep -B 3 $ERRCHAR >> $ERRORLOG
+			let COMPFAILPER=COMPFAILPER+1
 		else
 			echo "$ERR was __NOT__ generated."
 			echo "#$ERR was __NOT__ generated."  >> $ERRORLOG
+            if [ -f core ]
+            then
+                let COMPFAILCORE=COMPFAILCORE+1
+                rm -f core
+            else
+				let COMPFAILPER=COMPFAILPER+1
+            fi
 		fi;
         echo "##########################################################" >> $ERRORLOG
 
@@ -158,10 +205,12 @@ function compper {
 
 	fi;
 
+    let COMPSUCCESS=COMPSUCCESS+1
 
-	#####
+
+	####
 	done
-	#####
+	####
 
 
 }
@@ -170,95 +219,169 @@ function compper {
 #MAIN
 ###############
 
-#############
-#configuration:
-SKIP=skip
-ROOTDIR=$PWD
-COMPILER=aubit
-ALLERRDIR=/tmp/amakeallf
-STOPONERROR=0
-ERRORLOG=/tmp/amakeallf/amakeallf.log
+	#############
+	#configuration:
+	SKIP=skip
+	ROOTDIR=$PWD
+	COMPILER=aubit
+	ALLERRDIR=/tmp/amakeallf
+	STOPONERROR=0
+	ERRORLOG=/tmp/amakeallf/amakeallf.log
+
+	###############
+	#initialise:
+	WASERROR=0
+	COMPSUCCESS=0
+	COMPBEFORE=0
+	COMPFAILFRM=0
+	COMPFAILCCOMP=0
+	COMPFAILCORE=0
+	COMPFAILUNKNOWN=0
+    TOTALFAILED=0
+
+	############
+	for a in $@
+	############
+	do
+	   ##########
+	   case $a in
+	   ##########
+
+	   -x)
+	        cd aform
+	        for file in *.frm; do
+	            AONAME=`basename $file .frm`.afr;
+				echo moving $file to $AONAME
+				mv $file $AONAME
+	        done
+	        echo Finished renaming.
+	        exit 0
+		;;
+
+	    -r) 		RECURSIVE=1
+        ;;
+
+		-4js)		COMPILER=4js
+        ;;
+
+		-stoperr)	STOPONERROR=1
+        ;;
+
+        -noskip) 	SKIP=noskip
+        ;;
+
+        -tmp)  DESTDIR=/tmp/amakeallo-forms
+		;;
 
 
-if [ "$COMPILER" = "4js" ]
-then
-	#4Js/D4GL:
-	FORMCOMPILER=fglform
-	COMPEXT=42f
-	DESTDIR=gform
-	ERRCHAR=#
-fi
+        -help)
 
-if [ "$COMPILER" = "aubit" ]
-then
-	#Aubit 4gl:
-	FORMCOMPILER=fcompile
-	COMPEXT=frm
-	DESTDIR=aform
-	ERRCHAR=\|
-
-	if [ -f $AUBITDIR/aubitenv ]
-	then
-		. $AUBITDIR/aubitenv
-	fi
-
-	if [ -f /etc/aubitenv ]
-	then
-		. /etc/aubitenv
-	fi
-
-fi
+            echo "Aubit 4gl compiler form compile utillity: amakeallf"
+            echo " compiles all per files"
+            echo
+			echo "Options: [defaults are in ()]"
+			echo " -r = recursive: step into subdirectories too (. only)"
+			echo " -4js = use 4Js/D4GL compiler (Aubit)"
+			echo " -stoperr = stop on any error (continue)"
+			echo " -noskip = do not skip files that are already compiled (skip)"
+			echo " -x  = rename Aubit old extensions [.frm->.afr]"
+			echo " -tmp = move objects to /tmp/amakeallo-forms ('MAXDIR/?form')"
+			echo " -help = this help"
+            echo
+            exit 0
+        ;;
 
 
-if [ -d $ALLERRDIR ]
-then
-    rm -rf $ALLERRDIR
-fi
-
-mkdir $ALLERRDIR
-
-if [ -f $ERRORLOG ]
-then
-	rm $ERRORLOG
-fi
-
-if [ "$1" = "-r" ]
-then
-    #ALLDIR1=`ls -d *`
-    #echo $ALLDIR1
-    #exit 0
-
-	########################################################
-	for subsystem in ap ar eo fa gl in jm lc main qe re ss wo pu contr dvfund; do
-	########################################################
-
-		   if [ -d $ROOTDIR/$subsystem ]
-           then
-			   echo Making forms in $subsystem...
-			   cd $ROOTDIR/$subsystem ;
-	           doit
-	           if [ -d $ROOTDIR/$subsystem/ENG ]
-	           then
-		           cd $ROOTDIR/$subsystem/ENG
-				   echo Making forms in $subsystem/ENG...
-	               doit
-			   fi
-           fi
+	  ####
+	  esac
+	  ####
 	####
 	done
-    ####
-else
-	doit
-	ls *.err > /dev/null 2>&1
-	RET=$?
-	if test $RET = "0"
-	then
-		echo All error files:
-		ls *.err
-	fi
-fi
+	####
 
-echo Finished.
-echo "See $ERRORLOG for summary of all errors generated".
-exit 0
+
+	if [ "$COMPILER" = "4js" ]
+	then
+		#4Js/D4GL:
+		FORMCOMPILER=fglform
+		COMPEXT=42f
+		DESTDIR=gform
+		ERRCHAR=#
+	fi
+
+	if [ "$COMPILER" = "aubit" ]
+	then
+		#Aubit 4gl:
+		FORMCOMPILER=fcompile
+		COMPEXT=frm
+		DESTDIR=aform
+		ERRCHAR=\|
+
+		if [ -f $AUBITDIR/aubitenv ]
+		then
+			. $AUBITDIR/aubitenv
+		fi
+
+		if [ -f /etc/aubitenv ]
+		then
+			. /etc/aubitenv
+		fi
+
+	fi
+
+	if [ -d $ALLERRDIR ]
+	then
+	    rm -rf $ALLERRDIR
+	fi
+
+	mkdir $ALLERRDIR
+
+	if [ -f $ERRORLOG ]
+	then
+		rm $ERRORLOG
+	fi
+
+	if [ "$RECURSIVE" = "1" ]
+	then
+	    #FIXME: get list od subdirs from ls; BUT HOW?
+		#ALLDIR1=`ls -d *`
+	    #echo $ALLDIR1
+	    #exit 0
+
+		#############################################################################
+		for subsystem in ap ar eo fa gl in jm lc main qe re ss wo pu contr dvfund; do
+		#############################################################################
+
+			   if [ -d $ROOTDIR/$subsystem ]
+	           then
+				   echo Making forms in $subsystem...
+				   cd $ROOTDIR/$subsystem ;
+		           doit
+		           if [ -d $ROOTDIR/$subsystem/ENG ]
+		           then
+			           cd $ROOTDIR/$subsystem/ENG
+					   echo Making forms in $subsystem/ENG...
+		               doit
+				   fi
+	           fi
+		####
+		done
+	    ####
+	else
+		doit
+		ls *.err > /dev/null 2>&1
+		RET=$?
+		if test $RET = "0"
+		then
+			echo All error files:
+			ls *.err
+		fi
+	fi
+
+    #####
+	stats
+    #####
+	echo Finished.
+	echo "See $ERRORLOG for summary of all errors generated".
+	exit 0
 
