amake system work

diff --git a/aubit4glsrc/trunk/bin/amake b/aubit4glsrc/trunk/bin/amake
--- a/aubit4glsrc/trunk/bin/amake
+++ b/aubit4glsrc/trunk/bin/amake
@@ -14,15 +14,27 @@
 #####################################################################
 
 #`--include-dir=dir'
-#Specifies a directory dir to search for included makefiles. See section 
-#Including Other Makefiles. If several `-I' options are used to specify 
+#Specifies a directory dir to search for included makefiles. See section
+#Including Other Makefiles. If several `-I' options are used to specify
 #several directories, the directories are searched in the order specified.
 
 #defaults:
 LOG="0"
-OVERRIDEINCLUDE="1"
-HEADER="./header.mki"
-FOOTER="./footer.mki"
+LOGFILE=amake.log
+OVERRIDEINCLUDE="0"
+#HEADER="./header.mki"
+#FOOTER="./footer.mki"
+HEADER="$AUBITDIR/incl/header.mki"
+FOOTER="$AUBITDIR/incl/footer.mki"
+
+#if you export MAKERULES, ti will override 4gl make rules included in 
+#standard header.mki:
+RULESDIR=$AUBITDIR/incl
+#export MAKERULES=$RULESDIR/i4gl.mk $RULESDIR/d4gl.mk $RULESDIR/a4gl.mk $RULESDIR/q4gl.mk
+export MAKERULES=$RULESDIR/a4gl.mk
+
+rm -f *.err
+
 MAKE=make
 MK=".mk"
 
@@ -40,8 +52,10 @@ then
     echo "  to use make includes specified in this script"
     echo " -header xxx = use xxx file for header include, overrides -defaultinclude"
     echo " -footer yyy = use yyy file for footer include, overrides -defaultinclude"
+    echo " -i : ignore errors in amake and continue (adds -k to mkae call)"
 	echo " everything else will be passed to make"
-    echo
+	echo " -verbose = show what script is doing"
+	echo
 	echo Examples:
     echo
     echo "'amake' - build defailt targets of all .mk files in ./"
@@ -69,6 +83,8 @@ else
 	for a in $@
     ###########
 	do
+		a=`basename $a .mk`
+
 		let cnt=cnt+1
 
         #############
@@ -110,7 +126,14 @@ else
 			   -log) LOG="1"
 			   ;;
 
+			   -i) IGNOREERROR="1"
+                    MAKE="$MAKE -k"
+			   ;;
+
 			   -defaultinclude) OVERRIDEINCLUDE="0"
+			   ;;
+
+			   -verbose) VERBOSE="1"
 			   ;;
 
 			   -header) OVERRIDEINCLUDE="1"
@@ -167,24 +190,61 @@ fi
 	for ONEPROG in $PROGS
     #####################
     do
+        #see if we have include command in this .mk :
+		grep include $ONEPROG > /dev/null
+		RET=$?
+		if test $RET != "0"
+		then
+			OVERRIDEINCLUDE="1"
+		fi
+
 		if [ "$OVERRIDEINCLUDE" = "1" ]
         then
+			if [ "$VERBOSE" = "1" ]
+            then
+				echo "Overriding include..."
+            fi
 			INCLCMT="#include"
-			COMPOSITE=/tmp/$USER_$ONEPROG
+			COMPOSITE=/tmp/$USER-$ONEPROG
 			sed -e "s%include%$INCLCMT%g" $ONEPROG > $COMPOSITE.tmp
 	        cat $HEADER $COMPOSITE.tmp $FOOTER > $COMPOSITE
         else
-            $COMPOSITE=$ONEPROG
+			COMPOSITE=$ONEPROG
 		fi
+
+		if [ "$VERBOSE" = "1" ]
+        then
+            echo Command is: $MAKE $MKFLAGS -f $COMPOSITE $PARAMS
+        fi
+
 
 		if [ "$LOG" = "1" ]
 		then
-			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS > make.log 2>&1
+			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS > $LOGFILE 2>&1
         else
 			$MAKE $MKFLAGS -f $COMPOSITE $PARAMS
         fi
 
-        #FIXME: stop on error
+		RET=$?
+		if test $RET != "0"
+		then
+		    echo "ERROR: amake failed."
+			if [ "$LOG" = "1" ]
+			then
+				echo "See $LOGFILE"
+            fi
+		    ls *.err > /dev/null
+			RET=$?
+			if test $RET = "0"
+			then
+                echo "See .err files generated"
+            fi
+			if ! [ "$IGNOREERROR" = "1" ]
+            then
+				exit 1
+            fi
+		fi
+
     ####
 	done
     ####
diff --git a/aubit4glsrc/trunk/bin/amakeallf b/aubit4glsrc/trunk/bin/amakeallf
--- a/aubit4glsrc/trunk/bin/amakeallf
+++ b/aubit4glsrc/trunk/bin/amakeallf
@@ -3,145 +3,234 @@
 #Aubit 4gl
 #Compiles all per files in current directory to objects
 
+###################
+function doit {
+###################
+
+	ls *.per > /dev/null 2>&1
+	RET=$?
+	if test $RET != "0"
+	then
+	    echo "No .per files in current directory."
+	else
+
+		ls *.err > /dev/null 2>&1
+		RET=$?
+		if test $RET = "0"
+		then
+			echo Removing .err
+			rm *.err
+		fi
+
+		ls *.c > /dev/null 2>&1
+		RET=$?
+		if test $RET = "0"
+		then
+			echo Removing .c
+			rm *.c
+		fi
+
+		ls *.ec > /dev/null 2>&1
+		RET=$?
+		if test $RET = "0"
+		then
+			echo Removing .ec
+			rm *.ec
+		fi
+
+		ls *.frm > /dev/null 2>&1
+		RET=$?
+		if test $RET = "0"
+		then
+			echo Removing .frm
+			rm *.frm
+		fi
+
+		#######
+		compper
+		#######
+    fi
+
+}
+
+####################
+function compper {
+####################
+
+	####################
+	for i in *.per; do
+	####################
+	X=`basename $i .per`.frm;
+	ERR=`basename $i .per`.err;
+
+	if [ "x$SKIP" = "xskip" ]
+	then
+	    #echo "skip is on"
+		if [ -f $MAXDIR/aform/$X ]
+		then
+			echo "$MAXDIR/aform/$X exists - skip is on"
+	        continue
+		else
+			echo #------- Running fcompile $i in $PWD : -------------  >> $ERRORLOG
+			echo Running fcompile $i in $PWD:;
+			fcompile $i >> $ERRORLOG 2>&1;
+		fi
+	else
+	    #echo "Skip is OFF"
+		#echo fcompile $i;
+		echo #------- Running fcompile $i in $PWD : -------------  >> $ERRORLOG
+	    fcompile $i >> $ERRORLOG 2>&1;
+	fi
+
+	RET=$?
+	if test $RET != "0"
+	then
+		echo "#fcompile failed, return code is $RET"
+		cp $i $ALLERRDIR
+
+	    echo "#$ERR : ##################################################" >> $ERRORLOG
+		if [ -f $ERR ]
+		then
+		    echo "$ERR was generated."
+			cp $ERR $ALLERRDIR
+	        cat $ERR | grep -B 3 \| >> $ERRORLOG
+		else
+	        echo "ERR file was __NOT__ generated."
+	        echo "ERR file was __NOT__ generated." >> $ERRORLOG
+		fi;
+        echo "##########################################################" >> $ERRORLOG
+	    if test $STOPONERROR = "1"
+	    then
+			echo "Stop."
+			exit 1
+	    else
+	        continue
+		fi
+	#else
+	#	echo "fcompile succeded, return code is $RET"
+	fi;
+
+	if [ -f $X ]
+	then
+	    mv $X $MAXDIR/aform
+		if [ -f $ERR ]
+		then
+		    echo "$ERR _AND_ $X was generated, but fcompile did not return error code."
+		    echo "#$ERR _AND_ $X was generated, but fcompile did not return error code."  >> $ERRORLOG
+			ls *.err
+			if test $STOPONERROR = "1"
+		    then
+				echo "Stop."
+				exit 1
+		    else
+		        continue
+			fi
+
+		fi;
+
+	else
+		cp $i $ALLERRDIR
+	    echo "#$ERR : ##################################################" >> $ERRORLOG
+		echo "$X not generated, but fcompile did not return error code."
+		echo "#$X not generated, but fcompile did not return error code."  >> $ERRORLOG
+
+		if [ -f $ERR ]
+		then
+		    echo "$ERR was generated."
+			cp $ERR $ALLERRDIR
+	        cat $ERR | grep -B 3 \| >> $ERRORLOG
+		else
+			echo "$ERR was __NOT__ generated."
+			echo "#$ERR was __NOT__ generated."  >> $ERRORLOG
+		fi;
+        echo "##########################################################" >> $ERRORLOG
+
+		if test $STOPONERROR = "1"
+	    then
+			echo "Stop."
+			exit 1
+	    else
+	        continue
+		fi
+
+	fi;
+
+
+	#####
+	done
+	#####
+
+
+}
+
+###############
+#MAIN
+###############
+
 #SKIP=$1
 SKIP=skip
 
-. $AUBITDIR/aubitenv
+ROOTDIR=$PWD
+
+if [ -f $AUBITDIR/aubitenv ]
+then
+	. $AUBITDIR/aubitenv
+fi
+
+if [ -f /etc/aubitenv ]
+then
+	. /etc/aubitenv
+fi
+
+ALLERRDIR=/tmp/amakeallf
+if [ -d $ALLERRDIR ]
+then
+    rm -rf $ALLERRDIR
+fi
+
+mkdir $ALLERRDIR
 
 STOPONERROR=0
-ERRORLOG=/tmp/amakeallf.log
-rm $ERRORLOG
-
-
-
-ls *.err > /dev/null 2>&1
-RET=$?
-if test $RET = "0"
+ERRORLOG=/tmp/amakeallf/amakeallf.log
+if [ -f $ERRORLOG ]
 then
-	echo Removing .err
-	rm *.err
+	rm $ERRORLOG
 fi
 
-ls *.c > /dev/null 2>&1
-RET=$?
-if test $RET = "0"
+if [ "$1" = "-r" ]
 then
-	echo Removing .c
-	rm *.c
-fi
+    #ALLDIR1=`ls -d *`
+    #echo $ALLDIR1
+    #exit 0
 
-ls *.ec > /dev/null 2>&1
-RET=$?
-if test $RET = "0"
-then
-	echo Removing .ec
-	rm *.ec
-fi
-
-ls *.frm > /dev/null 2>&1
-RET=$?
-if test $RET = "0"
-then
-	echo Removing .frm
-	rm *.frm
-fi
-
-####################
-for i in *.per; do
-####################
-X=`basename $i .per`.frm;
-ERR=`basename $i .per`.err;
-
-if [ "x$SKIP" = "xskip" ]
-then
-    #echo "skip is on"
-	if [ -f $MAXDIR/aform/$X ]
-	then
-		echo "$MAXDIR/aform/$X exists - skip is on"
-        continue
-	else
-		#echo fcompile $i;
-		echo Running fcompile $i:;
-		fcompile $i >> $ERRORLOG 2>&1;
-	fi
+	########################################################
+	for subsystem in ap ar eo fa gl in jm lc main qe re ss wo pu contr dvfund; do
+	########################################################
+		   echo
+		   if [ -d $ROOTDIR/$subsystem ]
+           then
+			   echo Making forms in $subsystem...
+			   cd $ROOTDIR/$subsystem ;
+	           doit
+	           if [ -d $ROOTDIR/$subsystem/ENG ]
+	           then
+		           cd $ROOTDIR/$subsystem/ENG
+				   echo Making forms in $subsystem/ENG...
+	               doit
+			   fi
+           fi
+	####
+	done
+    ####
 else
-    #echo "Skip is OFF"
-	#echo fcompile $i;
-	echo Running fcompile $i:;
-    fcompile $i >> $ERRORLOG 2>&1;
-fi
-
-RET=$?
-
-if test $RET != "0"
-then
-	echo "fcompile failed, return code is $RET"
-	if [ -f $ERR ]
+	doit
+	ls *.err > /dev/null 2>&1
+	RET=$?
+	if test $RET = "0"
 	then
-	    echo "$ERR was generated."
-		#ls *.err
-        echo "$ERR : ###################################################" >> $ERRORLOG
-        cat $ERR | grep -B 3 \| >> $ERRORLOG
-	else
-        echo "ERR file was NOT generated."
-	fi;
-
-    if test $STOPONERROR = "1"
-    then
-		echo "Stop."
-		exit 1
-    else
-        continue
+		echo All error files:
+		ls *.err
 	fi
-else
-	echo "fcompile succeded, return code is $RET"
-fi;
-
-if [ -f $X ]
-then
-    mv $X $MAXDIR/aform
-else
-    echo "$X not generated, but fcompile did not return error code."
-	if [ -f $ERR ]
-	then
-	    echo "$ERR was generated."
-		#ls *.err
-	fi;
-
-	if test $STOPONERROR = "1"
-    then
-		echo "Stop."
-		exit 1
-    else
-        continue
-	fi
-
-fi;
-
-if [ -f $ERR ]
-then
-    echo "$ERR was generated, but fcompile did not return error code."
-	ls *.err
-	if test $STOPONERROR = "1"
-    then
-		echo "Stop."
-		exit 1
-    else
-        continue
-	fi
-
-fi;
-
-#####
-done
-#####
-
-ls *.err > /dev/null 2>&1
-RET=$?
-if test $RET = "0"
-then
-	echo All error files:
-	ls *.err
 fi
 
 echo Finished.
diff --git a/aubit4glsrc/trunk/bin/genmake b/aubit4glsrc/trunk/bin/genmake
--- a/aubit4glsrc/trunk/bin/genmake
+++ b/aubit4glsrc/trunk/bin/genmake
@@ -1,25 +1,94 @@
 #!/bin/sh
-
-############################################################
+##########################################################################
 #
-#   Aubit 4gl compiler - make system
-#genmake - utillity script to create Aubit-style makefiles
-#from typical existing 4gl makefiles
+#			Aubit 4gl compiler - make system
 #
-############################################################
+# genmake - utillity script to create Aubit-style makefiles from typical 
+# existing 4gl makefiles.
+#
+# You are not supposed to run this script mannualy; it will be called from
+# makefiles created with "prepmake" script.
+#
+##########################################################################
 
-#you are not supposed to run this script mannualy; it will be called from
-#makefiles created with "prepmake" script.
+if [ $# -lt 2 -o "$1" = "--help" ]
+then
+    echo "ERROR: not enough parameters."
+	echo "You are not supposed to run this script mannualy; it will be"
+	echo "called from makefiles created with 'prepmake' script."
+    exit 2
+fi
 
-FILENAME=$1.mk
+FIRST=`basename $1`
 
-	echo include header.mki > $FILENAME
+PROG=`basename $FIRST .4go`
+if [ "$PROG" != "$FIRST" ]
+then
+    IS4GO="1"
+    ISLIB="1"
+else
+	PROG=`basename $FIRST .4gi`
+	if [ "$PROG" != "$FIRST" ]
+	then
+	    IS4GI="1"
+	else
+        echo "Cannot recognise extension of $1. STOP."
+        exit 4
+	fi
+fi
+
+	HEADERNAME='${AUBITDIR}/incl/header.mki'
+	#HEADERNAME=header.mki
+	FOOTERNAME='${AUBITDIR}/incl/footer.mki'
+	FORMFILES=
+
+
+#if we revceived only prog name and one 4gl file, AND program name is one
+#of lib extensions, this is library function, not executable program:
+if [ $# = "2" ] && [ "$ISLIB" = "1" ]
+then
+    IS_SINGLE_LIB="1"
+	FILENAME=allsinglelibs.mk
+	fname=`basename $2 .4go`
+	fname=`basename $fname .4gl`
+
+    if ! [ -f $FILENAME ]
+    then
+		echo include $HEADERNAME > $FILENAME
+		echo >> $FILENAME
+		echo #we are using this dummy name only to get all in objects- >> $FILENAME
+        echo #it will not be used for anything - and it will possibly >> $FILENAME
+        echo #even fail to link: >> $FILENAME
+		echo "PROG		= dummy.lib"  >> $FILENAME
+		echo >> $FILENAME
+		echo "GLOBALS.4gl	= $fname.4gl" >> $FILENAME
+		echo >> $FILENAME
+		echo 'FILES.4gl	= \' >> $FILENAME
+		echo '		${GLOBALS.4gl} \' >> $FILENAME
+	else
+		echo "			$fname.4gl \\" >> $FILENAME
+	fi
+
+else
+	FILENAME=$PROG.mk
+
+	echo include $HEADERNAME > $FILENAME
 	echo >> $FILENAME
     #echo "#-------------------------------------" >> $FILENAME
 	#echo >> $FILENAME
-	echo "PROG		= $1"  >> $FILENAME
+
+	if [ "$ISLIB" = "1" ]
+    then
+		echo "PROG		= $PROG.lib"  >> $FILENAME
+    else
+		echo "PROG		= $PROG"  >> $FILENAME
+    fi
 	echo >> $FILENAME
-	echo "GLOBALS.4gl	= $2" >> $FILENAME
+
+	fname=`basename $2 .4go`
+	fname=`basename $fname .4gl`
+	echo "GLOBALS.4gl	= $fname.4gl" >> $FILENAME
+
 	echo >> $FILENAME
 	echo 'FILES.4gl	= \' >> $FILENAME
 	echo '		${GLOBALS.4gl} \' >> $FILENAME
@@ -27,29 +96,66 @@ FILENAME=$1.mk
 	for a in $@
     ###########
 	do
-        if ! [ "$1" = $a ]
+		if ! [ "$1" = $a ] 		#it's program name
         then
-	        if ! [ "$2" = $a ]
+	        if ! [ "$2" = $a ]  #it's GLOBALS file
             then
-                echo "		$a \\" >> $FILENAME
+
+			##########
+			case $a in
+	        ##########
+
+			#*.42m) || *.4go) HOW THE HELL DO YOU DO _OR_here ?
+			*.4go)
+				fname=`basename $a .4go`
+	            echo "			$fname.4gl \\" >> $FILENAME
+			;;
+
+			#*.42f) || *.frm)
+	        *.frm)
+				fname=`basename $a .frm`
+	            FORMFILES="$FORMFILES $fname.per"
+	        ;;
+
+	        *) echo "ERROR: what the hell is $a"
+	            exit 1
+
+	        ;;
+
+			####
+			esac
+			####
             fi
         fi
-    ####
+	####
 	done
     ####
 
 	echo >> $FILENAME
-	echo 'FILES.per	= ${ALLFORMS.per}' >> $FILENAME
+   	if [ "$ISLIB" != "1" ]
+    then
+
+		if [ "$FORMFILES" = "" ]
+	    then
+			#as defined in header.mki:
+			echo 'FILES.per	= ${ALLFORMS.per}' >> $FILENAME
+	    else
+			echo "FILES.per	= \\" >> $FILENAME
+
+			###################
+			for a in $FORMFILES
+		    ###################
+			do
+				echo "			$a \\" >> $FILENAME
+	        done
+	    fi
+    fi
+	
 	echo >> $FILENAME
     #echo "#-------------------------------------" >> $FILENAME
 	#echo >> $FILENAME
-	echo include footer.mki >> $FILENAME
+	echo include $FOOTERNAME >> $FILENAME
 	echo >> $FILENAME
-	echo
+fi
 
-
-
-
- 
-
-
+#------------------------------ EOF --------------------------------
diff --git a/aubit4glsrc/trunk/bin/prepmake b/aubit4glsrc/trunk/bin/prepmake
--- a/aubit4glsrc/trunk/bin/prepmake
+++ b/aubit4glsrc/trunk/bin/prepmake
@@ -7,6 +7,15 @@
 #
 ############################################################
 
+#Confirmed to work in :
+#gl
+#ap
+
+#$WARNING: some Maximise moduls depend on other modules already being
+#compiled. If they are not, makefile.prep will fail.
+#Compile modules in this order:
+#winds csimods main ar eo fa gl in jm lc qe re ss ap pu wo;
+
 
 #1. run "prepmake" in directory containing Maximise make file, "makefile".
 #This will create file "makefile.prep" containing instruction needed for
@@ -17,12 +26,60 @@
 #you want to process, look at the script, it should be easy to substitute
 #this with some other present command.
 
-INCLCMT='	genmake $(basename $(@F)) $(addsuffix .4gl,$(basename $(^F))) #'
-INCLCMT2="#fgllink"
+FILENAME=allsinglelibs.mk
+rm -f $FILENAME
 COMPOSITE=/tmp/makefile
 
-sed -e "s%cat%$INCLCMT%g" makefile > $COMPOSITE.tmp
-sed -e "s%fgllink%$INCLCMT2%g" $COMPOSITE.tmp > makefile.prep
+#replacing all "fgllink" lines with our command:
+#INCLCMT='	genmake $(basename $(@F)) $(addsuffix .4gl,$(basename $(^F))) #'
+#we don't want to rename ALL dependencies to .4gl they may be .per files!
+#INCLCMT='	genmake $(basename $(@F)) $(^F) #'
+#we alos don't want to strip extension from object name, it may be library
+#target, not executable:
+INCLCMT='	genmake $(@F) $(^F) #'
+
+sed -e "s%fgllink%$INCLCMT%g" makefile > $COMPOSITE.tmp
+
+#commenting out all "cat" lines, so they don't get executed:
+INCLCMT2="#cat "
+sed -e "s%cat %$INCLCMT2%g" $COMPOSITE.tmp > makefile.prep
+
+
+################### for GL #################################
+#INCLCMT2='touch $(addsuffix .42m,$(basename $($<)))'
+#INCLCMT2='touch $(basename $<).42m'
+INCLCMT2='touch $(notdir $(basename $<)).42m'
+#replace all fglcomp lines with fakes, so we don't go trough actual compile:
+sed -e "s%fglcomp%$INCLCMT2%g" makefile.prep > $COMPOSITE.tmp
+
+#INCLCMT2='touch $(notdir $(basename $<)).42f'
+INCLCMT2='touch $(basename $<).42f'
+#replace all fglform lines with fakes, so we don't go trough actual compile:
+sed -e "s%fglform%$INCLCMT2%g" $COMPOSITE.tmp > makefile.prep
+
+INCLCMT2='touch $(basename $<).frm'
+sed -e "s%form4gl%$INCLCMT2%g" makefile.prep > $COMPOSITE.tmp
+
+cp $COMPOSITE.tmp makefile.prep
+################### end for GL #################################
+
+
+################### for winds #################################
+#we need all fglpc replaced with commands, since in winds most files
+#are not programs, but library functions.
+INCLCMT3='	genmake $(@F) $(^F) #'
+sed -e "s%fglpc%$INCLCMT3%g" makefile.prep > $COMPOSITE.tmp
+
+
+#but we also need to process fgllink, since it creates composite library
+#objects (.42x)
+
+cp $COMPOSITE.tmp makefile.prep
+
+
+#################### end for winds #############################
+
+
 
 #2. run first "touch *.4gl" (to force all targets ito thinking they need
 #building) and then "make -f makefile.prep". This will create one make
@@ -33,5 +90,30 @@ sed -e "s%fgllink%$INCLCMT2%g" $COMPOSITE.tmp > makefile.prep
 
 touch *.4gl
 make -f makefile.prep
+RET=$?
+
+echo " "
+if test $RET != "0"
+then
+    echo "Error preparing make file, see makefile.prep "
+    exit 1
+else
+
+	#if we created single libs file, we need to add footer at the end:
+	FOOTERNAME='${AUBITDIR}/incl/footer.mki'
+
+	if [ -f $FILENAME ]
+    then
+		echo >> $FILENAME
+	    #echo "#-------------------------------------" >> $FILENAME
+		#echo >> $FILENAME
+		echo include $FOOTERNAME >> $FILENAME
+		echo >> $FILENAME
+    fi
+
+	echo "'prepmake' completed. You can now run generated make files using "
+	echo "'amake' script. see 'amake -help' for instructions"
+	exit 0
+fi
 
 #-------------------------- EOF -------------------------------
