More native Windows stuff

diff --git a/aubit4glsrc/trunk/bin/aubitbuild.sh.in b/aubit4glsrc/trunk/bin/aubitbuild.sh.in
--- a/aubit4glsrc/trunk/bin/aubitbuild.sh.in
+++ b/aubit4glsrc/trunk/bin/aubitbuild.sh.in
@@ -25,7 +25,7 @@
 # +----------------------------------------------------------------------+
 
 #
-# $Id: aubitbuild.sh.in,v 1.2 2002-10-27 22:34:02 afalout Exp $
+# $Id: aubitbuild.sh.in,v 1.3 2002-10-30 01:46:44 afalout Exp $
 #
 
 #Use this script in corn for Aubit nightly automatic builds
@@ -155,6 +155,10 @@ SHORTNAME=@SHORTNAME@
 SRCSHORTNAME=@SHORTNAME@src
 BINSHORTNAME=@SHORTNAME@bin
 
+#####################
+#name of the computer we are on:
+HOSTNAME=`hostname`
+
 ## ==================================================================
 ##                      Platform dependent Configuration
 ## ==================================================================
@@ -200,7 +204,15 @@ fi
 
 #####################
 #name for HTML template file of download page:
-DOWNLOADPAGE=$DLPAGEPATH/aubitdownload-template.htm
+if [ -f $DLPAGEPATH/aubitdownload-template.htm ]; then
+	DOWNLOADPAGE=$DLPAGEPATH/aubitdownload-template.htm
+else
+	#echo "$DLPAGEPATH/aubitdownload-template.htm is missing. Stop."
+	#exit 8
+	DOWNLOADPAGE_SCP=1  #we will get it from web server
+	DOWNLOADPAGE="aubitdownload-template.htm"
+fi
+
 #Name for download page when oploading to download web server:
 DOWNLOADPAGEBASE=aubitdownload.htm
 
@@ -247,6 +259,7 @@ function runexec {
 
 MAKE=0
 RPM=0
+WINSETUP=0
 GET=0
 UPLOAD=0
 CLEAN=0
@@ -259,6 +272,7 @@ if [ $# -lt 1 ]; then
 	    #UNIX
 	    MAKE=1
 	    RPM=1
+        WINSETUP=0
 	    GET=1
 	    UPLOAD=1
         CLEAN=1
@@ -266,6 +280,7 @@ if [ $# -lt 1 ]; then
 	    #Windows/CygWin
 	    MAKE=1
 	    RPM=0
+        WINSETUP=1
 	    GET=1
 	    UPLOAD=1
         CLEAN=0
@@ -284,6 +299,7 @@ else
 			echo "Actions:"
 			echo "  make - make tarballs, source and binary"
 			echo "  rpm - make RPM's, source and binary"
+            echo "  winsetup - make Windows Installer"
 			echo "  get - get download page template from web server"
 			echo "  upload - upload created files to web server"
 			echo "  clean - remove created files when finished"
@@ -301,6 +317,7 @@ else
 				    #UNIX
 				    MAKE=1
 				    RPM=1
+                    WINSETUP=0
 				    GET=1
 				    UPLOAD=1
 			        CLEAN=1
@@ -308,6 +325,7 @@ else
 				    #Windows/CygWin
 				    MAKE=1
 				    RPM=0
+                    WINSETUP=1
 				    GET=1
 				    UPLOAD=1
 			        CLEAN=0
@@ -320,7 +338,10 @@ else
 	    rpm)
 		    RPM=1
 	        ;;
-	    get)
+	    winsetup)
+            WINSETUP=1
+            ;;
+		get)
 		    GET=1
 	        ;;
 	    upload)
@@ -339,6 +360,21 @@ else
 	done
 fi
 
+set `type $AUTO_SF_SCP`
+if [ "$2" != "is" ]; then
+    echo "Script $AUTO_SF_SCP is missing. Stop."
+    exit 23
+fi
+set `type $AUTOSFSCPGET`
+if [ "$2" != "is" ]; then
+	echo "Script $AUTO_SF_SCP is missing. Stop."
+    exit 23
+fi
+set `type $AUTO_CVS`
+if [ "$2" != "is" ]; then
+    echo "Script $AUTO_SF_SCP is missing. Stop."
+    exit 23
+fi
 
 
 
@@ -388,7 +424,13 @@ if test "$MAKE" = "1"; then
 		STOPONERROR=1
 
 		EXEC="autoconf"; runexec
-		EXEC="make build"; runexec
+		
+		#increase build number, but doing this on more then one computer will cause
+        #problems with "cvs update"
+		if [ "$HOSTNAME" = "falout.org" ]; then
+			EXEC="make build"; runexec
+        fi
+
 		#configure will use aubitconf if it exists to provide switches:
 		#pasing parameters to configure from here will only work if aubitconf script is
         #not in the path
@@ -420,13 +462,19 @@ if test "$MAKE" = "1"; then
 
 			echo "Toatal compiler warnings: $WARNLINES"
 	        echo " "
-			grep "warning:" make.log
+			grep "warning:" make.log > warning.log
+			echo "See `PWD`/warning.log for details"
+	        echo " "
 
-			EXEC="make splint"; runexec
+			if [ "$COMSPEC" = "" ]; then
+				EXEC="make splint"; runexec
+				echo "All SPLint warnings: "
+				echo "                          Reported  Suppressed"
+				grep "^Total" lclint.log
+            else
+                echo "Fix splint"
+            fi
 
-			echo "All SPLint warnings: "
-			echo "                          Reported  Suppressed"
-			grep "^Total" lclint.log
         fi
 
 		################## install compiler ###############
@@ -497,10 +545,36 @@ else
 fi
 
 
+if test "$WINSETUP" = "1"; then
+    ################## make Windows installer #######################
+    STOPONERROR=0   #Continue even if next statemets fails
+    #EXEC="rm -f /usr/src/redhat/SRPMS/$SHORTNAME*.src.rpm"; runexec
+    #EXEC="rm -f /usr/src/redhat/RPMS/i586/$SHORTNAME*.rpm"; runexec
+    #EXEC="rm -rf /usr/src/redhat/BUILD/$SHORTNAME*"; runexec
+	STOPONERROR=1
+
+    EXEC="cd $AUBITSRCDIR"; runexec
+    EXEC="make winsetup"; runexec
+	#Setup program should now be at ${AUBITDIR}\etc\Output\setup.exe
+	WINSETUPEXE="$AUBITSRCDIR/etc/Output/setup.exe"
+	if ! [ -f $WINSETUPEXE ]; then
+		echo "Windows installer not created"
+        WINSETUPEXE=""
+    else
+		echo "FIXME: Windows installer created - do link replacing on dl page"
+	fi
+fi
 
 if test "$GET" = "1"; then
 
 		################### get things ####################
+
+		if [ "$DOWNLOADPAGE_SCP" = "1" ]; then
+			#This will fail first time we do it, if this server is not allsready 
+			#in the list of known hosts. It will ask us:
+            #Are you sure you want to continue connecting (yes/no)?
+			EXEC="$AUTOSFSCPGET $SCPPATH/$DOWNLOADPAGE"; runexec
+        fi
 
 		EXEC="cp $DOWNLOADPAGE $DLTMP1"; runexec
 
diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -7612,6 +7612,8 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
+
+
 #defaults for aubitrc:
 
 
@@ -7748,6 +7750,9 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
+#Inno Setup:
+
+
 
 #curses:
 
@@ -7843,8 +7848,10 @@ if test "$AUBIT_SOURCE" = "1" ; then
 	AUBIT_BUILD=`cat tools/project/build`
 fi
 
-FULLNAME="Aubit 4gl compiler"
+FULLNAME="Aubit 4GL compiler"
 SHORTNAME="aubit4gl"
+AUBIT_WEBSITE=aubit4gl.sf.net
+AUBIT_PUBLISHER="Aubit project development team"
 COMPILE_DATE=`date +%d-%m-%Y`
 test_rpclib="1"
 GTKBUILD=no
@@ -7928,9 +7935,18 @@ LDFLAGS_SHARED="$PIC -shared"
 ALL_LINGUAS="en"
 #AM_GNU_GETTEXT
 
-#check if we can install in $prefix
+## ==================================================================
+##            Decide on install location
+## ==================================================================
+
+
 	if test "$prefix" = "NONE"; then
-	    prefix="/opt"
+		if test "$cygwin" = "1" ; then
+			#/opt is not created by default on CygWin installations
+			prefix=/usr/local
+		else
+			prefix=/opt
+	    fi
 	fi
 	echo "$as_me:$LINENO: checking install root 'prefix=$prefix'" >&5
 echo $ECHO_N "checking install root 'prefix=$prefix'... $ECHO_C" >&6
@@ -7949,7 +7965,7 @@ echo "$as_me: error: Cannot determine install path. HOME=$HOME Stop." >&2;}
         fi
     fi
 
-LIB_PREFIX=$prefix/aubit4gl/lib
+LIB_PREFIX=$prefix/$SHORTNAME/lib
 
 #List of libraries that we allways make. Here so we don't have to maintain it
 #separately for RPM config file, install/deinstall and lib Makefile:
@@ -7983,6 +7999,12 @@ LIBFILE_27=
 LIBFILE_28=
 LIBFILE_29=
 LIBFILE_30=
+
+#Install location - must install first:
+#IS_SOURCE="$HOMEDRIVE\\cygwin$prefix\\$SHORTNAME"
+#Source code location:
+IS_SOURCE="$HOMEDRIVE\\cygwin$aubitdir"
+IS_SOURCE_GTK="$HOMEDRIVE\\cygwin\\lib"
 
 #Note: all command line switches like "--xxxx-wwwww" are automativaly
 #converted to shell variables in "xxxxx_wwwww" format.
@@ -9430,17 +9452,8 @@ if test "$CC" = "gcc"; then
 	echo "$as_me:$LINENO: checking GCC version" >&5
 echo $ECHO_N "checking GCC version... $ECHO_C" >&6
 
-	#$ gcc --version
-	#2.95.3-5
-
-	#$ gcc --version
-	#gcc (GCC) 3.2 20020818 (prerelease)
-
-	#gcc.exe (GCC) 3.2 (mingw special 20020817-1)
-
 	TMP_TMP=`gcc --version | head -1 | sed -e 's/^gcc (GCC) //' -e 's/ (prerelease)//' -e 's/\./ /g'`
 	TMP_TMP=`gcc --version | head -1 | sed -e 's/^gcc//' -e 's/(GCC)//' -e 's/ (prerelease)//' -e 's/(//' -e 's/\.exe//' -e 's/\./ /g'`
-	#  3 2 mingw special 20020817-1)
 	if test "$TMP_TMP" != ""; then
 		set `echo $TMP_TMP`
 		if test "$1" != ""; then
@@ -16187,28 +16200,22 @@ fi
 done
 
         fi
-echo 3
+
 		TMP=`eval echo '${'$as_ac_Header'}'`
 		#if test `eval echo '${'$as_ac_Header'}'` != "yes"; then
         if test "$TMP" != "yes"; then
-echo 4
-			if test "$GCC_MINGW" = "yes"; then
-				{ echo "$as_me:$LINENO: WARNING: No dlfcn.h found" >&5
-echo "$as_me: WARNING: No dlfcn.h found" >&2;}
-            else
-				{ { echo "$as_me:$LINENO: error: No dlfcn.h found - please install dl library. Stop." >&5
-echo "$as_me: error: No dlfcn.h found - please install dl library. Stop." >&2;}
-   { (exit 1); exit 1; }; }
+			if test "$GCC_MINGW" != "yes"; then
+				{ { echo "$as_me:$LINENO: error: No dlfcn.h found" >&5
+echo "$as_me: error: No dlfcn.h found" >&2;}
+   { (exit please install dl library. Stop.); exit please install dl library. Stop.; }; }
             fi
-echo 5
 		else
-echo 6
+
 			CFLAGS="$CFLAGS $TMP_IFLAGS"
         fi
-echo 7
+
 		CPPFLAGS="$old_CPPFLAGS"
     fi
-echo B
 fi
 
 ## ==================================================================
@@ -18684,7 +18691,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 18687 "configure"' > conftest.$ac_ext
+  echo '#line 18694 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -19152,7 +19159,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19155 "configure"
+#line 19162 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19250,7 +19257,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19253 "configure"
+#line 19260 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20807,18 +20814,6 @@ else
     fi
 fi
 
-## ==================================================================
-##            Decide on install location
-## ==================================================================
-
-if test "$prefix" = "NONE"; then
-	if test "$cygwin" = "1" ; then
-		#/opt is not created by default on CygWin installations
-		prefix=/usr/local
-	else
-		prefix=/opt
-    fi
-fi
 
 ## ==================================================================
 ##            Decide on default COMPILER OUTPUT driver
@@ -21014,7 +21009,7 @@ fi
 
 if test "$AUBIT_SOURCE" = "1" ; then
 
-	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile etc/aubitrc etc/aubit-rpm.spec incl/Makefile-common common/dataio/Makefile compilers/4glc/Makefile compilers/4glc/rules/Makefile compilers/fcompile/Makefile compilers/helpcompile/Makefile compilers/menus/Makefile compilers/ace/Makefile compilers/xgen/Makefile lib/libaubit4gl/Makefile lib/libform/form_xdr/Makefile lib/libform/noform/Makefile lib/libform/form_generic/Makefile lib/libmenu/menu_xdr/Makefile lib/libmenu/menu_nomenu/Makefile lib/libmenu/menu_generic/Makefile lib/libmsg/msg_native/Makefile lib/liblex/lex_c/Makefile lib/liblex/lex_perl/Makefile lib/libpdf/Makefile lib/libui/ui_console/Makefile lib/libui/ui_curses/Makefile lib/libui/ui_gtk/Makefile lib/resource/Makefile lib/libsql/nosql/Makefile lib/libsql/odbc/Makefile lib/libsql/esqlc/Makefile lib/libsql/postgresql/Makefile lib/libsql/sapdb/Makefile lib/librpc/no_rpc/Makefile lib/librpc/sun_rpc/Makefile lib/librpc/xml_rpc/Makefile lib/extra_libs/file/Makefile lib/extra_libs/string/Makefile lib/libpacker/packed/Makefile lib/libpacker/perl/Makefile lib/libpacker/xdr/Makefile lib/libpacker/xml/Makefile lib/libexdata/Makefile lib/swig/domake lib/Makefile tools/adbaccess/Makefile tools/loadmap/Makefile tools/adbload/Makefile tools/html/Makefile tools/ide/Makefile tools/jabber/Makefile tools/odbctest/Makefile tools/test/gui/Makefile tools/test/regression/Makefile tools/test/lang/Makefile tools/test/db/Makefile tools/test/Makefile bin/aubitbuild.sh docs/doxy/Doxyfile"
+	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ac_config_files="$ac_config_files Makefile etc/aubitrc etc/aubit-rpm.spec etc/aubit-InnoSetup.iss incl/Makefile-common common/dataio/Makefile compilers/4glc/Makefile compilers/4glc/rules/Makefile compilers/fcompile/Makefile compilers/helpcompile/Makefile compilers/menus/Makefile compilers/ace/Makefile compilers/xgen/Makefile lib/libaubit4gl/Makefile lib/libform/form_xdr/Makefile lib/libform/noform/Makefile lib/libform/form_generic/Makefile lib/libmenu/menu_xdr/Makefile lib/libmenu/menu_nomenu/Makefile lib/libmenu/menu_generic/Makefile lib/libmsg/msg_native/Makefile lib/liblex/lex_c/Makefile lib/liblex/lex_perl/Makefile lib/libpdf/Makefile lib/libui/ui_console/Makefile lib/libui/ui_curses/Makefile lib/libui/ui_gtk/Makefile lib/resource/Makefile lib/libsql/nosql/Makefile lib/libsql/odbc/Makefile lib/libsql/esqlc/Makefile lib/libsql/postgresql/Makefile lib/libsql/sapdb/Makefile lib/librpc/no_rpc/Makefile lib/librpc/sun_rpc/Makefile lib/librpc/xml_rpc/Makefile lib/extra_libs/file/Makefile lib/extra_libs/string/Makefile lib/libpacker/packed/Makefile lib/libpacker/perl/Makefile lib/libpacker/xdr/Makefile lib/libpacker/xml/Makefile lib/libexdata/Makefile lib/swig/domake lib/Makefile tools/adbaccess/Makefile tools/loadmap/Makefile tools/adbload/Makefile tools/html/Makefile tools/ide/Makefile tools/jabber/Makefile tools/odbctest/Makefile tools/test/gui/Makefile tools/test/regression/Makefile tools/test/lang/Makefile tools/test/db/Makefile tools/test/Makefile bin/aubitbuild.sh docs/doxy/Doxyfile"
 
 
 else
@@ -21541,6 +21536,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "etc/aubitrc" ) CONFIG_FILES="$CONFIG_FILES etc/aubitrc" ;;
   "etc/aubit-rpm.spec" ) CONFIG_FILES="$CONFIG_FILES etc/aubit-rpm.spec" ;;
+  "etc/aubit-InnoSetup.iss" ) CONFIG_FILES="$CONFIG_FILES etc/aubit-InnoSetup.iss" ;;
   "incl/Makefile-common" ) CONFIG_FILES="$CONFIG_FILES incl/Makefile-common" ;;
   "common/dataio/Makefile" ) CONFIG_FILES="$CONFIG_FILES common/dataio/Makefile" ;;
   "compilers/4glc/Makefile" ) CONFIG_FILES="$CONFIG_FILES compilers/4glc/Makefile" ;;
@@ -21725,6 +21721,8 @@ s,@aubitdir@,$aubitdir,;t t
 s,@COMPILE_DATE@,$COMPILE_DATE,;t t
 s,@AUBIT_VERSION@,$AUBIT_VERSION,;t t
 s,@AUBIT_BUILD@,$AUBIT_BUILD,;t t
+s,@AUBIT_WEBSITE@,$AUBIT_WEBSITE,;t t
+s,@AUBIT_PUBLISHER@,$AUBIT_PUBLISHER,;t t
 s,@FULLNAME@,$FULLNAME,;t t
 s,@SHORTNAME@,$SHORTNAME,;t t
 s,@A4GL_SQLTYPE@,$A4GL_SQLTYPE,;t t
@@ -21819,6 +21817,8 @@ s,@CONFIGURE_COMMAND@,$CONFIGURE_COMMAND,;t t
 s,@GCC_VERSION_MAJOR@,$GCC_VERSION_MAJOR,;t t
 s,@GCC_VERSION_MINOR@,$GCC_VERSION_MINOR,;t t
 s,@GCC_MINGW@,$GCC_MINGW,;t t
+s,@IS_SOURCE@,$IS_SOURCE,;t t
+s,@IS_SOURCE_GTK@,$IS_SOURCE_GTK,;t t
 s,@CURSES_LIB_PATH@,$CURSES_LIB_PATH,;t t
 s,@CURSES_INC_PATH@,$CURSES_INC_PATH,;t t
 s,@HAVE_CURSES@,$HAVE_CURSES,;t t
@@ -22584,12 +22584,10 @@ cat<<X
 | the installation process at this point.                            |
 +--------------------------------------------------------------------+
 X
+if test "$enable_ac_debug" = "yes" ; then
 cat<<X
 +--------------------------------------------------------------------+
 |                        ***  NOTE   ***                             |
-X
-if test "$enable_ac_debug" = "yes" ; then
-cat<<X
 |
 | Aubit plug-ins to build:
 | $PLUGIN_YES
@@ -22620,6 +22618,7 @@ fi
 cat<<X
 
 Thank you for using Aubit 4gl compiler.
+                   $AUBIT_PUBLISHER
 
 X
 
