Small updates & fixes

diff --git a/aubit4glsrc/trunk/bin/aubitbuild.sh.in b/aubit4glsrc/trunk/bin/aubitbuild.sh.in
--- a/aubit4glsrc/trunk/bin/aubitbuild.sh.in
+++ b/aubit4glsrc/trunk/bin/aubitbuild.sh.in
@@ -25,7 +25,7 @@
 # +----------------------------------------------------------------------+
 
 #
-# $Id: aubitbuild.sh.in,v 1.37 2004-09-18 06:32:36 afalout Exp $
+# $Id: aubitbuild.sh.in,v 1.38 2004-09-22 14:39:03 afalout Exp $
 #
 
 #Use this script in corn for Aubit nightly automatic builds
@@ -186,6 +186,11 @@ FULLNAME='@FULLNAME@'
 AUBIT_VERSION=@AUBIT_VERSION@
 AUBIT_BUILD=@AUBIT_BUILD@
 
+#For comparing sizes:
+WGET_SIZE="wget --server-response --spider"
+WGET_LOG=wget.log
+HTTP_FILES_URL="http://aubit4gl.sf.net/files/"
+
 #####################
 #name of the computer we are on:
 HOSTNAME=`hostname`
@@ -295,15 +300,13 @@ function runexec {
 ############################
 
 
-        if [ "$VERBOSE" = "1" ]
-        then
+        if [ "$VERBOSE" = "1" ]; then
 			echo "Executing: $EXEC"
         fi
 
 		if [ "$LOGFILE" != "$MAINLOG" ]
         then
-	        if [ "$VERBOSE" = "1" ]
-	        then
+	        if [ "$VERBOSE" = "1" ]; then
 				echo "Log redirected to $LOGFILE"
 	        fi
         fi
@@ -327,6 +330,63 @@ function runexec {
 
 }
 
+############################
+function compare_size {
+############################
+
+UP_FILE=$1
+LOCAL_FILE=$2
+
+	HTTP_FILE="$HTTP_FILES_URL$UP_FILE"			
+	FILESIZE_SF=`$WGET_SIZE $HTTP_FILE > $WGET_LOG 2>&1;`
+	FILESIZE_SF=`cat $WGET_LOG | grep Content-Length: | sed -e 's/7 Content-Length://'`
+	rm -f $WGET_LOG
+	FILESIZE_LOCAL=`ls -al "$LOCAL_FILE" | awk '{print $5}';`
+	if test "$FILESIZE_LOCAL" != "$FILESIZE_SF"; then 
+		echo "ERROR: $LOCAL_FILE filesize of local and uploaded file are different"
+		echo "Filesize on SF is $FILESIZE_SF, local file is $FILESIZE_LOCAL"
+		echo "----------------------------------------------------"				
+		COMPARED_OK=0
+	fi
+}
+
+#########################
+function compare_files {
+#########################
+UP_FILE=$1
+DOWN_FILE=$2
+
+	if test "$USE_WGET" = "1"; then
+		EXEC="wget http://aubit4gl.sf.net/files/$UP_FILE"; runexec
+	else
+		EXEC="$AUTOSFSCPGET $SCPPATH/$UP_FILE"; runexec
+	fi
+	
+	if [ -f /tmp/$UP_FILE ]; then
+		diff /tmp/$UP_FILE $DOWN_FILE
+		RET=$?
+		if test $RET != "0"; then
+			#echo "Error: /tmp/$UP_FILE and $DOWN_FILE are different"
+			ls -al /tmp/$UP_FILE
+			ls -al $DOWN_FILE
+			if [ "$VERBOSE" = "1" ]; then
+				echo "Failed cmd was: $EXEC"
+			fi
+			echo "----------------------------------------------------"
+			COMPARED_OK=0
+			if test "$STOP_AFTER_DL_ERROR" = "1"; then 
+				exit 54
+			fi
+		fi
+	else
+		echo "Download of $UP_FILE failed"
+		if [ "$VERBOSE" = "1" ]; then
+			echo "Failed cmd was: $EXEC"
+		fi
+		echo "----------------------------------------------------"
+		COMPARED_OK=0
+	fi
+}
 
 ## ==================================================================
 ##                      Main
@@ -634,7 +694,8 @@ if test "$MAKE" = "1"; then
             echo " "
 
 			#Run all build tests in tools/test/build_tests/...
-			make test.build
+			#this is now invoked from cron script
+			#make test.build
 
         fi
 
@@ -979,52 +1040,15 @@ if test "$COMPARE" = "1"; then
 	COMPARED_OK=1
     cd /tmp
 
+	#source tarball
 	if test "$SOURCETARBASENAME" != ""; then
 		if test " -f /tmp/$SOURCETARBASENAME"; then
 			rm -f /tmp/$SOURCETARBASENAME
 	    fi
-		
-		if test "$COMPARE_SIZE" = "1"; then 
-			WGET_SIZE="wget --server-response --spider"
-			HTTP_FILE="http://aubit4gl.sf.net/files/$SOURCETARBASENAME"
-			WGET_LOG=xx.log
-			FILESIZE_SF=`$WGET_SIZE $HTTP_FILE > $WGET_LOG 2>&1;`
-			FILESIZE_SF=`cat $WGET_LOG | grep Content-Length: | sed -e 's/7 Content-Length://'`
-			rm -f $WGET_LOG
-			FILESIZE_LOCAL=`ls -al /tmp/$SOURCETARBASENAME | awk '{print $5}';`
-			if test "$FILESIZE_LOCAL" != "$FILESIZE_SF"; then 
-				echo "Filesize on SF is $FILESIZE_SF, local file is $FILESIZE_LOCAL"
-				echo "ERROR: $SOURCETARBASENAME filesize of local and uploaded file are different"
-				COMPARED_OK=0
-			fi
+		if test "$COMPARE_SIZE" = "1"; then
+			compare_size $SOURCETARBASENAME $SOURCETARNAME
 		else
-			if test "$USE_WGET" = "1"; then
-				EXEC="wget http://aubit4gl.sf.net/files/$SOURCETARBASENAME"; runexec
-			else
-				EXEC="$AUTOSFSCPGET $SCPPATH/$SOURCETARBASENAME"; runexec
-			fi
-	
-			if [ -f /tmp/$SOURCETARBASENAME ]; then
-				diff /tmp/$SOURCETARBASENAME $SOURCETARNAME
-				RET=$?
-				if test $RET != "0"
-				then
-					echo "Error: /tmp/$SOURCETARBASENAME and $SOURCETARNAME are different"
-					ls -al /tmp/$SOURCETARBASENAME
-					ls -al $SOURCETARNAME
-					echo "Failed cmd was: $EXEC"
-					echo "----------------------------------------------------"
-					COMPARED_OK=0
-					if test "$STOP_AFTER_DL_ERROR" = "1"; then 
-						exit 54
-					fi
-				fi
-			else
-				echo "Download of $SOURCETARBASENAME failed"
-				echo "Failed cmd was: $EXEC"
-				echo "----------------------------------------------------"
-				COMPARED_OK=0
-			fi
+			compare_files $SOURCETARBASENAME $SOURCETARNAME
 		fi
     fi
 
@@ -1037,12 +1061,13 @@ if test "$COMPARE" = "1"; then
 		if [ -f /tmp/$TARBALLBASENAME ]; then
 			diff /tmp/$TARBALLBASENAME $TARBALL
 			RET=$?
-			if test $RET != "0"
-			then
-		        echo "Error: /tmp/$TARBALLBASENAME and $TARBALL are different"
+			if test $RET != "0"; then
+		        #echo "Error: /tmp/$TARBALLBASENAME and $TARBALL are different"
 				ls -al /tmp/$TARBALLBASENAME
 				ls -al $TARBALL
-				echo "Failed cmd was: $EXEC"
+				if [ "$VERBOSE" = "1" ]; then
+					echo "Failed cmd was: $EXEC"
+				fi
 				echo "----------------------------------------------------"
 				COMPARED_OK=0
 				if test "$STOP_AFTER_DL_ERROR" = "1"; then 
@@ -1051,7 +1076,9 @@ if test "$COMPARE" = "1"; then
 		    fi
         else
             echo "Downlaod of $TARBALLBASENAME failed"
-			echo "Failed cmd was: $EXEC"
+			if [ "$VERBOSE" = "1" ]; then
+				echo "Failed cmd was: $EXEC"
+			fi
 			echo "----------------------------------------------------"
 			COMPARED_OK=0
         fi
@@ -1074,12 +1101,13 @@ if test "$COMPARE" = "1"; then
 		if test -f "/tmp/$WINSETUPEXE_BASENAME"; then
 			diff "/tmp/$WINSETUPEXE_BASENAME" "$WINSETUPEXE"
 			RET=$?
-			if test $RET != "0"
-			then
-		        echo "Error: /tmp/$WINSETUPEXE_BASENAME and $WINSETUPEXE are different"
+			if test $RET != "0"; then
+		        #echo "Error: /tmp/$WINSETUPEXE_BASENAME and $WINSETUPEXE are different"
 				ls -al "/tmp/$WINSETUPEXE_BASENAME"
 				ls -al "$WINSETUPEXE"
-				echo "Failed cmd was: $EXEC"
+				if [ "$VERBOSE" = "1" ]; then
+					echo "Failed cmd was: $EXEC"
+				fi
 				echo "----------------------------------------------------"
 				COMPARED_OK=0
 				if test "$STOP_AFTER_DL_ERROR" = "1"; then 
@@ -1092,7 +1120,9 @@ if test "$COMPARE" = "1"; then
 			fi
         else
 			echo "Download of $WINSETUPEXE_BASENAME failed"
-			echo "Failed cmd was: $EXEC"
+			if [ "$VERBOSE" = "1" ]; then
+				echo "Failed cmd was: $EXEC"
+			fi
 			echo "----------------------------------------------------"
 			COMPARED_OK=0
         fi
@@ -1107,12 +1137,13 @@ if test "$COMPARE" = "1"; then
 			if [ -f /tmp/$SOURCERPMBASENAME ]; then
 				diff /tmp/$SOURCERPMBASENAME $SOURCERPM
 				RET=$?
-				if test $RET != "0"
-				then
-			        echo "Error: /tmp/$SOURCERPMBASENAME and $SOURCERPM are different"
+				if test $RET != "0"; then
+			        #echo "Error: /tmp/$SOURCERPMBASENAME and $SOURCERPM are different"
 					ls -al /tmp/$SOURCERPMBASENAME
 					ls -al $SOURCERPM
-					echo "Failed cmd was: $EXEC"
+					if [ "$VERBOSE" = "1" ]; then
+						echo "Failed cmd was: $EXEC"
+					fi
 					echo "----------------------------------------------------"
 					COMPARED_OK=0
 					if test "$STOP_AFTER_DL_ERROR" = "1"; then 
@@ -1121,7 +1152,9 @@ if test "$COMPARE" = "1"; then
 			    fi
             else
                 echo "Download of $SOURCERPMBASENAME failed"
-				echo "Failed cmd was: $EXEC"
+				if [ "$VERBOSE" = "1" ]; then
+					echo "Failed cmd was: $EXEC"
+				fi
 				echo "----------------------------------------------------"
 				COMPARED_OK=0
             fi
@@ -1136,12 +1169,13 @@ if test "$COMPARE" = "1"; then
 			if [ -f /tmp/$BINRPMBASENAME ]; then
 				diff /tmp/$BINRPMBASENAME $BINRPM
 				RET=$?
-				if test $RET != "0"
-				then
-			        echo "Error: /tmp/$BINRPMBASENAME and $BINRPM are different"
+				if test $RET != "0"; then
+			        #echo "Error: /tmp/$BINRPMBASENAME and $BINRPM are different"
 					ls -al /tmp/$BINRPMBASENAME
 					ls -al $BINRPM
-					echo "Failed cmd was: $EXEC"
+					if [ "$VERBOSE" = "1" ]; then
+						echo "Failed cmd was: $EXEC"
+					fi
 					echo "----------------------------------------------------"
 					COMPARED_OK=0
 					if test "$STOP_AFTER_DL_ERROR" = "1"; then 
@@ -1150,7 +1184,9 @@ if test "$COMPARE" = "1"; then
 			    fi
             else
                 echo "Download of $BINRPMBASENAME failed"
-				echo "Failed cmd was: $EXEC"
+				if [ "$VERBOSE" = "1" ]; then
+					echo "Failed cmd was: $EXEC"
+				fi
 				echo "----------------------------------------------------"
 				COMPARED_OK=0
             fi
