*** empty log message ***

diff --git a/aubit4glsrc/trunk/bin/aubit b/aubit4glsrc/trunk/bin/aubit
--- a/aubit4glsrc/trunk/bin/aubit
+++ b/aubit4glsrc/trunk/bin/aubit
@@ -1,4 +1,3 @@
-
 #On CygWin, using /bin/sh will result in error since sh is NOT bash and 
 #does NOT understand functions!
 #Variables, like #!${SHELL:-/bin/bash} cant be used here
@@ -34,7 +33,6 @@ function show_help {
     echo ' --show-path'
     echo ' --ahelp'	
     echo
-    echo '<command> can be:'
 	echo ' 4glpc - main compiler script (scheduled to be obsoleted)'
     echo ' 4glc - 4gl to [C|Perl|EC|...]-code compiler'
 	echo ' fcompile - form file (.per) compiler'
@@ -51,6 +49,16 @@ function show_help {
 if [ $# -lt 1 ]; then
 	show_help
 	exit 0
+fi
+
+################################
+#Determine for which OS was this aubit-config compiled
+#TARGET=i686-pc-cygwin
+#TARGET_OS=cygwin
+TARGET_OS=`aubit-config TARGET_OS  2>/dev/null`
+if test "$TARGET_OS" = ""; then 
+	echo "ERROR: no TARGET_OS"
+	exit 3
 fi
 
 #FIXME: on CygWin, we must add "bash" in front of "4glpc" otherwise standard "sh" will be
@@ -71,7 +79,7 @@ CMD_LINE_TOOLS="4glc 4glpc aubit-config default_frm mcompile 4glc-strip aupscol 
 
 #If user invoked this from command line, via aubit script, he probably wants 
 #to run them in terminal, and not GUI mode?
-TUI_TOOLS="asql_g.4ae asql_i.4ae asql_p.4ae"
+TUI_TOOLS="asql_g.4ae asql_i.4ae asql_p.4ae asql_g asql_i asql_p"
 CMD_LINE_TOOLS="$CMD_LINE_TOOLS $TUI_TOOLS"
 
 FLAGS=$@
@@ -108,18 +116,27 @@ for FLAG in $FLAGS; do
 		FLAG_CNT=`(expr $FLAG_CNT + 1) 2>/dev/null`
 		
 		for CMD in $CMD_LINE_TOOLS; do
-			if test "$FLAG" = "$CMD"; then 
+			#The whole pint of this script is not to have to specify path
+			#BASENAME_FLAG=`basename $FLAG`
+			#if test "$BASENAME_FLAG" = "$CMD"; then
+			if test "$FLAG" = "$CMD"; then
 				IS_CMD_LINE_TOOL=1
-				#Only thing we have for sure is CONSOLE
-				if test "$GCC_MINGW" = "yes"; then
-					export A4GL_UI=HL_TUIN
-					#export A4GL_UI=HL_TUINs
-				else
-					export A4GL_UI=CONSOLE
-					#export A4GL_UI=TUI
-				fi
+				break
 			fi
 		done	
+		if test "$IS_CMD_LINE_TOOL" = "1"; then
+			#Only thing we have for sure is CONSOLE
+			if test "$TARGET_OS" = "mingw"; then 
+				USE_UI=HL_TUINs
+			else
+				#On UNIX and CygWin, we should allways have TUI
+				#USE_UI=CONSOLE
+				USE_UI=TUI
+			fi
+			#echo "Forcing A4GL_UI=$USE_UI (TARGET_OS=$TARGET_OS)"
+			#exit
+			export A4GL_UI=$USE_UI
+		fi
 
 	    EXEC="$EXEC $FLAG"
 		;;
@@ -146,7 +163,6 @@ fi
 #TARGET_OS=cygwin
 TARGET_OS=`aubit-config TARGET_OS  2>/dev/null`
 if test "$TARGET_OS" = "mingw"; then 
-	GCC_MINGW="yes"
 	case "$PATH" in
 		*cygdrive*)
 			#We are running under CygWin shell, that will do nasty things
@@ -169,7 +185,7 @@ fi
 	
 case "$AUBITDIR" in
 	*cygdrive*)
-		if test "$GCC_MINGW" = "yes"; then
+		if test "$TARGET_OS" = "mingw"; then
 			echo "WARNING: AUBITDIR contaned CygWin mapped path:"
 			echo "$AUBITDIR"
 			#convert Cygwin path mapping back to native
@@ -177,14 +193,14 @@ case "$AUBITDIR" in
 		fi
 		;;
 	*:*)
-		if test "$GCC_MINGW" != "yes"; then
+		if test "$TARGET_OS" != "mingw"; then		
 			echo "WARNING: AUBITDIR contans ':' but not using MinGW"
 			echo "$AUBITDIR"
 		fi
 		;;
 	*)
 		#no cygdrive and no column (:)
-		if test "$GCC_MINGW" = "yes"; then
+		if test "$TARGET_OS" = "mingw"; then
 			echo "WARNING: AUBITDIR does NOT contan ':'"
 			echo "$AUBITDIR"
 		fi
@@ -273,7 +289,7 @@ else
 	DBPATH=$AUBITDIR/bin$A4GL_PATH_SEP$DBPATH
 fi
 
-if test "$GCC_MINGW" = "xxxyes"; then
+if test "$TARGET_OS" = "xxxmingw"; then
 	NEW_PATH=`echo $PATH | sed -e 's/;/:/'g`
 	if test "$PATH" != "$NEW_PATH"; then 
 		echo "WARNING: PATH contained ';'"
@@ -305,8 +321,6 @@ if test "$SHOW" = "1" -o "$VERBOSE" = "1"; then
     echo "PATH=$PATH"
 	echo
 	echo "TARGET_OS=TARGET_OS"
-	echo
-	echo "GCC_MINGW=$GCC_MINGW"
 	echo
     echo "DBPATH=$DBPATH"
 	echo
