Updates

diff --git a/aubit4glsrc/trunk/bin/aubitbuild.sh.in b/aubit4glsrc/trunk/bin/aubitbuild.sh.in
--- a/aubit4glsrc/trunk/bin/aubitbuild.sh.in
+++ b/aubit4glsrc/trunk/bin/aubitbuild.sh.in
@@ -25,7 +25,7 @@
 # +----------------------------------------------------------------------+
 
 #
-# $Id: aubitbuild.sh.in,v 1.36 2004-09-13 16:29:48 afalout Exp $
+# $Id: aubitbuild.sh.in,v 1.37 2004-09-18 06:32:36 afalout Exp $
 #
 
 #Use this script in corn for Aubit nightly automatic builds
@@ -130,8 +130,18 @@ export PATH=/bin/custom:$PATH
 #Do we want to stop on errors, or continue:
 STOPONERROR=1
 
+#####################
 #Do we stop after first upload/download error
 STOP_AFTER_DL_ERROR=0
+
+#####################
+#Do we just compare size of uploaded and local filess, or do we actually 
+#download uploaded files and compare them 
+COMPARE_SIZE=1
+
+#####################
+#Do we use wget to download, or wget
+USE_WGET=1
 
 #####################
 #Do we want to increase build number:
@@ -966,30 +976,56 @@ fi
 
 if test "$COMPARE" = "1"; then
 	####################### download and compare #################
-
+	COMPARED_OK=1
     cd /tmp
 
 	if test "$SOURCETARBASENAME" != ""; then
 		if test " -f /tmp/$SOURCETARBASENAME"; then
 			rm -f /tmp/$SOURCETARBASENAME
 	    fi
-		EXEC="$AUTOSFSCPGET $SCPPATH/$SOURCETARBASENAME"; runexec
-
-        if [ -f /tmp/$SOURCETARBASENAME ]; then
-			diff /tmp/$SOURCETARBASENAME $SOURCETARNAME
-			RET=$?
-			if test $RET != "0"
-			then
-		        echo "Error: /tmp/$SOURCETARBASENAME and $SOURCETARNAME are different"
-				ls -al /tmp/$SOURCETARBASENAME
-				ls -al $SOURCETARNAME
-				if test "$STOP_AFTER_DL_ERROR" = "1"; then 
-					exit 54
+		
+		if test "$COMPARE_SIZE" = "1"; then 
+			WGET_SIZE="wget --server-response --spider"
+			HTTP_FILE="http://aubit4gl.sf.net/files/$SOURCETARBASENAME"
+			WGET_LOG=xx.log
+			FILESIZE_SF=`$WGET_SIZE $HTTP_FILE > $WGET_LOG 2>&1;`
+			FILESIZE_SF=`cat $WGET_LOG | grep Content-Length: | sed -e 's/7 Content-Length://'`
+			rm -f $WGET_LOG
+			FILESIZE_LOCAL=`ls -al /tmp/$SOURCETARBASENAME | awk '{print $5}';`
+			if test "$FILESIZE_LOCAL" != "$FILESIZE_SF"; then 
+				echo "Filesize on SF is $FILESIZE_SF, local file is $FILESIZE_LOCAL"
+				echo "ERROR: $SOURCETARBASENAME filesize of local and uploaded file are different"
+				COMPARED_OK=0
+			fi
+		else
+			if test "$USE_WGET" = "1"; then
+				EXEC="wget http://aubit4gl.sf.net/files/$SOURCETARBASENAME"; runexec
+			else
+				EXEC="$AUTOSFSCPGET $SCPPATH/$SOURCETARBASENAME"; runexec
+			fi
+	
+			if [ -f /tmp/$SOURCETARBASENAME ]; then
+				diff /tmp/$SOURCETARBASENAME $SOURCETARNAME
+				RET=$?
+				if test $RET != "0"
+				then
+					echo "Error: /tmp/$SOURCETARBASENAME and $SOURCETARNAME are different"
+					ls -al /tmp/$SOURCETARBASENAME
+					ls -al $SOURCETARNAME
+					echo "Failed cmd was: $EXEC"
+					echo "----------------------------------------------------"
+					COMPARED_OK=0
+					if test "$STOP_AFTER_DL_ERROR" = "1"; then 
+						exit 54
+					fi
 				fi
-		    fi
-        else
-            echo "Download of $SOURCETARBASENAME failed"
-        fi
+			else
+				echo "Download of $SOURCETARBASENAME failed"
+				echo "Failed cmd was: $EXEC"
+				echo "----------------------------------------------------"
+				COMPARED_OK=0
+			fi
+		fi
     fi
 
 	if test "$TARBALLBASENAME" != "" -a "$TARBALL" != "NONE"; then
@@ -1006,12 +1042,18 @@ if test "$COMPARE" = "1"; then
 		        echo "Error: /tmp/$TARBALLBASENAME and $TARBALL are different"
 				ls -al /tmp/$TARBALLBASENAME
 				ls -al $TARBALL
+				echo "Failed cmd was: $EXEC"
+				echo "----------------------------------------------------"
+				COMPARED_OK=0
 				if test "$STOP_AFTER_DL_ERROR" = "1"; then 
 					exit 54
 				fi
 		    fi
         else
             echo "Downlaod of $TARBALLBASENAME failed"
+			echo "Failed cmd was: $EXEC"
+			echo "----------------------------------------------------"
+			COMPARED_OK=0
         fi
     fi
 
@@ -1037,6 +1079,9 @@ if test "$COMPARE" = "1"; then
 		        echo "Error: /tmp/$WINSETUPEXE_BASENAME and $WINSETUPEXE are different"
 				ls -al "/tmp/$WINSETUPEXE_BASENAME"
 				ls -al "$WINSETUPEXE"
+				echo "Failed cmd was: $EXEC"
+				echo "----------------------------------------------------"
+				COMPARED_OK=0
 				if test "$STOP_AFTER_DL_ERROR" = "1"; then 
 					exit 54
 				fi
@@ -1047,6 +1092,9 @@ if test "$COMPARE" = "1"; then
 			fi
         else
 			echo "Download of $WINSETUPEXE_BASENAME failed"
+			echo "Failed cmd was: $EXEC"
+			echo "----------------------------------------------------"
+			COMPARED_OK=0
         fi
     fi
 
@@ -1064,12 +1112,18 @@ if test "$COMPARE" = "1"; then
 			        echo "Error: /tmp/$SOURCERPMBASENAME and $SOURCERPM are different"
 					ls -al /tmp/$SOURCERPMBASENAME
 					ls -al $SOURCERPM
+					echo "Failed cmd was: $EXEC"
+					echo "----------------------------------------------------"
+					COMPARED_OK=0
 					if test "$STOP_AFTER_DL_ERROR" = "1"; then 
 						exit 54
 					fi
 			    fi
             else
                 echo "Download of $SOURCERPMBASENAME failed"
+				echo "Failed cmd was: $EXEC"
+				echo "----------------------------------------------------"
+				COMPARED_OK=0
             fi
         fi
 
@@ -1087,17 +1141,24 @@ if test "$COMPARE" = "1"; then
 			        echo "Error: /tmp/$BINRPMBASENAME and $BINRPM are different"
 					ls -al /tmp/$BINRPMBASENAME
 					ls -al $BINRPM
+					echo "Failed cmd was: $EXEC"
+					echo "----------------------------------------------------"
+					COMPARED_OK=0
 					if test "$STOP_AFTER_DL_ERROR" = "1"; then 
 						exit 54
 					fi
 			    fi
             else
                 echo "Download of $BINRPMBASENAME failed"
+				echo "Failed cmd was: $EXEC"
+				echo "----------------------------------------------------"
+				COMPARED_OK=0
             fi
 		fi
     fi
-
-	COMPARED_OK=1
+	if test "$COMPARED_OK" != "1"; then
+		echo "ERROR: one or more errors comparing created and downloaded files"
+	fi
     cd -
 fi
 
diff --git a/aubit4glsrc/trunk/bin/esql_wrap b/aubit4glsrc/trunk/bin/esql_wrap
--- a/aubit4glsrc/trunk/bin/esql_wrap
+++ b/aubit4glsrc/trunk/bin/esql_wrap
@@ -81,8 +81,7 @@ do
 
 	d=`dirname $a`
 
-	if [ "$d" != "" -a "$d" != "." ]
-	then
+	if [ "$d" != "" -a "$d" != "." ]; then
 		c=$d/`basename "$a" `
 		b=$d/`basename "$c" ".$ESQL_EXT"`
 	else
@@ -91,15 +90,20 @@ do
 		b2=./`basename "$c" ".$ESQL_EXT"`
 	fi
 
-	if [ $b.$ESQL_EXT = $a -o $b2.$ESQL_EXT = $a ]
-	then
+	if [ $b.$ESQL_EXT = $a -o $b2.$ESQL_EXT = $a ]; then
 		srcs="$srcs $a"
 		shift
 		continue
 	fi
+	case $a in
+		*.c)
+			srcs="$srcs $a"
+			shift
+			continue
+		;;
+	esac
 
-	if [ $a = "-o" ]
-	then
+	if [ $a = "-o" ]; then
 		shift
 		output="-o $1"
 		case $1 in
@@ -115,33 +119,47 @@ do
 	fi
 
 	other_args="$other_args $a"
-
-
 	shift
 done
 
 if test "$SH_DEBUG" = "1"; then
 	echo "SOURCES : " $srcs
 fi
+if test "$COMPILE_OBJ" = "1" -a "$srcs" = ""; then
+	echo "ERROR: no source files and no linking?"
+	exit 1
+fi
 
 for a in $srcs
 do
-	if test "$COMSPEC" = ""; then 
-		ESQL_RUN="esql -e $a"
-	else
-		ESQL_RUN="esql -thread -e $a"     #-C INFORMIX_SE	
-	fi
-
-    echo $ESQL_RUN
-    eval $ESQL_RUN
-
-    RET=$?
-    if test "$RET" != "0"; then
-        exit $RET
-    fi
+	case $a in
+		*.ec)
+			if test "$COMSPEC" = ""; then 
+				ESQL_RUN="esql -e $a"
+			else
+				ESQL_RUN="esql -thread -e $a"     #-C INFORMIX_SE	
+			fi
+			echo $ESQL_RUN
+			eval $ESQL_RUN
+			RET=$?
+			if test "$RET" != "0"; then
+				exit $RET
+			fi
+		;;
+	esac
+	
     out=`basename $a ".$ESQL_EXT"`
-    cfiles="$cfiles $out.c"
-    GCC_COMPILE="gcc -c $out.c $other_args -I\"$INFORMIXDIR/incl/esql\" \
+	case $a in
+		*.ec)
+			cfiles="$cfiles $out.c"
+			outfile="$out.c"
+		;;
+		*)
+			outfile="$out"		
+		;;
+	esac
+	
+    GCC_COMPILE="gcc -c $outfile $other_args -I\"$INFORMIXDIR/incl/esql\" \
 		-I\"$INFORMIXDIR/CSDK/incl/esql\" -I$AUBITDIR/incl"
 
 	if test "$OUTPUT_IS_OBJECT" = "1"; then
@@ -195,7 +213,7 @@ if test "$COMSPEC" != "" ; then
 		\"$INFORMIXDIR/$LIB/isqlt09a.dll\" \"$INFORMIXDIR/$LIB/igl4n304.dll\" \
 		\"$INFORMIXDIR/$LIB/iglxn304.dll\" \"$INFORMIXDIR/$LIB/igo4n304.dll\" "
 else
-	GCC_INFX="-mms-bitfields $IFX_LIBS -L$INFORMIXDIR/lib/esql -L$INFORMIXDIR/lib"
+	GCC_INFX="$IFX_LIBS -L$INFORMIXDIR/lib/esql -L$INFORMIXDIR/lib"
 fi
 
 #DO NOT link in -lESQL_INFORMIX - it is dlopen()ed
@@ -205,6 +223,11 @@ GCC_RUN="gcc $ofiles $other_args $GCC_INFX $LFLAGS $output"
 echo $GCC_RUN
 eval $GCC_RUN
 RET=$?
+if test "$RET" != "0"; then 
+	if test -f $LOGFILE; then 
+		cat $LOGFILE
+	fi
+fi
 exit $RET
 
 
