CigWin GTK related

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -9426,19 +9426,23 @@ echo $ECHO_N "checking GCC version... $ECHO_C" >&6
 	#$ gcc --version
 	#gcc (GCC) 3.2 20020818 (prerelease)
 
-	#set `gcc --version |sed -e 's/^gcc \(GCC\) //' -e 's/ \(prerelease\)//' -e 's/\./ /g'`
-	set `gcc --version | head -1 | sed -e 's/^gcc (GCC) //' -e 's/ (prerelease)//' -e 's/\./ /g'`
-    #set `bison --version|head -1|sed -e 's/^GNU Bison version //' -e 's/^bison (GNU Bison) //' -e 's/\./ /g'`
-	if test "$1" != ""; then
-		#if test "$1" = "3" -a "$2" -lt "50"; then
-	    #    AC_MSG_WARN(You will need GNU make version 3.50 or later (found $1.$2.$3).)
-        #else
-		    echo "$as_me:$LINENO: result: $1.$2.$3" >&5
+	TMP_TMP=`gcc --version | head -1 | sed -e 's/^gcc (GCC) //' -e 's/ (prerelease)//' -e 's/\./ /g'`
+	if test "$TMP_TMP" != ""; then
+		set `echo $TMP_TMP`
+		if test "$1" != ""; then
+			#if test "$1" = "3" -a "$2" -lt "50"; then
+		    #    AC_MSG_WARN(You will need GNU make version 3.50 or later (found $1.$2.$3).)
+	        #else
+			    echo "$as_me:$LINENO: result: $1.$2.$3" >&5
 echo "${ECHO_T}$1.$2.$3" >&6
-            GCC_VERSION_MAJOR=$1
-			GCC_VERSION_MINOR=$2
-        #fi
-	else
+	            GCC_VERSION_MAJOR=$1
+				GCC_VERSION_MINOR=$2
+	        #fi
+		else
+			{ echo "$as_me:$LINENO: WARNING: Cannot read GCC version." >&5
+echo "$as_me: WARNING: Cannot read GCC version." >&2;}
+	    fi
+    else
 		{ echo "$as_me:$LINENO: WARNING: Cannot read GCC version." >&5
 echo "$as_me: WARNING: Cannot read GCC version." >&2;}
     fi
@@ -12938,10 +12942,8 @@ fi
 #endif
 
 
-
-
 		#check if we have all we need to make GTK GUI
-		if test "$ac_cv_lib_gtk_main" = yes && test "$ac_cv_lib_glib_main" = yes && test "$ac_cv_lib_gdk_main" = yes; then
+		if test "$ac_cv_lib_gtk_main" = yes && test "$ac_cv_lib_glib_main" = yes && test "$ac_cv_lib_gdk_main" = yes || test "$PKG_CONFIG" != "no"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_GTK 1
@@ -12968,7 +12970,7 @@ _ACEOF
 					else
 						if test "$PKG_CONFIG" != "no"; then
 		                    #this will get assigned in makefile iteself, but
-                            #plg-config needs package name as parameter, and on Cygwin,
+                            #pkg-config needs package name as parameter, and on Cygwin,
                             #this iclude version names, like this:
 							#gtk+-1.3-win32-production
 							#gdk-1.3-win32-production
@@ -12978,9 +12980,9 @@ _ACEOF
 							#gthread-2.0
                             # - so we need to extract this names first:
 
-                            GTK_NAME=`$PKG_CONFIG --list-all | grep gtk | awk '{print $1}'`
-							GDK_NAME=`$PKG_CONFIG --list-all | grep gdk | awk '{print $1}'`
-							GLIB_NAME=`$PKG_CONFIG --list-all | grep glib | awk '{print $1}'`
+                            GTK_NAME=`$PKG_CONFIG --list-all | grep gtk | head -1 | awk '{print $1}'`
+							GDK_NAME=`$PKG_CONFIG --list-all | grep gdk | head -1 | awk '{print $1}'`
+							GLIB_NAME=`$PKG_CONFIG --list-all | grep glib |  head -1 | awk '{print $1}'`
 
 							#pkg-config options:
 							# --libs
@@ -13051,6 +13053,10 @@ fi;
 
 CUSTOM_WITHVAL=0
 
+echo "$as_me:$LINENO: checking GTK+ support" >&5
+echo $ECHO_N "checking GTK+ support... $ECHO_C" >&6
+echo "$as_me:$LINENO: result: $GTKBUILD ($GTK_NAME $GDK_NAME $GLIB_NAME)" >&5
+echo "${ECHO_T}$GTKBUILD ($GTK_NAME $GDK_NAME $GLIB_NAME)" >&6
 
 #Fixme: we should test for GTK+ versions
 
@@ -18502,7 +18508,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 18505 "configure"' > conftest.$ac_ext
+  echo '#line 18511 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18970,7 +18976,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18973 "configure"
+#line 18979 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19068,7 +19074,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19071 "configure"
+#line 19077 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
