Build related updates and fixes

diff --git a/aubit4glsrc/trunk/configure.in b/aubit4glsrc/trunk/configure.in
--- a/aubit4glsrc/trunk/configure.in
+++ b/aubit4glsrc/trunk/configure.in
@@ -22,7 +22,7 @@ dnl # | If you did not, or have any questions about Aubit licensing, please  |
 dnl # | contact afalout@ihug.co.nz                                           |
 dnl # +----------------------------------------------------------------------+
 dnl #
-dnl # $Id: configure.in,v 1.328 2006-10-14 16:18:30 mikeaubury Exp $
+dnl # $Id: configure.in,v 1.329 2006-10-21 13:02:36 afalout Exp $
 dnl #
 dnl #TODO: check that WARN_LD_LIBRARY_PATH is set ONLY if user specified custom withval
 dnl #and then check that it is no already in LD_LIBRARY_PATH or ldconfig file. Only
@@ -47,7 +47,7 @@ export LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH
 
 #We need autoconf at least version 2.50
 AC_PREREQ(2.50)
-AC_REVISION($Id: configure.in,v 1.328 2006-10-14 16:18:30 mikeaubury Exp $)
+AC_REVISION($Id: configure.in,v 1.329 2006-10-21 13:02:36 afalout Exp $)
 
 #Need to be here too, to be used in AC_INIT call:
 #FIXME - DOES NOT WORK HERE - works only after AC_INIT!!!!
@@ -297,7 +297,7 @@ fi
 AC_CONFIG_SRCDIR([bin/aubit])
 
 if test "$AUBIT_SOURCE" = "1" ; then
-	#Location of global header to receive "#define xxxxx y" replacements:
+	#Location of global header to receive "#define ABCD y" replacements:
 	#AC_CONFIG_HEADER([incl/a4gl_incl_config.h])
 	#When file name contains path and therefore / , we get strange errors
     #from automake if path is specified as ([path/file.ext]). Autoconf
@@ -603,6 +603,7 @@ AC_SUBST(LDFLAGS)
 AC_SUBST(LDFLAGS_SHARED)
 #AC_SUBST(YACC)
 AC_SUBST(BISON)
+AC_SUBST(BISON_EXE)
 AC_SUBST(LEX)
 AC_SUBST(LCLINTEXE)
 AC_SUBST(EXPECT)
@@ -2116,7 +2117,13 @@ fi
 		fi
     fi
 
-
+	if test "$prefix" = "$aubitdir"; then
+		echo "ERROR: cannot install Aubit to the same location where you are running 'configure' from"
+		exit 3
+	fi
+	
+	
+	
 #INST_BASE=$prefix/$SHORTNAME
 INST_BASE=$prefix
 #AC_MSG_RESULT(INST_BASE set to $INST_BASE)
@@ -2304,8 +2311,9 @@ fi
 ## ==================================================================
 
 AMAKE_SH="amake genmake prepmake"
-ALL_SH="aubit ecpg_wrap $AMAKE_SH"
-#runner_fgl_wrapper"
+ALL_SH="aubit ecpg_wrap $AMAKE_SH runner_fgl_wrapper"
+#compilers/pcode/runner_fgl_wrapper is copied to bin by pcode makefile
+
 #obsolete: ecpg_wrap esql_wrap
 #ALL_SH="4glpc $AMAKE_SH"
 #abug.sh
@@ -2995,7 +3003,10 @@ if test "$AUBIT_SOURCE" = "1" ; then
 				#same) "by hand" before ./configure. A better fix is to change
 				#the Makefile (replace "bison" with "LANG=C bison" or something)
 
-				#BISON="LANG=C LC_ALL=C; nice -n -20 $BISON -y"
+				#Store just the executable name for cases where we need it
+				#without default flags:
+				BISON_EXE="$BISON"
+				#BISON="LANG=C LC_ALL=C; nice -n -20 $BISON -y"				
 				BISON="LANG=C LC_ALL=C $BISON -y"
 			fi
 		else
@@ -9284,11 +9295,12 @@ PLUGIN_NO_LINKABLE=
 	if test "$IFMX_ESQLC" != "no" ; then
 		PLUGIN_YES="$PLUGIN_YES SQL_esql ESQL_INFORMIX"
 		if test "$enable_minimal" != "yes"; then
-			COMP_EXE="$COMP_EXE aupscol asql_i$A4GL_EXE_EXT runforms$A4GL_EXE_EXT"
-			#aupscol and sqleditor currently compiles only with Informix ESQL/C
+			COMP_EXE="$COMP_EXE aupscol adbload2 asql_i$A4GL_EXE_EXT runforms$A4GL_EXE_EXT"
+			#adbload2, aupscol and sqleditor currently compiles only with Informix ESQL/C
 		fi
 	else
-        PLUGIN_NO="$PLUGIN_NO SQL_esql ESQL_INFORMIX sqleditor$A4GL_EXE_EXT aupscol asql_i$A4GL_EXE_EXT"
+        PLUGIN_NO="$PLUGIN_NO SQL_esql ESQL_INFORMIX sqleditor$A4GL_EXE_EXT aupscol adbload2 asql_i$A4GL_EXE_EXT"
+		EXE_NO="$COMP_EXE aupscol adbload2 asql_i$A4GL_EXE_EXT runforms$A4GL_EXE_EXT"		
 		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.ifx.esql"
 	fi
 
@@ -9652,7 +9664,7 @@ PLUGIN_NO_LINKABLE=
 if test "$enable_minimal" != "yes"; then
 	#Need RPClib:
 	PCODE_EXE_RPC="c2pcode checker runner"
-	PCODE_EXE_NATIVE="c2pcode_fgl checker_fgl runner_fgl"
+	PCODE_EXE_NATIVE="c2pcode_fgl checker_fgl runner_fgl link_fgl"
 fi
 
 #FIXME: can't make pcode without Bison - IS THIS STILL TRUE?
@@ -10210,7 +10222,7 @@ cat<<X
 | CONFIGURE_COMMAND="$CONFIGURE_COMMAND"
 |                                                                    |
 | CONFIGURE_VERSION:                                                 |
-| $Id: configure.in,v 1.328 2006-10-14 16:18:30 mikeaubury Exp $
+| $Id: configure.in,v 1.329 2006-10-21 13:02:36 afalout Exp $
 |                                                                    |
 +--------------------------------------------------------------------+
 X
diff --git a/aubit4glsrc/trunk/incl/Makefile-install.mki b/aubit4glsrc/trunk/incl/Makefile-install.mki
--- a/aubit4glsrc/trunk/incl/Makefile-install.mki
+++ b/aubit4glsrc/trunk/incl/Makefile-install.mki
@@ -1,3 +1,4 @@
+# +----------------------------------------------------------------------+
 # | Aubit 4gl Language Compiler Version $.0   binary install make include|
 # +----------------------------------------------------------------------+
 # | Copyright (c) 2000-5 Aubit Development Team (See Credits file)       |
@@ -22,7 +23,7 @@
 # | contact afalout@ihug.co.nz                                           |
 # +----------------------------------------------------------------------+
 #
-# $Id: Makefile-install.mki,v 1.109 2006-10-14 08:25:35 afalout Exp $
+# $Id: Makefile-install.mki,v 1.110 2006-10-21 13:02:49 afalout Exp $
 #
 
 #This file is included from both source distribution root make file and
@@ -36,6 +37,10 @@
 #	${INSTALL} -m 644    ${FILE1.42f} ${D4GL_D4GL}
 
 #<block for binary install Makefile ======================================>
+
+#Cant declare PHONY here???
+#.PHONY: install.links install.bin.links install.lib.links \
+#	deinstall.links: deinstall.bin.links deinstall.libs.links
 
 ## ==================================================================
 ##                    install targets
@@ -51,16 +56,16 @@ else
 	${CP} ${INFILE} /tmp/aubitrc.tmp
 endif
 ifeq "${AUBITRCFILEEXISTS}" ""
-	${MKPATH} ${AUBITETC}
-#FIXME: following test will fail if performed on the same run when directory is created,
-#since make will evaluate it BEFORE mkdir is executed:
-ifeq "$(shell  if test -w ${AUBITETC} ; then echo 1; fi)" "1"
-	mv /tmp/aubitrc.tmp ${AUBITETC}/aubitrc
-	chmod a+r ${AUBITETC}/aubitrc
-	@echo "Configuration files installed to ${AUBITETC}/aubitrc"
-else 
-	@echo "======== WARNING: ${AUBITETC} is not writable. ==========="
-endif
+	@if ! test -d ${AUBITETC} ; then ${MKPATH} ${AUBITETC}; fi
+#THIS MUST BE A PURE SHELL - not a $(shell ...) as make variables are evaluated
+#BEFORE any make target commands are executed!
+	@if test -w ${AUBITETC} ; then \
+		mv /tmp/aubitrc.tmp ${AUBITETC}/aubitrc; \
+		chmod a+r ${AUBITETC}/aubitrc; \
+		echo "Configuration files installed to ${AUBITETC}/aubitrc"; \
+	else \
+		echo "======== NOTE: ${AUBITETC} is not writable. ==========="; \
+	fi
 else
 	@echo " "
 	@echo "WARNING: Configuration file aubitrc exists in ${AUBITETC}/aubitrc"
@@ -84,28 +89,89 @@ install.amake.files:
 	${CP} ${AMAKE_TOINCL} $(INCL_DEST)
 
 install.aubit-config.link: install.bin.install.link.dir
-#   -w file True if file exists and is writable.
-ifeq "$(shell  if test -w ${BIN_INSTALL_LINK} ; then echo 1; fi)" "1"
-	${LN_S} $(INSTALL_DIR)/bin/aubit-config ${BIN_INSTALL_LINK}/aubit-config
-	${LN_S} $(INSTALL_DIR)/bin/amake ${BIN_INSTALL_LINK}/amake
-else
-	@echo "WARNING: ${BIN_INSTALL_LINK} is not writable."
-endif
+	@if ! test -d ${BIN_INSTALL_LINK}; then ${MKPATH} ${BIN_INSTALL_LINK}; fi
+	@if test -w ${BIN_INSTALL_LINK} ; then \
+		${LN_S} $(INSTALL_DIR)/bin/aubit-config ${BIN_INSTALL_LINK}/aubit-config; \
+		${LN_S} $(INSTALL_DIR)/bin/amake ${BIN_INSTALL_LINK}/amake; \
+		echo "Links from $(INSTALL_DIR)/bin to ${BIN_INSTALL_LINK} for aubit-config and amake installed"; \
+	else \
+		echo " "; \
+		echo "+---------------------------------------------------------------------------"; \
+		echo "| NOTE: ${BIN_INSTALL_LINK} is not writable-cant install aubit-config link"; \
+		echo "+---------------------------------------------------------------------------"; \
+		${MKPATH} ${HOME}/bin; \
+		if test -w ${HOME}/bin ; then \
+			${LN_S} $(INSTALL_DIR)/bin/aubit-config ${HOME}/bin/aubit-config; \
+			${LN_S} $(INSTALL_DIR)/bin/amake ${HOME}/bin/amake; \
+			echo "Links from $(INSTALL_DIR)/bin to ${HOME}/bin/ for aubit-config and amake installed"; \
+		else \
+			echo " "; \
+			echo "+---------------------------------------------------------------------------"; \
+			echo "| WARNING: ${HOME}/bin is not writable-cant install aubit-config link"; \
+			echo "+---------------------------------------------------------------------------"; \
+		fi \
+	fi
 
 install.bin.install.link.dir:
-	${MKPATH} ${BIN_INSTALL_LINK}
+	@if ! test -d ${BIN_INSTALL_LINK}; then ${MKPATH} ${BIN_INSTALL_LINK}; fi
+	@if ! test -d ${HOME}/bin; then ${MKPATH} ${HOME}/bin; fi
 
+
+#Install all links
+install.links: install.bin.links install.libs.links
+	@echo "All links installed"
+	
+#De-install all links
+deinstall.links: deinstall.bin.links deinstall.libs.links
+	@echo "All links de-installed"
+	
 #######################################
 #Create links for bin programs to location of Aubit bynary installation:
-install.links: deinstall.bin.links install.aubit-config.link install.bin.install.link.dir
-#   -w file True if file exists and is writable.
-ifeq "$(shell  if test -w ${BIN_INSTALL_LINK} ; then echo 1; fi)" "1"
-	${LN_S} $(INSTALL_DIR)/bin/aubit ${BIN_INSTALL_LINK}/aubit
-	@echo "Links to Aubit programs installed to ${BIN_INSTALL_LINK}/ "
-else
-	@echo "WARNING: ${BIN_INSTALL_LINK} is not writable - won't install 'aubit' there"
-endif
+install.bin.links: deinstall.bin.links install.aubit-config.link install.bin.install.link.dir
+	@if ! test -d ${BIN_INSTALL_LINK}; then ${MKPATH} ${BIN_INSTALL_LINK}; fi
+	@if test -w ${BIN_INSTALL_LINK} ; then \
+		${LN_S} $(INSTALL_DIR)/bin/aubit ${BIN_INSTALL_LINK}/aubit; \
+		echo "Links from $(INSTALL_DIR)/bin to ${BIN_INSTALL_LINK}/ for 'aubit' installed"; \
+	else \
+		echo " "; \
+		echo "+---------------------------------------------------------------------------"; \
+		echo "| NOTE: ${BIN_INSTALL_LINK} is not writable - won't install 'aubit' link there"; \
+		echo "+---------------------------------------------------------------------------"; \
+		if ! test -d ${HOME}/bin ; then ${MKPATH} ${HOME}/bin; fi; \
+		if test -w ${HOME}/bin ; then \
+			${LN_S} $(INSTALL_DIR)/bin/aubit ${HOME}/bin/aubit; \
+			echo "Links from $(INSTALL_DIR)/bin to ${HOME}/bin/ for 'aubit' installed"; \
+		else \
+			echo " "; \
+			echo "+---------------------------------------------------------------------------"; \
+			echo "| WARNING: ${HOME}/bin is not writable - won't install 'aubit' link there"; \
+			echo "+---------------------------------------------------------------------------"; \
+		fi; \
+	fi
 
+#######################################
+install.libs.links: deinstall.libs.links
+#Link libaubit4gl with version string to plain libaubit4gl:
+	${LN_S_LIB} $(INSTALL_DIR)/lib/libaubit4gl-${A4GL_VERSION_STRING}${SO_EXT} $(INSTALL_DIR)/lib/libaubit4gl${SO_EXT}
+	@if ! test -d ${LIB_INSTALL_LINK}; then ${MKPATH} ${LIB_INSTALL_LINK}; fi
+	@if test -w ${LIB_INSTALL_LINK} ; then \
+		${LN_S_LIB} $(INSTALL_DIR)/lib/libaubit4gl${SO_EXT} ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}; \
+		echo "Links from $(INSTALL_DIR)/lib to ${LIB_INSTALL_LINK}/ for libaubit4gl installed"; \
+	else \
+		echo " "; \
+		echo "+---------------------------------------------------------------------------"; \
+		echo "| NOTE: ${LIB_INSTALL_LINK} is not writable - won't create Aubit libraries links there"; \
+		echo "+---------------------------------------------------------------------------"; \
+	fi
+
+
+
+#Note: there are not alternatives here - there is no location that is by default writable to 
+#to a regular user, that is by default included in LD_LIBRARY_PATH or ldconfig paths.
+#Therefore, user will need to add $(INSTALL_DIR)/lib to his LD_LIBRARY_PATH himself
+#manually (hopefully to ${HOME}/.profile) as no other options are avilable to regular user 
+#appart from asking a sys admin. Or using 'abit' wrapper script.
+	
 
 #This will work only on Linux, and Aubit loads from $AUBITDIR.lib anyway:
 #But NOT libs that are linked and not dlopen()-ed (like libESQL_ and file...)
@@ -113,6 +179,24 @@ endif
 #Can't put targets in MAkefile-common - I should create one include makefile 
 #for targets needed by both binary and source distros 
 install.libs.conf:
+	@if test -w /etc/ld.so.conf.d ; then \
+		echo "$(INSTALL_DIR)/lib" > /etc/ld.so.conf.d/aubit4gl.conf; \
+	fi
+ifneq "${LDCONFIG}" "no"	
+	@if test -w /etc/ ; then \
+		if "${LDCONFIG}" ; then \
+			echo "Refreshed ldconfig cache." ;\
+		else \
+			echo "Unable to refresh ldconfig cache." ;\
+		fi; \
+	fi
+else
+	@echo "ldconfig not found on your system"
+endif
+
+
+ifeq "1" "2"
+#OBSOLETE - The above should have same effect and is simpler
 ifneq "${LDCONFIG}" "no"
 ifeq "${GREP_LD_SO_CONF}" ""
 	@if echo "$(INSTALL_DIR)/lib" >> ${LD_SO_CONF} ; \
@@ -132,7 +216,11 @@ endif
 else
 	@echo "ldconfig not found on your system"
 endif
+endif
 
+## ==================================================================
+##                    Windows registry
+## ==================================================================
 
 #Add basic registry keys, so native windows executable can find aubitrc
 install.registry:
@@ -164,16 +252,6 @@ ifdef COMSPEC
 	@echo "AUBITDIR=`regtool get "/HKLM/Software/Aubit project/Aubit 4GL compiler/AUBITDIR"`"
 	@echo "A4GL_INIFILE=`regtool get "/HKLM/Software/Aubit project/Aubit 4GL compiler/A4GL_INIFILE"`"	
 	@echo "----------------------------------------------------------------"	
-endif
-
-#######################################
-install.libs.links: deinstall.libs.links
-	${MKPATH} ${LIB_INSTALL_LINK}
-ifeq "$(shell  if test -w ${LIB_INSTALL_LINK} ; then echo 1; fi)" "1"
-	${LN_S_LIB} $(INSTALL_DIR)/lib/libaubit4gl${SO_EXT} ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}
-	@echo "Links to Aubit libraries installed to ${LIB_INSTALL_LINK}/ "
-else
-	@echo "WARNING: ${LIB_INSTALL_LINK} is not writable - won't install Aubit libraries there"
 endif
 
 ## ==================================================================
@@ -241,6 +319,9 @@ deinstall.tree:
 #Remove entries added to system configuration for libraries paths
 deinstall.ldconfig:
 ifneq "${LDCONFIG}" "no"
+	@if test -w /etc/ld.so.conf.d ; then \
+		${RM} /etc/ld.so.conf.d/aubit4gl.conf; \
+	fi
 #remove entry from library path config file:
 ifeq "${GREP_LD_SO_CONF}" ""
 	@echo "$(INSTALL_DIR)/lib entry in ${LD_SO_CONF} does not exist."
@@ -258,25 +339,54 @@ endif
 #######################################
 #remove links to libraries:
 deinstall.libs.links:
-ifeq "$(shell  if test -w ${LIB_INSTALL_LINK} ; then echo 1; fi)" "1"
-	${RM} ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}
-else
-ifeq "$(shell  if test -f ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT} ; then echo 1; fi)" "1"
-	@echo "WARNING : Unable to remove ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}"
-endif
-endif
+#Remove the link from plain name to the one with version string:
+	${RM} $(INSTALL_DIR)/lib/libaubit4gl${SO_EXT}
+#	@echo "checking ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}"
+	@if test -L ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}; then \
+		if test -w ${LIB_INSTALL_LINK} ; then \
+			${RM} ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}; \
+			echo "Removed libaubit4gl link in ${LIB_INSTALL_LINK}"; \
+		else \
+			echo " "; \
+			echo "+---------------------------------------------------------------------------"; \
+			echo "| WARNING : Unable to remove link ${LIB_INSTALL_LINK}/libaubit4gl${SO_EXT}"; \
+			echo "| - insufficienet user permisions"; \
+			echo "+---------------------------------------------------------------------------"; \
+		fi; \
+	fi
+
 
 #######################################
 #remove links to binaries:
 deinstall.bin.links:
-ifeq "$(shell  if test -w ${BIN_INSTALL_LINK} ; then echo 1; fi)" "1"
-	${RM} ${BIN_INSTALL_LINK}/aubit-config ${BIN_INSTALL_LINK}/aubit
-else
-ifeq "$(shell  if test -w ${BIN_INSTALL_LINK} ; then echo 1; fi)" "1"
-	@echo "WARNING  :Unable to remove the aubit-config and aubit files in the ${BIN_INSTALL_LINK} directory"
-endif
-	
-endif
+	@if test -L ${BIN_INSTALL_LINK}/aubit-config -o -L ${BIN_INSTALL_LINK}/aubit \
+			-o -L ${BIN_INSTALL_LINK}/amake; then \
+		if test -w ${BIN_INSTALL_LINK} ; then \
+			${RM} ${BIN_INSTALL_LINK}/aubit-config ${BIN_INSTALL_LINK}/aubit \
+				${BIN_INSTALL_LINK}/amake; \
+			echo "Removed aubit-config, amake and aubit links in ${BIN_INSTALL_LINK}"; \
+		else \
+			echo " "; \
+			echo "+---------------------------------------------------------------------------"; \
+			echo "| WARNING:Unable to remove the aubit-config and aubit links in the"; \
+			echo "| ${BIN_INSTALL_LINK} directory - insufficienet user permisions"; \
+			echo "+---------------------------------------------------------------------------"; \
+		fi \
+	fi
+	@if test -L ${HOME}/bin/aubit-config -o -L ${HOME}/bin/aubit \
+			-o -L ${HOME}/bin/amake; then \
+		if test -w ${HOME}/bin ; then \
+			${RM} ${HOME}/bin/aubit-config ${HOME}/bin/aubit \
+				${HOME}/bin/amake; \
+			echo "Removed aubit-config, amake and aubit links in ${HOME}/bin/aubit-config"; \
+		else \
+			echo " "; \
+			echo "+---------------------------------------------------------------------------"; \
+			echo "| WARNING:Unable to remove the aubit-config and aubit links in the"; \
+			echo "| ${BIN_INSTALL_LINK} directory - insufficienet user permisions"; \
+			echo "+---------------------------------------------------------------------------"; \
+		fi \
+	fi
 
 #######################################
 #stuff left over from automatic nightly builds (aubitbuild.sh):
