Moving yy stuff into a4gl_ namespace, and small fixes

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -20165,12 +20165,7 @@ fi
 		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.xmlrpc"
 	fi
 
-	if test "$HAVE_RPCLIB" != "0" && test "$GTKBUILD" != "no"; then
-		RPMFILE_11=$LIB_PREFIX/libMENU_XDR$SO_EXT
-		PLUGIN_YES="$PLUGIN_YES MENU_XDR"
-    else
-        PLUGIN_NO="$PLUGIN_NO MENU_XDR"
-    fi
+#RPMFILE_11 is unused - use it.
 
 	if test "$HAVE_RPCLIB" != "0"; then
 		RPMFILE_12=$LIB_PREFIX/libRPC_XDR$SO_EXT
@@ -20263,7 +20258,15 @@ fi
 		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.gtk"
 	fi
 
-	#RPMFILE_27=$LIB_PREFIX/
+	#All libMENU_xxx need libUI_GTK on Windows to be linked with, to
+    #resolve symbols - so all libMENU_ must be built after libUI_GTK
+	if test "$HAVE_RPCLIB" != "0" && test "$GTKBUILD" != "no"; then
+		RPMFILE_27=$LIB_PREFIX/libMENU_XDR$SO_EXT
+		PLUGIN_YES="$PLUGIN_YES MENU_XDR"
+    else
+        PLUGIN_NO="$PLUGIN_NO MENU_XDR"
+    fi
+
 	#RPMFILE_28=$LIB_PREFIX/
 	#RPMFILE_29=$LIB_PREFIX/
 	#RPMFILE_30=$LIB_PREFIX/
@@ -20317,9 +20320,9 @@ else
 
 fi
 
-  echo "$as_me:20320: result: " >&5
+  echo "$as_me:20323: result: " >&5
 echo "${ECHO_T}" >&6
-  echo "$as_me:20322: result: ${T_MD}Creating files:${T_ME}" >&5
+  echo "$as_me:20325: result: ${T_MD}Creating files:${T_ME}" >&5
 echo "${ECHO_T}${T_MD}Creating files:${T_ME}" >&6
 
 cat >confcache <<\_ACEOF
@@ -20401,7 +20404,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:20404: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:20407: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -20577,7 +20580,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:20580: error: ambiguous option: $1
+    { { echo "$as_me:20583: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -20596,7 +20599,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:20599: error: unrecognized option: $1
+  -*) { { echo "$as_me:20602: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -20705,7 +20708,7 @@ do
   "etc/aubitrc-bin" ) CONFIG_FILES="$CONFIG_FILES etc/aubitrc-bin" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "incl/a4gl_incl_config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS incl/a4gl_incl_config.h" ;;
-  *) { { echo "$as_me:20708: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20711: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -21157,7 +21160,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:21160: creating $ac_file" >&5
+    { echo "$as_me:21163: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -21175,7 +21178,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:21178: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:21181: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -21188,7 +21191,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:21191: error: cannot find input file: $f" >&5
+           { { echo "$as_me:21194: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -21249,7 +21252,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:21252: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:21255: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -21260,7 +21263,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:21263: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:21266: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -21273,7 +21276,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:21276: error: cannot find input file: $f" >&5
+           { { echo "$as_me:21279: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -21390,7 +21393,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:21393: $ac_file is unchanged" >&5
+      { echo "$as_me:21396: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -21724,13 +21727,13 @@ X
 
 fi
 
-echo "$as_me:21727: result: " >&5
+echo "$as_me:21730: result: " >&5
 echo "${ECHO_T}" >&6
-echo "$as_me:21729: result: Thank you for using Aubit 4gl compiler." >&5
+echo "$as_me:21732: result: Thank you for using Aubit 4gl compiler." >&5
 echo "${ECHO_T}Thank you for using Aubit 4gl compiler." >&6
-echo "$as_me:21731: result:               $AUBIT_PUBLISHER" >&5
+echo "$as_me:21734: result:               $AUBIT_PUBLISHER" >&5
 echo "${ECHO_T}              $AUBIT_PUBLISHER" >&6
-echo "$as_me:21733: result: " >&5
+echo "$as_me:21736: result: " >&5
 echo "${ECHO_T}" >&6
 
 #------------------------------ EOF --------------------------------
