Updates

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -19346,7 +19346,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES GTK"
 	else
         PLUGIN_NO="$PLUGIN_NO GTK"
-		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL "
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.gtk"
 	fi
 
 	if test "$HAVE_CURSES" = "1" || test "$HAVE_PDCURSES" = "1"; then
@@ -19354,6 +19354,8 @@ fi
         PLUGIN_YES="$PLUGIN_YES TUI"
 	else
         PLUGIN_NO="$PLUGIN_NO TUI"
+		#should be on every Linux
+		#INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL "
 	fi
 
 	if test "$PDFBUILD" != "no"; then
@@ -19369,6 +19371,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES IFX_NATIVE"
 	else
         PLUGIN_NO="$PLUGIN_NO IFX_NATIVE"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.ifx.esql"
 	fi
 
 	if test "$HAVE_PGODBC" = "yes" ; then
@@ -19376,6 +19379,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES PG_ODBC"
 	else
         PLUGIN_NO="$PLUGIN_NO PG_ODBC"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.pg.odbc"
 	fi
 
 	if test "$HAVE_IFXODBC" = "yes" ; then
@@ -19383,6 +19387,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES IFXODBC"
 	else
         PLUGIN_NO="$PLUGIN_NO IFXODBC"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.ifx.odbc"
 	fi
 
 	if test "$HAVE_IODBC" = "yes" ; then
@@ -19398,6 +19403,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES unixODBC"
 	else
         PLUGIN_NO="$PLUGIN_NO unixODBC"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.unixodbc"
 	fi
 
 	if test "$cygwin" = "1"; then
@@ -19414,6 +19420,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES XML-RPC"
 	else
         PLUGIN_NO="$PLUGIN_NO XML-RPC"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.xmmlrpc"
 	fi
 
 	if test "$HAVE_RPCLIB" != "0" && test "$GTKBUILD" != "no"; then
@@ -19434,6 +19441,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES RPC_XDR FORM_XDR XDRPACKER"
 	else
         PLUGIN_NO="$PLUGIN_NO RPC_XDR FORM_XDR XDRPACKER"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.sunrpc"
 	fi
 
 	if test "$EXDATA_MPZ" != "no"; then
@@ -19441,6 +19449,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES MPZ"
 	else
         PLUGIN_NO="$PLUGIN_NO MPZ"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.mpz"
 	fi
 
 	if test "$HAVE_SAPODBC" = "yes" ; then
@@ -19448,6 +19457,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES SAPODBC"
 	else
         PLUGIN_NO="$PLUGIN_NO SAPODBC"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.sapdb.odbc"
 	fi
 
 	#this is made by 'make extra'
@@ -19469,6 +19479,7 @@ fi
         PLUGIN_YES="$PLUGIN_YES PG_NATIVE"
 	else
         PLUGIN_NO="$PLUGIN_NO PG_NATIVE"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.pg.esql"
 	fi
 
 	if test "$DOT" = "no"; then
@@ -19476,7 +19487,7 @@ fi
     fi
 
 	if test "$DOXYGEN" = "no"; then
-		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL "
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.doxygen"
     fi
 
 	#RPMFILE_25=$LIB_PREFIX/
@@ -19515,9 +19526,9 @@ else
 
 fi
 
-  echo "$as_me:19518: result: " >&5
+  echo "$as_me:19529: result: " >&5
 echo "${ECHO_T}" >&6
-  echo "$as_me:19520: result: ${T_MD}Creating files:${T_ME}" >&5
+  echo "$as_me:19531: result: ${T_MD}Creating files:${T_ME}" >&5
 echo "${ECHO_T}${T_MD}Creating files:${T_ME}" >&6
 
 cat >confcache <<\_ACEOF
@@ -19599,7 +19610,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:19602: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:19613: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -19775,7 +19786,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:19778: error: ambiguous option: $1
+    { { echo "$as_me:19789: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -19794,7 +19805,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:19797: error: unrecognized option: $1
+  -*) { { echo "$as_me:19808: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -19901,7 +19912,7 @@ do
   "etc/aubitrc-bin" ) CONFIG_FILES="$CONFIG_FILES etc/aubitrc-bin" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "incl/a4gl_incl_config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS incl/a4gl_incl_config.h" ;;
-  *) { { echo "$as_me:19904: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:19915: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20346,7 +20357,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20349: creating $ac_file" >&5
+    { echo "$as_me:20360: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20364,7 +20375,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20367: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20378: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20377,7 +20388,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20380: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20391: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20438,7 +20449,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20441: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20452: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20449,7 +20460,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20452: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20463: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20462,7 +20473,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20465: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20476: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20579,7 +20590,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:20582: $ac_file is unchanged" >&5
+      { echo "$as_me:20593: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -20891,13 +20902,13 @@ X
 
 fi
 
-echo "$as_me:20894: result: " >&5
+echo "$as_me:20905: result: " >&5
 echo "${ECHO_T}" >&6
-echo "$as_me:20896: result: Thank you for using Aubit 4gl compiler." >&5
+echo "$as_me:20907: result: Thank you for using Aubit 4gl compiler." >&5
 echo "${ECHO_T}Thank you for using Aubit 4gl compiler." >&6
-echo "$as_me:20898: result:               $AUBIT_PUBLISHER" >&5
+echo "$as_me:20909: result:               $AUBIT_PUBLISHER" >&5
 echo "${ECHO_T}              $AUBIT_PUBLISHER" >&6
-echo "$as_me:20900: result: " >&5
+echo "$as_me:20911: result: " >&5
 echo "${ECHO_T}" >&6
 
 #------------------------------ EOF --------------------------------
