Updates on SuSE 9

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -9320,7 +9320,7 @@ ALL_LINGUAS="en"
 
 #examlpe - USE iT
 #AC_ARG_WITH(pdflibname,[  --with-pdflibname=name  set file name of generated library [default=pdf]],[PDFLIBNAME="$withval"])
-# $Id: configure,v 1.228 2004-02-02 09:37:34 afalout Exp $
+# $Id: configure,v 1.229 2004-02-06 22:50:13 afalout Exp $
 
 
 if test "$with_all" = ""; then              with_all=yes        ;fi
@@ -14772,11 +14772,10 @@ echo "${ECHO_T}No-Cannot read version number" >&6
 			PG_ESQLC_IFXCOMPAT=no
         fi
 
-        #if test "$PG_ESQLC_IFXCOMPAT" = "yes"; then
-		#why not test anyway? we at least need to know if we have headers
+		#we at least need to know if we have headers
 		#for compiling things like SQL_c_ecpg that do not need IFX compatibility
 
-            #check PostgreSQL db engine version - we need 7.4, and NOT beta
+            #check PostgreSQL db engine version
 			# Extract the first word of "postmaster", so it can be a program name with args.
 set dummy postmaster; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -14819,31 +14818,41 @@ fi
 
 
             if test "$POSTMASTER" != "no"; then
-				echo "$as_me:$LINENO: checking PG engine Informix compatibility" >&5
-echo $ECHO_N "checking PG engine Informix compatibility... $ECHO_C" >&6
+				echo "$as_me:$LINENO: checking PG engine version" >&5
+echo $ECHO_N "checking PG engine version... $ECHO_C" >&6
 				POSTMASTER_VER=`$POSTMASTER --version 2>&1 | head -1 | sed -e 's/postmaster (PostgreSQL) //'`
 				#7.1.3
 				case "$POSTMASTER_VER" in
 					6.*.* | 7.1.* | 7.2.* | 7.3.*)
-				    	echo "$as_me:$LINENO: result: No-$POSTMASTER_VER" >&5
-echo "${ECHO_T}No-$POSTMASTER_VER" >&6
-						{ echo "$as_me:$LINENO: WARNING: ** Locally installed PostgreSQL db engine is" >&5
-echo "$as_me: WARNING: ** Locally installed PostgreSQL db engine is" >&2;}
-						{ echo "$as_me:$LINENO: WARNING: ** NOT Informix compatible." >&5
-echo "$as_me: WARNING: ** NOT Informix compatible." >&2;}
-						#don't reset PG_ESQLC_IFXCOMPAT because user might use
-                        #remote one
+				    	echo "$as_me:$LINENO: result: $POSTMASTER_VER" >&5
+echo "${ECHO_T}$POSTMASTER_VER" >&6
 					    ;;
 					*.*.*) #7.4.0 and up
-				    	echo "$as_me:$LINENO: result: Yes-$POSTMASTER_VER" >&5
-echo "${ECHO_T}Yes-$POSTMASTER_VER" >&6
+				    	echo "$as_me:$LINENO: result: $POSTMASTER_VER" >&5
+echo "${ECHO_T}$POSTMASTER_VER" >&6
 			            ;;
 					*)
-				    	{ echo "$as_me:$LINENO: WARNING: No-Invalid version number format-$POSTMASTER_VER" >&5
-echo "$as_me: WARNING: No-Invalid version number format-$POSTMASTER_VER" >&2;}
+				    	{ echo "$as_me:$LINENO: WARNING: Invalid version number format-$POSTMASTER_VER" >&5
+echo "$as_me: WARNING: Invalid version number format-$POSTMASTER_VER" >&2;}
 					    ;;
 		        esac
 
+				echo "$as_me:$LINENO: checking PG engine IFX compatibility-informix_serial function" >&5
+echo $ECHO_N "checking PG engine IFX compatibility-informix_serial function... $ECHO_C" >&6
+			 	TMP=`nm -A --defined-only $POSTMASTER | grep informix_serial`
+				if test "$TMP" != ""; then
+					echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+				else
+					echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+					{ echo "$as_me:$LINENO: WARNING: ** Locally installed PostgreSQL db engine is" >&5
+echo "$as_me: WARNING: ** Locally installed PostgreSQL db engine is" >&2;}
+					{ echo "$as_me:$LINENO: WARNING: ** NOT Informix compatible." >&5
+echo "$as_me: WARNING: ** NOT Informix compatible." >&2;}
+					#don't reset PG_ESQLC_IFXCOMPAT because user might use
+                    #remote one
+				fi
 
             else
 				{ echo "$as_me:$LINENO: WARNING: No locally installed postmaster detected" >&5
@@ -15390,7 +15399,9 @@ fi
 
 				echo "$as_me:$LINENO: checking PG ESQL libraryes compatibility" >&5
 echo $ECHO_N "checking PG ESQL libraryes compatibility... $ECHO_C" >&6
-				if test "$ac_cv_lib_ecpg_main" = "yes" -a "$ac_cv_lib_pgtypes_main" = "yes" -a "$ac_cv_lib_ecpg_compat_main" = "yes"; then
+				if test "$ac_cv_lib_ecpg_main" = "yes" \
+					-a "$ac_cv_lib_pgtypes_main" = "yes" \
+					-a "$ac_cv_lib_ecpg_compat_main" = "yes"; then
 					echo "$as_me:$LINENO: result: OK" >&5
 echo "${ECHO_T}OK" >&6
                     #POSTGRESDIR is really a ecpg installation dir, but...
@@ -15410,7 +15421,7 @@ echo "$as_me: WARNING: Disabled ecpg - no headers" >&2;}
 
 			CFLAGS=$old_CFLAGS; LDFLAGS=$old_LDFLAGS; LIBS=$old_LIBS; CPPFLAGS="$old_CPPFLAGS"
 
-		#fi  #if "$PG_ESQLC_IFXCOMPAT" = "yes"
+
     fi
   else
     echo "$as_me:$LINENO: result: disabled" >&5
@@ -16535,20 +16546,10 @@ _ACEOF
 fi
 
 		if test $ac_cv_lib_sqlod_main = yes; then
+			#First test for WINDOWS.H - it defines stuff like DWORD which is needed by
+			#other SAP ODBC headers
 
-
-		#Note: On SuSE 9 sqltypes failed to compile with:
-		#/opt/sapdb/interfaces/odbc/incl/sqltypes.h:296: error: parse error before "DWORD"
-		#Don't know why - needs investigating
-
-
-
-
-
-for ac_header in interfaces/odbc/incl/sql.h \
-								interfaces/odbc/incl/sqlext.h \
-								interfaces/odbc/incl/sqltypes.h \
-								interfaces/odbc/incl/WINDOWS.H
+for ac_header in interfaces/odbc/incl/WINDOWS.H
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -16689,6 +16690,70 @@ fi
 
 done
 
+
+			if test "$ac_cv_header_interfaces_odbc_incl_WINDOWS_H" = "yes"; then
+				#Now test for remaining 3, and include WINDOWS.H in testing code:
+
+
+
+for ac_header in interfaces/odbc/incl/sql.h \
+						interfaces/odbc/incl/sqlext.h \
+						interfaces/odbc/incl/sqltypes.h \
+
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#if HAVE_INTERFACES_ODBC_INCL_WINDOWS_H
+						# include <interfaces/odbc/incl/WINDOWS.H>
+						# endif
+
+
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+			fi
         fi
 		LIBS="$old_LIBS"
 		LDFLAGS="$old_LDFLAGS"
@@ -17543,6 +17608,7 @@ fi
 		if test $ac_cv_lib_iodbc_main = yes; then
 
 			#do we need to check for headers ?
+			#This two tests are for debugging only:
 
 
 
@@ -26296,7 +26362,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 26299 "configure"' > conftest.$ac_ext
+  echo '#line 26365 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -26776,7 +26842,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 26779 "configure"
+#line 26845 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -26874,7 +26940,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 26877 "configure"
+#line 26943 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -31429,7 +31495,7 @@ cat<<X
 | CONFIGURE_COMMAND="$CONFIGURE_COMMAND"
 |                                                                    |
 | CONFIGURE_VERSION:                                                 |
-| $Id: configure,v 1.228 2004-02-02 09:37:34 afalout Exp $
+| $Id: configure,v 1.229 2004-02-06 22:50:13 afalout Exp $
 |                                                                    |
 +--------------------------------------------------------------------+
 X
