update to allow 4glc to be used on assist.4gl

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -19728,14 +19728,6 @@ fi
 ##              RPM packaging, install/seinstall and build process
 ## ==================================================================
 
-	if test "$GTKBUILD" != "no"; then
-		RPMFILE_1=$LIB_PREFIX/libUI_GTK$SO_EXT
-        PLUGIN_YES="$PLUGIN_YES GTK"
-	else
-        PLUGIN_NO="$PLUGIN_NO GTK"
-		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.gtk"
-	fi
-
 	if test "$HAVE_CURSES" = "1" || test "$HAVE_PDCURSES" = "1"; then
         RPMFILE_2=$LIB_PREFIX/libUI_TUI$SO_EXT
         PLUGIN_YES="$PLUGIN_YES TUI"
@@ -19861,6 +19853,16 @@ fi
 	RPMFILE_23=$LIB_PREFIX/libA4GL_HTML$SO_EXT_LINKABLE
 	PLUGIN_YES="$PLUGIN_YES FILE STRING HTML"
 
+	#GTK plug-in may need to recompile assist.4gl, so it may need to have 4glc,
+    #so it needs to be AFTER all other plug-ins needed by 4glc, like SQL plug-ins:
+	if test "$GTKBUILD" != "no"; then
+		RPMFILE_1=$LIB_PREFIX/libUI_GTK$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES GTK"
+	else
+        PLUGIN_NO="$PLUGIN_NO GTK"
+		INSTALL_MISSING_OPTIONAL="$INSTALL_MISSING_OPTIONAL install.gtk"
+	fi
+
     #temp disabled:
     #if test "$HAVE_PGSQL_LIB" = "yes"; then
 	#	RPMFILE_24=$LIB_PREFIX/libSQL_pg$SO_EXT
@@ -19918,9 +19920,9 @@ else
 
 fi
 
-  echo "$as_me:19921: result: " >&5
+  echo "$as_me:19923: result: " >&5
 echo "${ECHO_T}" >&6
-  echo "$as_me:19923: result: ${T_MD}Creating files:${T_ME}" >&5
+  echo "$as_me:19925: result: ${T_MD}Creating files:${T_ME}" >&5
 echo "${ECHO_T}${T_MD}Creating files:${T_ME}" >&6
 
 cat >confcache <<\_ACEOF
@@ -20002,7 +20004,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:20005: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:20007: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -20178,7 +20180,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:20181: error: ambiguous option: $1
+    { { echo "$as_me:20183: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -20197,7 +20199,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:20200: error: unrecognized option: $1
+  -*) { { echo "$as_me:20202: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -20304,7 +20306,7 @@ do
   "etc/aubitrc-bin" ) CONFIG_FILES="$CONFIG_FILES etc/aubitrc-bin" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "incl/a4gl_incl_config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS incl/a4gl_incl_config.h" ;;
-  *) { { echo "$as_me:20307: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20309: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20751,7 +20753,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20754: creating $ac_file" >&5
+    { echo "$as_me:20756: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20769,7 +20771,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20772: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20774: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20782,7 +20784,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20785: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20787: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20843,7 +20845,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20846: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20848: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20854,7 +20856,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20857: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20859: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20867,7 +20869,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20870: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20872: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20984,7 +20986,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:20987: $ac_file is unchanged" >&5
+      { echo "$as_me:20989: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -21315,13 +21317,13 @@ X
 
 fi
 
-echo "$as_me:21318: result: " >&5
+echo "$as_me:21320: result: " >&5
 echo "${ECHO_T}" >&6
-echo "$as_me:21320: result: Thank you for using Aubit 4gl compiler." >&5
+echo "$as_me:21322: result: Thank you for using Aubit 4gl compiler." >&5
 echo "${ECHO_T}Thank you for using Aubit 4gl compiler." >&6
-echo "$as_me:21322: result:               $AUBIT_PUBLISHER" >&5
+echo "$as_me:21324: result:               $AUBIT_PUBLISHER" >&5
 echo "${ECHO_T}              $AUBIT_PUBLISHER" >&6
-echo "$as_me:21324: result: " >&5
+echo "$as_me:21326: result: " >&5
 echo "${ECHO_T}" >&6
 
 #------------------------------ EOF --------------------------------
