First take on native Windows port using MinGW GCC and CygWin tools - SOME THINGS ARE PROBABLY BROKEN

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -7827,6 +7827,19 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 ##                             Defaults
 ## ==================================================================
 
+#AC_LIBLTDL_INSTALLABLE
+  case $enable_ltdl_convenience in
+  no) { { echo "$as_me:$LINENO: error: this package needs a convenience libltdl" >&5
+echo "$as_me: error: this package needs a convenience libltdl" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  "") enable_ltdl_convenience=yes
+      ac_configure_args="$ac_configure_args --enable-ltdl-convenience" ;;
+  esac
+  LIBLTDL='${top_builddir}/''libltdl'/libltdlc.la
+  INCLTDL='-I${top_srcdir}/''libltdl'
+
+
+
 if test "$AUBIT_SOURCE" = "1" ; then
 	#need to do this again, since the earlyer one was before initialisation,
 	#and will not get in substitution otherwise:
@@ -8171,12 +8184,10 @@ echo "$as_me: error: Cannot compile Aubit from source code without 'make' - plea
 echo "$as_me: WARNING: It will be much easier if you would install 'make'" >&2;}
     fi
 else
-#make --version'
 		echo "$as_me:$LINENO: checking make version" >&5
 echo $ECHO_N "checking make version... $ECHO_C" >&6
 		#this creates fill set dump on Solaris
 		set `make --version | head -1|sed -e 's/^GNU Make version //' -e 's/, by Richard Stallman and Roland McGrath.//' -e 's/\./ /g'`
-		#set `bison --version|head -1|sed -e 's/^GNU Bison version //' -e 's/^bison (GNU Bison) //' -e 's/\./ /g'`
 		if test "$1" != ""; then
 			if test "$1" = "3" -a "$2" -lt "50"; then
 		        { echo "$as_me:$LINENO: WARNING: You will need GNU make version 3.50 or later (found $1.$2.$3)." >&5
@@ -9419,7 +9430,11 @@ echo $ECHO_N "checking GCC version... $ECHO_C" >&6
 	#$ gcc --version
 	#gcc (GCC) 3.2 20020818 (prerelease)
 
+	#gcc.exe (GCC) 3.2 (mingw special 20020817-1)
+
 	TMP_TMP=`gcc --version | head -1 | sed -e 's/^gcc (GCC) //' -e 's/ (prerelease)//' -e 's/\./ /g'`
+	TMP_TMP=`gcc --version | head -1 | sed -e 's/^gcc//' -e 's/(GCC)//' -e 's/ (prerelease)//' -e 's/(//' -e 's/\.exe//' -e 's/\./ /g'`
+	#  3 2 mingw special 20020817-1)
 	if test "$TMP_TMP" != ""; then
 		set `echo $TMP_TMP`
 		if test "$1" != ""; then
@@ -9430,6 +9445,32 @@ echo $ECHO_N "checking GCC version... $ECHO_C" >&6
 echo "${ECHO_T}$1.$2.$3" >&6
 	            GCC_VERSION_MAJOR=$1
 				GCC_VERSION_MINOR=$2
+                if test "$3" = "mingw"; then
+					GCC_MINGW=yes
+					{ echo "$as_me:$LINENO: WARNING: Using MinGW GCC. $CFLAGS" >&5
+echo "$as_me: WARNING: Using MinGW GCC. $CFLAGS" >&2;}
+					old_CFLAGS="$CFLAGS"
+					old_CPPFLAGS="$CPPFLAGS"
+					old_LDFLAGS="$LDFLAGS"
+
+					TMP_IFLAGS="-ID:/cygwin/usr/include"
+                    CFLAGS=" $CFLAGS $TMP_IFLAGS"
+					CPPFLAGS="$CPPFLAGS $TMP_IFLAGS"
+
+					#Clear cached value:
+					#unset ac_cv_header_dlfcn_h
+					#AC_CHECK_HEADERS([dlfcn.h])
+	                #exit
+					#In file included from d:/MinGW/include/inttypes.h:6,
+					#                 from configure:9489:
+					#d:/MinGW/include/stdint.h:27: conflicting types for `int8_t'
+					#D:/cygwin/usr/include/sys/types.h:128: previous declaration of `int8_t'
+
+					CFLAGS="$old_CFLAGS"
+					CPPFLAGS="$old_CPPFLAGS"
+					LDFLAGS="$old_LDFLAGS"
+                    TMP_IFLAGS=
+                fi
 	        #fi
 		else
 			{ echo "$as_me:$LINENO: WARNING: Cannot read GCC version." >&5
@@ -16002,11 +16043,21 @@ done
 		#Clear cached value:
 		unset ac_cv_header_dlfcn_h
 
-        #/sw/include/dlfcn.h
         old_CPPFLAGS="$CPPFLAGS"
 		#old_CLFAGS="$CFLAGS"
-        TMP_IFLAGS="-I/sw/include"
-		CPPFLAGS="$CPPFLAGS $TMP_IFLAGS"
+
+		case $host in
+			*-apple-darwin*)
+				#only on Darwin:
+				TMP_IFLAGS="-I/sw/include"
+                RE_CHECK=1
+				;;
+			*)
+		        ;;
+		esac
+
+        if test "$RE_CHECK" = "1"; then
+			CPPFLAGS="$CPPFLAGS $TMP_IFLAGS"
 
 for ac_header in dlfcn.h
 do
@@ -16121,11 +16172,17 @@ fi
 
 done
 
+        fi
 
 		if test `eval echo '${'$as_ac_Header'}'` != yes; then
-			{ { echo "$as_me:$LINENO: error: No dlfcn.h found - please install dl library. Stop." >&5
+			if test "$GCC_MINGW" = "yes"; then
+				{ echo "$as_me:$LINENO: WARNING: No dlfcn.h found" >&5
+echo "$as_me: WARNING: No dlfcn.h found" >&2;}
+            else
+				{ { echo "$as_me:$LINENO: error: No dlfcn.h found - please install dl library. Stop." >&5
 echo "$as_me: error: No dlfcn.h found - please install dl library. Stop." >&2;}
    { (exit 1); exit 1; }; }
+            fi
         else
 			CFLAGS="$CFLAGS $TMP_IFLAGS"
         fi
@@ -18606,7 +18663,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 18609 "configure"' > conftest.$ac_ext
+  echo '#line 18666 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -19074,7 +19131,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19077 "configure"
+#line 19134 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19172,7 +19229,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19175 "configure"
+#line 19232 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20798,43 +20855,73 @@ fi
 
 	if test "$GTKBUILD" != "no"; then
 		RPMFILE_1=$LIB_PREFIX/libUI_GTK$SO_EXT
-    fi
+        PLUGIN_YES="$PLUGIN_YES GTK"
+	else
+        PLUGIN_NO="$PLUGIN_NO GTK"
+	fi
 
 	if test "$HAVE_CURSES" = "1"; then
         RPMFILE_2=$LIB_PREFIX/libUI_TUI$SO_EXT
-    fi
+        PLUGIN_YES="$PLUGIN_YES TUI"
+	else
+        PLUGIN_NO="$PLUGIN_NO TUI"
+	fi
 
 	if test "$PDFBUILD" != "no"; then
 		RPMFILE_3=$LIB_PREFIX/libEXREPORT_PDF$SO_EXT
-    fi
+        PLUGIN_YES="$PLUGIN_YES PDF"
+	else
+        PLUGIN_NO="$PLUGIN_NO PDF"
+	fi
 
 	if test "$IFMX_ESQLC" != "no" ; then
 		RPMFILE_4=$LIB_PREFIX/libSQL_esql$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES IFX"
+	else
+        PLUGIN_NO="$PLUGIN_NO IFX"
 	fi
 
 	if test "$HAVE_PGODBC" = "yes" ; then
 		RPMFILE_5=$LIB_PREFIX/libSQL_pgodbc$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES PG"
+	else
+        PLUGIN_NO="$PLUGIN_NO PG"
 	fi
 
 	if test "$HAVE_IFXODBC" = "yes" ; then
 		RPMFILE_6=$LIB_PREFIX/libSQL_ifxodbc$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES IFXODBC"
+	else
+        PLUGIN_NO="$PLUGIN_NO IFXODBC"
 	fi
 
 	if test "$HAVE_IODBC" = "yes" ; then
 		RPMFILE_7=$LIB_PREFIX/libSQL_iodbc$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES iODBC"
+	else
+        PLUGIN_NO="$PLUGIN_NO iODBC"
 	fi
 
 	if test "$HAVE_UNIXODBC" = "yes" ; then
 		RPMFILE_8=$LIB_PREFIX/libSQL_unixodbc$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES unixODBC"
+	else
+        PLUGIN_NO="$PLUGIN_NO unixODBC"
 	fi
 
 	if test "$cygwin" = "1"; then
 		RPMFILE_9=$LIB_PREFIX/libSQL_odbc32$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES ODBC32"
+	else
+        PLUGIN_NO="$PLUGIN_NO ODBC32"
 	fi
 
 	if test "$XML_RPC" != "no"; then
 		RPMFILE_10=$LIB_PREFIX/libRPC_XMLRPC$SO_EXT
-    fi
+        PLUGIN_YES="$PLUGIN_YES XML-RPC"
+	else
+        PLUGIN_NO="$PLUGIN_NO XML-RPC"
+	fi
 
 	if test "$HAVE_RPCLIB" != "0"; then
 
@@ -20847,24 +20934,38 @@ fi
 		RPMFILE_16=$LIB_PREFIX/libXDRPACKER_struct_form$SO_EXT
         RPMFILE_17=$LIB_PREFIX/libPACKER_XDR$SO_EXT
 
+        PLUGIN_YES="$PLUGIN_YES MENU_XDR RPC_XDR FORM_XDR XDRPACKER"
+	else
+        PLUGIN_NO="$PLUGIN_NO MENU_XDR RPC_XDR FORM_XDR XDRPACKER"
 	fi
 
 	if test "$EXDATA_MPZ" != "no"; then
 		RPMFILE_18=$LIB_PREFIX/libEXDTYPE_mpz$SO_EXT
-    fi
+        PLUGIN_YES="$PLUGIN_YES MPZ"
+	else
+        PLUGIN_NO="$PLUGIN_NO MPZ"
+	fi
 
 	if test "$HAVE_SAPODBC" = "yes" ; then
 		RPMFILE_19=$LIB_PREFIX/libSQL_sapodbc$SO_EXT
+        PLUGIN_YES="$PLUGIN_YES SAPODBC"
+	else
+        PLUGIN_NO="$PLUGIN_NO SAPODBC"
 	fi
 
 	#this is made by 'make extra'
 	if test "$JABBERBUILD" != "no"; then
 		RPMFILE_20=$LIB_PREFIX/libIM_JABBER$SO_EXT_LINKABLE
+        PLUGIN_YES="$PLUGIN_YES JABBER"
+	else
+        PLUGIN_NO="$PLUGIN_NO JABBER"
 	fi
 
 	RPMFILE_21=$LIB_PREFIX/libA4GL_file$SO_EXT
 	RPMFILE_22=$LIB_PREFIX/libA4GL_string$SO_EXT
 	RPMFILE_23=$LIB_PREFIX/libA4GL_HTML$SO_EXT_LINKABLE
+	PLUGIN_YES="$PLUGIN_YES FILE STRING HTML"
+
 	#RPMFILE_24=$LIB_PREFIX/
 	#RPMFILE_25=$LIB_PREFIX/
 	#RPMFILE_26=$LIB_PREFIX/
@@ -21696,6 +21797,7 @@ s,@ARCHEXT@,$ARCHEXT,;t t
 s,@CONFIGURE_COMMAND@,$CONFIGURE_COMMAND,;t t
 s,@GCC_VERSION_MAJOR@,$GCC_VERSION_MAJOR,;t t
 s,@GCC_VERSION_MINOR@,$GCC_VERSION_MINOR,;t t
+s,@GCC_MINGW@,$GCC_MINGW,;t t
 s,@CURSES_LIB_PATH@,$CURSES_LIB_PATH,;t t
 s,@CURSES_INC_PATH@,$CURSES_INC_PATH,;t t
 s,@HAVE_CURSES@,$HAVE_CURSES,;t t
@@ -22411,7 +22513,6 @@ cat<<X
 | exactly what you are doing.                                        |
 X
 fi
-
 if test "$INFORMIXODBC_WARNING" = "1"; then
 cat<<X
 +--------------------------------------------------------------------+
@@ -22460,7 +22561,14 @@ cat<<X
 | the installation process at this point.                            |
 +--------------------------------------------------------------------+
 X
-
+cat<<X
++--------------------------------------------------------------------+
+|                        ***  NOTE   ***                             |
+| Aubit plug-ins to build:
+| $PLUGIN_YES
+| Aubit plug-ins the will not be built:                              |
+| $PLUGIN_NO
+X
 if test "$AUBIT_SOURCE" = "1" ; then
 cat<<X
 |                          *** NOTE ***                              |
