.

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -2046,6 +2046,7 @@ PROG_SENDMAIL
 IKSPERF
 LIBWWW_CONFIG
 PDFLIB_CONFIG
+HAVE_LIBQRENCODE
 MAKECINT
 FJS_PCOMPILER
 FJS_PRUNTIME
@@ -2749,6 +2750,7 @@ Optional Packages:
                           install directory, defaults to /usr/local.
   --with-pdf=DIR          Include PDF support.  DIR is the PDFlib
                           install directory, defaults to /usr/local.
+--with-qrencoder
   --with-cint=DIR         Include CINT support.  DIR is the Cint base
                           install directory, defaults to /usr/local.
   --with-fourj=DIR        Include 4Js compiler support.  DIR is the 4Js base
@@ -6511,7 +6513,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6514 "configure"' > conftest.$ac_ext
+  echo '#line 6516 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9022,11 +9024,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9025: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9027: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9029: \$? = $ac_status" >&5
+   echo "$as_me:9031: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9312,11 +9314,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9317: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9319: \$? = $ac_status" >&5
+   echo "$as_me:9321: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9416,11 +9418,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9419: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9421: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9423: \$? = $ac_status" >&5
+   echo "$as_me:9425: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11778,7 +11780,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11781 "configure"
+#line 11783 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11878,7 +11880,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11881 "configure"
+#line 11883 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14298,11 +14300,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14301: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14303: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14305: \$? = $ac_status" >&5
+   echo "$as_me:14307: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14402,11 +14404,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14405: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14407: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14409: \$? = $ac_status" >&5
+   echo "$as_me:14411: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15977,11 +15979,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15982: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15984: \$? = $ac_status" >&5
+   echo "$as_me:15986: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16081,11 +16083,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16084: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16086: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16088: \$? = $ac_status" >&5
+   echo "$as_me:16090: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18281,11 +18283,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18284: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18286: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18288: \$? = $ac_status" >&5
+   echo "$as_me:18290: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18571,11 +18573,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18574: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18576: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18578: \$? = $ac_status" >&5
+   echo "$as_me:18580: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18675,11 +18677,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18678: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18680: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18682: \$? = $ac_status" >&5
+   echo "$as_me:18684: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -31929,6 +31931,121 @@ fi
 if test "$enable_stop_pdf" = "yes" ; then
 	exit
 fi
+
+
+
+## ==================================================================
+##                 Checks for QREncoder support (QR Barcodes)
+## ==================================================================
+
+
+
+  { echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6; }
+  { echo "$as_me:$LINENO: result: ${T_MD}Checking for QREncoder support:${T_ME}" >&5
+echo "${ECHO_T}${T_MD}Checking for QREncoder support:${T_ME}" >&6; }
+
+
+save_LIBS="$LIBS"
+
+# Check whether --with-qrencoder was given.
+if test "${with_qrencoder+set}" = set; then
+  withval=$with_qrencoder; chk_qrencoder=x$withval
+else
+  chk_qrencoder=notset
+fi
+
+
+if test "$chk_qrencoder" = "xno"
+then
+	HAVE_LIBQRENCODE=0
+else
+
+{ echo "$as_me:$LINENO: checking for QRinput_new2 in -lqrencode" >&5
+echo $ECHO_N "checking for QRinput_new2 in -lqrencode... $ECHO_C" >&6; }
+if test "${ac_cv_lib_qrencode_QRinput_new2+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lqrencode  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char QRinput_new2 ();
+int
+main ()
+{
+return QRinput_new2 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_qrencode_QRinput_new2=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_qrencode_QRinput_new2=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_qrencode_QRinput_new2" >&5
+echo "${ECHO_T}$ac_cv_lib_qrencode_QRinput_new2" >&6; }
+if test $ac_cv_lib_qrencode_QRinput_new2 = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBQRENCODE 1
+_ACEOF
+
+  LIBS="-lqrencode $LIBS"
+
+fi
+
+	 if test "$ac_cv_lib_qrencode_qrinput_new2" = "yes"; then
+		HAVE_LIBQRENCODE=1
+	 else
+		HAVE_LIBQRENCODE=1
+	 fi
+
+fi
+
+
+if test "$enable_stop_qrencode" = "yes" ; then
+	exit
+fi
+
+LIBS="$save_LIBS"
+
 
 ## ==================================================================
 ##                 Checks for CINT - C code interpreter
@@ -50371,11 +50488,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:50374: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:50491: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:50378: \$? = $ac_status" >&5
+   echo "$as_me:50495: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -50475,11 +50592,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:50478: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:50595: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:50482: \$? = $ac_status" >&5
+   echo "$as_me:50599: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -54392,7 +54509,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 54395 "configure"' > conftest.$ac_ext
+  echo '#line 54512 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -55440,7 +55557,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 55443 "configure"
+#line 55560 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -55540,7 +55657,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 55543 "configure"
+#line 55660 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -61291,6 +61408,7 @@ PROG_SENDMAIL!$PROG_SENDMAIL$ac_delim
 IKSPERF!$IKSPERF$ac_delim
 LIBWWW_CONFIG!$LIBWWW_CONFIG$ac_delim
 PDFLIB_CONFIG!$PDFLIB_CONFIG$ac_delim
+HAVE_LIBQRENCODE!$HAVE_LIBQRENCODE$ac_delim
 MAKECINT!$MAKECINT$ac_delim
 FJS_PCOMPILER!$FJS_PCOMPILER$ac_delim
 FJS_PRUNTIME!$FJS_PRUNTIME$ac_delim
@@ -61328,7 +61446,7 @@ CYGCHECK!$CYGCHECK$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -62103,7 +62221,7 @@ cat<<X
 | CONFIGURE_COMMAND="$CONFIGURE_COMMAND"
 |                                                                    |
 | CONFIGURE_VERSION:                                                 |
-| $Id: configure,v 1.407 2008-05-15 13:39:55 mikeaubury Exp $
+| $Id: configure,v 1.408 2008-09-11 17:45:15 mikeaubury Exp $
 |                                                                    |
 +--------------------------------------------------------------------+
 X
