Added libpdf to autoconf and makefiles changed

diff --git a/aubit4glsrc/trunk/configure b/aubit4glsrc/trunk/configure
--- a/aubit4glsrc/trunk/configure
+++ b/aubit4glsrc/trunk/configure
@@ -4582,7 +4582,7 @@ EOF
 fi
 done
 
-ac_config_files="$ac_config_files Makefile compilers/4glc/Makefile compilers/4glc/rules/Makefile compilers/fcompile/Makefile compilers/helpcompile/Makefile compilers/menus/Makefile lib/libgui/Makefile lib/libsql/nosql/Makefile lib/libsql/odbc/Makefile lib/Makefile tools/adbaccess/Makefile tools/adbload/Makefile tools/html/Makefile tools/ide/Makefile tools/jabber/Makefile tools/odbctest/Makefile tools/test/gui/Makefile tools/test/Makefile"
+ac_config_files="$ac_config_files Makefile compilers/4glc/Makefile compilers/4glc/rules/Makefile compilers/fcompile/Makefile compilers/helpcompile/Makefile compilers/menus/Makefile lib/libpdf/Makefile lib/libgui/Makefile lib/libsql/nosql/Makefile lib/libsql/odbc/Makefile lib/Makefile tools/adbaccess/Makefile tools/adbload/Makefile tools/html/Makefile tools/ide/Makefile tools/jabber/Makefile tools/odbctest/Makefile tools/test/gui/Makefile tools/test/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4895,6 +4895,7 @@ do
   "compilers/fcompile/Makefile" ) CONFIG_FILES="$CONFIG_FILES compilers/fcompile/Makefile" ;;
   "compilers/helpcompile/Makefile" ) CONFIG_FILES="$CONFIG_FILES compilers/helpcompile/Makefile" ;;
   "compilers/menus/Makefile" ) CONFIG_FILES="$CONFIG_FILES compilers/menus/Makefile" ;;
+  "lib/libpdf/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/libpdf/Makefile" ;;
   "lib/libgui/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/libgui/Makefile" ;;
   "lib/libsql/nosql/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/libsql/nosql/Makefile" ;;
   "lib/libsql/odbc/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/libsql/odbc/Makefile" ;;
@@ -4908,7 +4909,7 @@ do
   "tools/test/gui/Makefile" ) CONFIG_FILES="$CONFIG_FILES tools/test/gui/Makefile" ;;
   "tools/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES tools/test/Makefile" ;;
   "incl/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS incl/config.h" ;;
-  *) { { echo "$as_me:4911: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4912: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5115,7 +5116,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5118: creating $ac_file" >&5
+    { echo "$as_me:5119: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5133,7 +5134,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5136: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5137: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5146,7 +5147,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5149: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5150: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5206,7 +5207,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5209: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5210: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5217,7 +5218,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5220: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5221: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5230,7 +5231,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5233: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5234: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5347,7 +5348,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5350: $ac_file is unchanged" >&5
+      { echo "$as_me:5351: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
