Updates and fixes

diff --git a/aubit4glsrc/trunk/configure.in b/aubit4glsrc/trunk/configure.in
--- a/aubit4glsrc/trunk/configure.in
+++ b/aubit4glsrc/trunk/configure.in
@@ -23,7 +23,7 @@ dnl # | If you did not, or have any questions about Aubit licensing, please  |
 dnl # | contact afalout@ihug.co.nz                                           |
 dnl # +----------------------------------------------------------------------+
 dnl #
-dnl # $Id: configure.in,v 1.201 2003-10-08 01:36:30 afalout Exp $
+dnl # $Id: configure.in,v 1.202 2003-10-09 13:01:05 afalout Exp $
 dnl #
 dnl #TODO: check that WARN_LD_LIBRARY_PATH is set ONLY if user specified custom withval
 dnl #and then check that it is no already in LD_LIBRARY_PATH or ldconfig file. Only
@@ -75,6 +75,7 @@ T_ME=`$a4gl_shtool echo -n -e %b`
 #if test "$enableval" = "yes" ; then
 #    WITH_DEBUG=yes
 #fi)
+#AC_ARG_ENABLE(rebuilds, [  --disable-rebuilds      disable all source autogeneration rules],,enable_rebuilds=yes)
 
 #Store parameters this script was invoked with
 CONFIGURE_COMMAND="$ac_configure_args"
@@ -95,33 +96,33 @@ if test "$AUBITCONF_FLAG" != "running"; then
 	## ==================================================================
         #This must be done on first pass only, since after we invoke
         #aubitconf, "echo -e" will not work ...
-		rm -f ./order.c ./order ./order.exe ./order.o ./order.tmp
-
-		echo "" > order.c
-		echo "main() {" >> order.c
-		echo "short a;" >> order.c
-		echo "char *ptr;" >> order.c
-		echo "a=1;" >> order.c
-		echo "ptr=(char *)&a;" >> order.c
-
-#		if test "$COMSPEC" = ""; then
-            #echo "-------------------NOT On Windows"
-			echo 'printf("%d%d",ptr\1330\135,ptr\1331\135);' > order.tmp
-		    xx=`cat order.tmp`
-			echo -e "$xx" >> order.c
-#        else
-#            #echo "-------------------On Windows"
-#			#echo 'printf("%d%d",ptr[0],ptr[1]);' > order.tmp
-#			#This craps out on CygWin
-#			echo -e 'printf("%d%d",ptr\1330\135,ptr\1331\135);' >> order.c
-#        fi
-
-		echo "}" >> order.c
-		echo "" >> order.c
-
-        #Above code is obsolete; see AC_C_BIGENDIAN later in the code
-
-
+##		rm -f ./order.c ./order ./order.exe ./order.o ./order.tmp
+##
+##		echo "" > order.c
+##		echo "main() {" >> order.c
+##		echo "short a;" >> order.c
+##		echo "char *ptr;" >> order.c
+##		echo "a=1;" >> order.c
+##		echo "ptr=(char *)&a;" >> order.c
+##
+###		if test "$COMSPEC" = ""; then
+##            #echo "-------------------NOT On Windows"
+##			echo 'printf("%d%d",ptr\1330\135,ptr\1331\135);' > order.tmp
+##		    xx=`cat order.tmp`
+##			echo -e "$xx" >> order.c
+###        else
+###            #echo "-------------------On Windows"
+###			#echo 'printf("%d%d",ptr[0],ptr[1]);' > order.tmp
+###			#This craps out on CygWin
+###			echo -e 'printf("%d%d",ptr\1330\135,ptr\1331\135);' >> order.c
+###        fi
+##
+##		echo "}" >> order.c
+##		echo "" >> order.c
+##
+##        #Above code is obsolete; see AC_C_BIGENDIAN later in the code
+##
+##
 
 	##############################
 
@@ -1390,29 +1391,58 @@ fi
 
 
 	if test "$prefix" = "NONE"; then
+        #Defaults:
 		if test "$cygwin" = "1" ; then
 			#/opt is not created by default on CygWin installations
-			prefix=/usr/local
+			prefix=/usr/local/$SHORTNAME
 		else
-			prefix=/opt
+			prefix=/opt/$SHORTNAME
 	    fi
+	else
+        #User specified:
+		if test -d "$prefix"; then
+			#We expect user to specify a full installation path;
+            #nothing will be added to it, so if he specifies "/usr" Aubit
+            #executables will go straoght into /usr/bin - is this OK?
+
+			AC_MSG_WARN( ** Directory specified as prefix:)
+			AC_MSG_WARN( ** $prefix)
+			AC_MSG_WARN( ** already exists.)
+			#Can't do this - if you run configure on already installed Aubit...?
+            #We will have to trust user to know what he's doing to some degree here... :-( right...
+			#AC_MSG_WARN( ** already exists. Adding suffix (/$SHORTNAME))
+            #prefix=$prefix/$SHORTNAME
+		fi
 	fi
+
+    #must create it now, otherwise -w test will fail
+	if ! test -d "$prefix"; then
+		mkdir "$prefix"
+	fi
+
 	AC_MSG_CHECKING(install root 'prefix=$prefix')
 	if test -w "$prefix"; then
 		AC_MSG_RESULT(Yes ($prefix))
     else
-		if test -w "$HOME"; then
-			prefix=$HOME
-			AC_MSG_RESULT(No (will use $prefix instead))
-        else
-			AC_MSG_ERROR(Cannot determine install path. HOME=$HOME Stop.)
-        fi
+        #Some scripts (like aubitbuild) will fail if we just decide to switch
+        #install location from what they specified using --prefix flag, so
+        #we better stop here:
+
+		AC_MSG_ERROR(Cannot determine install path. Try using HOME (--prefix=$HOME) Stop.)
+		#if test -w "$HOME"; then
+		#	prefix=$HOME/$SHORTNAME
+		#	AC_MSG_RESULT(No (will use HOME ($prefix) instead))
+        #else
+		#	AC_MSG_ERROR(Cannot determine install path. HOME=$HOME Stop.)
+        #fi
     fi
 
-INST_BASE=$prefix/$SHORTNAME
-LIB_PREFIX=$INST_BASE/lib
+#INST_BASE=$prefix/$SHORTNAME
+INST_BASE=$prefix
+#AC_MSG_RESULT(INST_BASE set to $INST_BASE)
 
-A4GL_DBPATH=$aubitdir/tools:$prefix/$SHORTNAME/tools
+LIB_PREFIX=$INST_BASE/lib
+A4GL_DBPATH=$aubitdir/tools:$INST_BASE/tools
 
 ## ==================================================================
 ##      Decide on install location for aubitrc configuration file
@@ -3866,6 +3896,42 @@ fi
 
 #</This block was copied from PHP 4.x ext/odbc/config.m4 ---------------->
 
+# Ensure MSVC-compatible struct packing convention is used when
+# compiling for Win32 with gcc.
+# What flag to depends on gcc version: gcc3 uses "-mms-bitfields", while
+# gcc2 uses "-fnative-struct".
+if test x"$glib_native_win32" = xyes; then
+  if test x"$GCC" = xyes; then
+    msnative_struct=''
+    AC_MSG_CHECKING([how to get MSVC-compatible struct packing])
+    if test -z "$ac_cv_prog_CC"; then
+      our_gcc="$CC"
+    else
+      our_gcc="$ac_cv_prog_CC"
+    fi
+    case `$our_gcc --version | sed -e 's,\..*,.,' -e q` in
+      2.)
+	if $our_gcc -v --help 2>/dev/null | grep fnative-struct >/dev/null; then
+	  msnative_struct='-fnative-struct'
+	fi
+	;;
+      *)
+	if $our_gcc -v --help 2>/dev/null | grep ms-bitfields >/dev/null; then
+	  msnative_struct='-mms-bitfields'
+	fi
+	;;
+    esac
+    if test x"$msnative_struct" = x ; then
+      AC_MSG_RESULT([no way])
+      AC_MSG_WARN([produced libraries might be incompatible with MSVC-compiled code])
+    else
+      CFLAGS="$CFLAGS $msnative_struct"
+      AC_MSG_RESULT([${msnative_struct}])
+    fi
+  fi
+fi
+
+
 ## ==================================================================
 ##                  Check for GTK+ GUI support
 ## ==================================================================
@@ -3873,6 +3939,34 @@ fi
 #Fixme: use AC native macros:
 #AM_PATH_GTK(1.0.2,, [AC_MSG_ERROR([GTK not in path])])
 #AM_PATH_GTKMM(0.9.5,, [AC_MSG_ERROR([GTK not in path])])
+
+#GLIB_REQUIRED_VERSION=2.0.0
+#AM_PATH_GLIB_2_0($GLIB_REQUIRED_VERSION, :,
+#  AC_MSG_ERROR([
+#*** GLIB $GLIB_REQUIRED_VERSION or better is required. The latest version of
+#*** GLIB is always available from ftp://ftp.gtk.org/.]),
+#  gobject gmodule)
+
+#GLIB_PACKAGES="gobject-2.0 gmodule-2.0"
+#PKG_CHECK_MODULES(DEP, glib-2.0 >= $GLIB_REQUIRED_VERSION $GLIB_PACKAGES, , AC_MSG_ERROR([
+#        *** GLib not found. You can find it on ftp://ftp.gtk.org
+#        *** Errors follow:
+#            $DEP_PKG_ERRORS]))
+
+#
+# Find pkg-config
+#
+#AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
+#if test x$PKG_CONFIG = xno ; then
+#  AC_MSG_ERROR([*** pkg-config not found. See http://www.freedesktop.org/software/pkgconfig/])
+#fi
+#
+#if $PKG_CONFIG --atleast-pkgconfig-version 0.14 ; then
+#  :
+#else
+#  AC_MSG_ERROR([*** pkg-config too old; version 0.14 or better required.])
+#fi
+
 
 PHP_CONFIGURE_PART(Checking for GTK+ GUI support:)
 
@@ -5143,33 +5237,33 @@ esac
 ##            check what the byte ordering is:
 ## ==================================================================
 
-	AC_MSG_CHECKING(byte ordering)
-
-    gcc order.c -o order
-
-    ORDER=`./order`
-
-	case "$ORDER" in
-		10) #least byte first
-			AC_DEFINE(HAVE_LEAST_BYTE_FIRST,1,[ ])
-			AC_MSG_RESULT(10)
-        ;;
-
-        01) #If it gives 01 then ntohs would be
-			#define ntohs(x) (x)
-			AC_DEFINE(HAVE_LEAST_BYTE_FIRST,0,[ ])
-			AC_MSG_RESULT(01)
-	        ;;
-
-        *)
-			AC_MSG_RESULT(Invalid byte order result: >>$ORDER<<)
-            #must not exit here untill I find a way for this to work on
-            #CygWin without re-runing autoconf
-			#exit 5
-	        ;;
-    esac
-
-	rm -f ./order.c ./order ./order.exe ./order.o ./order.tmp
+##	AC_MSG_CHECKING(byte ordering)
+##
+##    gcc order.c -o order
+##
+##    ORDER=`./order`
+##
+##	case "$ORDER" in
+##		10) #least byte first
+##			AC_DEFINE(HAVE_LEAST_BYTE_FIRST,1,[ ])
+##			AC_MSG_RESULT(10)
+##        ;;
+##
+##        01) #If it gives 01 then ntohs would be
+##			#define ntohs(x) (x)
+##			AC_DEFINE(HAVE_LEAST_BYTE_FIRST,0,[ ])
+##			AC_MSG_RESULT(01)
+##	        ;;
+##
+##        *)
+##			AC_MSG_RESULT(Invalid byte order result: >>$ORDER<<)
+##            #must not exit here untill I find a way for this to work on
+##            #CygWin without re-runing autoconf
+##			#exit 5
+##	        ;;
+##    esac
+##
+##	rm -f ./order.c ./order ./order.exe ./order.o ./order.tmp
 
 ## ==================================================================
 ##            Decide on default SQL driver
