Updates

diff --git a/aubit4glsrc/trunk/Makefile.in b/aubit4glsrc/trunk/Makefile.in
--- a/aubit4glsrc/trunk/Makefile.in
+++ b/aubit4glsrc/trunk/Makefile.in
@@ -23,7 +23,7 @@
 # | contact afalout@ihug.co.nz                                           |
 # +----------------------------------------------------------------------+
 #
-# $Id: Makefile.in,v 1.142 2004-03-19 02:43:44 afalout Exp $
+# $Id: Makefile.in,v 1.143 2004-03-19 03:59:48 afalout Exp $
 #
 
 ## ==================================================================
@@ -875,30 +875,40 @@ update:
 		if test "$$RET" = "0" ; then \
 			rm ./configure ; \
 			echo "./configure modified - removing it to avoid invalid merging"; \
+		else \
+			echo "./configure check OK."; \
 		fi
 	@echo "+--------------------------------------------------------------------+"
 	@echo "| CVS update started at `date`"
+	@echo "| Logging to /tmp/cvsupdate-aubit4gl.log                             |"
 	@echo "+--------------------------------------------------------------------+"	
-	@echo " "	
-	@cvs update -d -P > /tmp/cvsupdate-aubit4gl.log 2>&1
-	grep -v "cvs update: Updating" /tmp/cvsupdate-aubit4gl.log
+	@echo " "
+	@-cvs update -d -P > /tmp/cvsupdate-aubit4gl.log 2>&1; \
+		RET=$$?; if test "$$RET" != "0"; then echo "ERROR: cvs updated failed"; fi
+	@grep -v "cvs update: Updating" /tmp/cvsupdate-aubit4gl.log
+	@grep "cvs update: conflict" /tmp/cvsupdate-aubit4gl.log  > /dev/null ; \
+		RET=$$?; \
+		if test "$$RET" = "0" ; then \
+			grep "cvs update: conflict" /tmp/cvsupdate-aubit4gl.log; \
+			echo "WARNING: conflict(s) detected - see /tmp/cvsupdate-aubit4gl.log"; \
+		fi
 	@grep "\.in" /tmp/cvsupdate-aubit4gl.log  > /dev/null ; \
 		RET=$$?; \
 		if test "$$RET" = "0" ; then \
 			echo "WARNING: one or more .in files changed - run ./configure or ./config.status"; \
-		fi	
+		fi
 	@grep "configure" /tmp/cvsupdate-aubit4gl.log  > /dev/null ; \
 		RET=$$?; \
 		if test "$$RET" = "0" ; then \
 			echo "WARNING: configure changed - re-run ./configure"; \
 		fi
 #TODO: check for merge conflicts		
-	@echo " "	
-	@echo "+--------------------------------------------------------------------+"	
+	@echo " "
+	@echo "+--------------------------------------------------------------------+"
 	@echo "| CVS update finished at `date`"
 	@echo "| See /tmp/cvsupdate-aubit4gl.log for details                        |"
-	@echo "+--------------------------------------------------------------------+"	
-	@echo " "	
+	@echo "+--------------------------------------------------------------------+"
+	@echo " "
 
 
 ## ------------------------------------------------------------------
