Updates

diff --git a/aubit4gltest/trunk/run_tests b/aubit4gltest/trunk/run_tests
--- a/aubit4gltest/trunk/run_tests
+++ b/aubit4gltest/trunk/run_tests
@@ -34,6 +34,12 @@ EXPECT_TO_FAIL_TESTS_ECP="$EXPECT_TO_FAIL_TESTS_ECP \
 	685 686 687 689 690 691 693 694 697 698 699 700 701 702 703 704 710 711 \
 	712 713 714 715 716 717 718 \
 	"
+#Expected to fail using Informix p-code compiler
+EXPECT_TO_FAIL_IFX="102 225 227 228 234 248 251 254 319 487 531 536 537 540 \
+	541 542 543 554 555 558 560 561 562 569 571 572 585 590 600"
+#102 - dump_screen empty
+
+#more - arround 350 make sure you are running LDP server
 
 ######################
 #Tests that currently fail because of the errors in the test itself
@@ -87,84 +93,6 @@ cfunc_t usrcfuncs[] =
 	0, 0, 0
 }; 
 EOF
-}
-
-
-t1() {
-	
-cat<<EOF > prog.4gl
-main
-	display "1"
-	call prdate()
-	display "2"
-end main
-EOF
-
-cat<<EOF > cfunc.c
-#include <stdio.h>
-#include <time.h>
-prdate()
-{
-/* This program timestamps file FileX */
-long cur_date;
-extern int errno;
-FILE *fptr;
-time(&cur_date);
-fptr = fopen("time_file","a");
-fprintf(fptr,"FileX was accessed %s", ctime(&cur_date));
-printf("4GL: FileX was accessed %s", ctime(&cur_date));
-fclose(fptr);
-}
-EOF
-
-create_ifx_api
-
-rm -f time_file
-
-cfglgo ./fgiusr.c ./cfunc.c ./infx.o -o testfglgo
-#Gives:
-#./infx.o(.text+0xb4): undefined reference to `scr_dump'
-
-
-#cfglgo ./fgiusr.c ./cfunc.c ./infx.o -lncurses -o testfglgo
-#Gives:
-#feform.o(.text+0x184): undefined reference to `wgraphset'
-#feform.o(.text+0x1c4): undefined reference to `waddgch'
-#feform.o(.text+0x236): undefined reference to `waddgch'
-#feform.o(.text+0x28a): undefined reference to `wgraphset'
-
-
-fglpc ./prog.4gl
-./testfglgo ./prog.4go
-cat time_file
-exit
-
-}
-
-test_create_runner() {
-cat<<EOF > fgiusr.c 
-#include "fgicfunc.h"
-	cfunc_t usrcfuncs[] =
-	{
-		0, 0, 0
-	};
-EOF
-
-cc -c ./fgiusr.c -I${INFORMIXDIR}/incl/tools
-#cc -c /opt/aubit/aubit4glsrc/lib/extra_libs/infx_dump_screen/infx.c -I${INFORMIXDIR}/incl/tools
-#cfglgo fgiusr.o infx.o -o testfglgo -lncurses
-cfglgo fgiusr.o -o testfglgo
-
-cat<<EOF > x.4gl
-	MAIN
-			DISPLAY "Hello world...: "
-	END MAIN
-EOF
-
-fglpc x.4gl
-./testfglgo ./x.4go
-
-exit 
 }
 
 ##
@@ -230,7 +158,7 @@ OBJ_CUSTOM="$CUSTOM.o"
 		fi		
 		create_4js_api
 		
-		#decap strips away the termcap escape sequences
+		#decap program strips away the termcap escape sequences
 		EXEC="gcc $AUBITDIR_SRC/lib/extra_libs/infx_dump_screen/decap.c -o ./decap"
 		echo $EXEC
 		eval $EXEC
@@ -246,12 +174,19 @@ OBJ_CUSTOM="$CUSTOM.o"
 		DB=ix720
 		#4Js apprently DOES NOT use curses
 		#LFLAGS="-lkf \"-lncurses\""
+		
+		#/opt/aubit/gen4gl/fglbld/include/decimal.h
+		#/opt/informix/incl/tools/decimal.h
+		#/opt/querix/incl/decimal.h
+		FJS_CFLAGS="-cpf \"-DC4GL=1 -DFOURJS \
+			-I$FGLDIR/include -I$INFORMIXDIR/incl/tools \
+			-I$INFORMIXDIR/incl\""
+		
 		rm -f $FJSRUNNER
 		LINKER="esql"	#assumes there is Informix ESQL/C installed
-		SRC_CUSTOM="$AUBITDIR_SRC/lib/extra_libs/infx_dump_screen/fgl_prtscr.c \
-			$AUBITDIR_SRC/lib/extra_libs/infx_dump_screen/wrappers.c"
+		SRC_CUSTOM="$AUBITDIR_SRC/lib/extra_libs/infx_dump_screen/fgl_prtscr.c"
 		EXEC="fglmkrun -d $DB -o $FJSRUNNER -l $LINKER \
-			-cpf \"-DFOURJS -I$FGLDIR/include\" \
+			$FJS_CFLAGS \
 			-acs \"$SRC_CUSTOM\" \
 			$LFLAGS \
 			-ext fgiusr-4js.c"
@@ -751,9 +686,16 @@ for a in $FLAGS; do
 				if ! test -f $a/.cvsignore; then
                     cp template/.cvsignore $a
                     ADDED="$ADDED $a/.cvsignore"
-                #else
-					#echo '*.4go' >> $a/.cvsignore
-					#echo '*.4gi' >> $a/.cvsignore					
+                else
+					CVSIGNORE="$a/.cvsignore"
+					#CVSIGNORE_OUT=">> $CVSIGNORE"
+					ADDEXT_LIST=".4go .4gi"
+					for ADDEXT in $ADDEXT_LIST; do
+						if ! grep "$ADDEXT" "$CVSIGNORE" > /dev/null ; then 
+							#echo "*$ADDEXT" $CVSIGNORE_OUT
+							echo "*$ADDEXT" >> $CVSIGNORE
+						fi
+					done
 				fi
 	 		done
 
@@ -1132,11 +1074,11 @@ for a in $FLAGS; do
 		SHOW_TIME=1
         ;;
 
-	-update)
+	-update)		#Update tests souce code from CVS
 		cvs -q update -d -P 
 		exit
 		;;
-	-commit)
+	-commit)		#commit changes to tests source code to CVS
 		cvs -q commit
 		exit
 		;;
@@ -1176,7 +1118,9 @@ for a in $FLAGS; do
     -onlytui)       #Run only TUI tests listed in TUI_TESTS
 		ONLY_TUI=1
         ;;
-
+	-show-passed)	#Show full list of tests that passed 
+		SHOW_PASSED=1
+		;;
 	-norunec)       #don't run EC compiled programs
 		export SKIP_EC_RUN=1
         ;;
@@ -1572,28 +1516,33 @@ for a in $FLAGS; do
         ;;
 	-ifx-p)				#Use Informix P-code compiler instead of Aubit compiler
 		USE_COMP=ifx-p
+		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_TESTS $EXPECT_TO_FAIL_IFX"
 		#force Informix compiler to check all SQL for ANSI compliance
 		#I4GL_PC_FLAGS variable used in i4gl.mk
 		I4GL_PC_FLAGS="$I4GL_PC_FLAGS -ansi"
 		export I4GL_PC_FLAGS
 		if test -f "$IFX_RUNNER" ; then
-			echo "Note: using custom runner"
+			if test "$VERBOSE" = "1"; then
+				echo "Note: using custom runner"
+			fi
 			RUNNER=$IFX_RUNNER
 			FGLRUN=$IFX_RUNNER
 			export FGLRUN RUNNER
 		fi
+		#Indicate that we will use Informix RDBMS
+		USE_SQLITE=0; USE_ESQLI=1
 		;;
-
 	-4js-p)				#Use FourJs P-code compiler instead of Aubit compiler
 		USE_COMP=4js-p
 		if test -f "$FJSRUNNER" ; then
-			echo "Note: using custom runner"
+			if test "$VERBOSE" = "1"; then		
+				echo "Note: using custom runner"
+			fi
 			RUNNER=$FJSRUNNER
 			FGLRUN=$FJSRUNNER
 			export FGLRUN RUNNER
 		fi
 		;;
-		
 	-querix)				#Use Querix compiler instead of Aubit compiler
 		USE_COMP=querix
 		#Force Querix compiler to check SQL fro ANSI compliance
@@ -1732,6 +1681,9 @@ for a in $FLAGS; do
 		echo " -add-cvsignore Add .cvsignore from template to tests that don't have one"
 		echo " -record     record keystrokes to file while running program"
 		echo " -runner-[ifx|4js] Create p-code runner for specified compiler"		
+		echo " -update     Update tests souce code from CVS"
+		echo " -commit     commit changes to tests source code to CVS"
+
 		echo ""
 		
 		exit 0
@@ -1745,7 +1697,8 @@ for a in $FLAGS; do
 		echo " -err-with-log Send stderr to same destination that logs stdout"
 		echo " -short      Show only short summary"
 		echo " -show-time  Show timing results for each test"
-		echo " -itemised   Show result for each executed test"		
+		echo " -itemised   Show result for each executed test"
+		echo " -show-passed Show full list of tests that passed"
 		echo " -help       This help"
 
 		echo " FORMATS (resource files):"
@@ -3285,7 +3238,6 @@ do
 				echo "FIXME: check version"			
 			fi
 		fi
-	
 		if test "$A4GL_FAKELEXTYPE" = "PCODE" && test "$IS_PCODE_ENABLED" = "0"; then
 			SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
 			if test "$VERBOSE" = "1"; then
@@ -3385,14 +3337,38 @@ do
 			SKIP_NOMAKEFILE_LIST="$SKIP_NOMAKEFILE_LIST $a"
 			continue
 		fi
-		
-		if test "$USE_COMP" != "aubit" -a "$compat_test" != "1"; then 
-			SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
-			if test "$VERBOSE" = "1"; then
-				echo "$a Not run - $USE_COMP specified on non-compat test" >> $LOGFILE
+		if test "$USE_COMP" != "aubit"; then 
+			if test -f "$a/keys.in"; then 
+				SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
+				if test "$VERBOSE" = "1"; then
+					echo "$a Not run - $USE_COMP specified but test uses keys.in" >> $LOGFILE
+				fi
+				SKIP_KEYS_IN_LIST="$SKIP_KEYS_IN_LIST $a"
+				continue
 			fi
-			continue
-			SKIP_NOCOMPAT_LIST="$SKIP_NOCOMPAT_LIST $a"
+#temp disabled
+			#if test "$compat_test" != "1"; then
+			if test "1" = "2"; then
+				SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
+				if test "$VERBOSE" = "1"; then
+					echo "$a Not run - $USE_COMP specified on non-compat test" >> $LOGFILE
+				fi
+				SKIP_NOCOMPAT_LIST="$SKIP_NOCOMPAT_LIST $a"
+				continue
+			fi
+			
+			if test "$OLD_DESC" = "1" \
+				-a "$IS_DESCRIBED" = "1" \
+				-a "$IS_UNKNOWN_TEST" != "1" || \
+				test "$desc_txt" = "Old makefile"
+			then 
+				#Old makefiles don't know how to use non-Aubit compilers
+				SKIP_OLD_MAKEFILE_LIST="$SKIP_OLD_MAKEFILE_LIST $a"
+				if test "$VERBOSE" = "1"; then
+					echo "$a Not run - $USE_COMP specified on test having old makefile" >> $LOGFILE
+				fi
+				continue
+			fi
 		fi
 
 		###############################################################
@@ -3576,7 +3552,6 @@ do
 	
 	if test "$RET" = "$MAKE_EXPECT_CODE"
 	then
-
 		if test "$IS_EXPECT_TO_FAIL_TEST" = "1" ; then
 			if test "$SHOW_ITEM_RESULT" = "1"; then 
 				#echo " "
@@ -3587,6 +3562,7 @@ do
 			EXPECTED_TO_FAIL_PASSED_CNT=`(expr $EXPECTED_TO_FAIL_PASSED_CNT + 1) 2>/dev/null`
 		fi
 		PASS_CNT=`(expr $PASS_CNT + 1) 2>/dev/null`
+		PASS_LIST="$PASS_LIST $a"
 		if test "$IS_CERT_TEST" = "0"; then
 			if test "$SHOW_ITEM_RESULT" = "1"; then
 				echo "$a Pass - NOT CERTIFIED" >> $LOGFILE
@@ -3706,7 +3682,12 @@ fi
 if test "$SKIP_INVALID_LIST" != "" ; then 
 	echo "Skipped as invalid (PLEASE FIX OR OBSOLETE): $SKIP_INVALID_LIST" >> $LOGFILE
 fi
-
+if test "$SKIP_KEYS_IN_LIST" != ""; then
+	echo "Skipped as use keys.in: $SKIP_KEYS_IN_LIST" >> $LOGFILE
+fi
+if test "$SKIP_OLD_MAKEFILE_LIST" != ""; then 
+	echo "Skipped - has old makefile: $SKIP_OLD_MAKEFILE_LIST" >> $LOGFILE
+fi
 	SKIP_OTHER_LIST="\
 	$SKIP_PCODE_LIST $SKIP_TUI_LIST $SKIP_LONG_LIST $SKIP_CONSOLE_LIST \
 	$SKIP_NONDB_LIST $SKIP_DB_LIST $SKIP_NOSILENT_LIST \
@@ -3715,6 +3696,9 @@ fi
 	SKIP_OTHER_LIST=`echo $SKIP_OTHER_LIST`
 if test "$SKIP_OTHER_LIST" != "" ; then 
 	echo "Other skipped tests: $SKIP_OTHER_LIST" >> $LOGFILE
+fi
+if test "$PASS_LIST" != "" -a "$SHOW_PASSED" = "1"; then 
+	echo "Passed: $PASS_LIST" >> $LOGFILE
 fi
 if test "$FAIL_CNT" = "$EXPECTED_TO_FAIL_CNT" -o "$FAIL_CNT" -lt "$EXPECTED_TO_FAIL_CNT" ; then
 	echo "RESULT: EXPECTED" >> $LOGFILE
