Updates

diff --git a/aubit4gltest/trunk/run_tests b/aubit4gltest/trunk/run_tests
--- a/aubit4gltest/trunk/run_tests
+++ b/aubit4gltest/trunk/run_tests
@@ -6,16 +6,11 @@
 #
 ###########################################################################
 
-#check 252 and -ifx-p
-
 ######################
 #Tests that currently fail because of the bug in Aubit compiler (with -cert)
 EXPECT_TO_FAIL_TESTS="240 670 706"
 #240 (numeric formating) 670 (syntax errors in generated EC code)
 #706 (expression in SQL syntax error)
-
-#Not (yet) reported
-EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_TESTS "
 
 ######################
 #Tests that currently fail with -ecp (but work with -cert)
@@ -36,23 +31,36 @@ EXPECT_TO_FAIL_TESTS_ECP="$EXPECT_TO_FAIL_TESTS_ECP \
 	685 686 687 689 690 691 693 694 697 698 699 700 701 702 703 704 710 711 \
 	712 713 714 715 716 717 718 "
 
-	#Expected to fail using Informix/4Js/Querix compiler
-EXPECT_TO_FAIL_IFX="102 225 227 228 234 248 251 254 319 487 531 536 537 540 \
-	541 542 543 554 555 558 560 561 562 569 571 572 585 590 600"
-#102 - dump_screen empty
-EXPECT_TO_FAIL_4JS=""
-EXPECT_TO_FAIL_QUERIX="225 227 228 234 248 251 254 351 359 362 363 364 365 \
-	366 372 373 374 376 380 381 383 385 402 404 408 421 422 461 470 471 473 \
-	475 487 516 531 538 539 544 554 555 556 558 560 569 572 582 583 584 585 \
-	586 587 590 597 599 600 607 629 683 702"
+#Expected to fail using Informix/4Js/Querix compiler
+EXPECT_TO_FAIL_IFX="102 227 251 254 319 487 "
+#102,254 - dump_screen empty
+#227 - all 3 compilers give different ouptput
+#251 - Ifx & Q same, but Aubit different
+#319 - NULL in function call not accepted by i4gl
+#487 - ON KEY ("home") supported only by 4js and Aubit
+#NOT expected to fail:  706 (1) - but it worked when I tries again?
+
+EXPECT_TO_FAIL_4JS="216 225 240 348 349 364 372 373 380 381 531 536 565 566 \
+	573 577 626 627 628 629 630 631 632 633 634 635 636 670 675 706"
+EXPECT_TO_FAIL_QUERIX="234 240 351 359 362 363 364 365 366 372 373 374 376 380 \
+	381 383 385 402 404 408 421 422 461 470 471 473 475 487 516 531 538 539 544 \
+	556 582 583 584 586 587 597 599 607 629 670 683 702 706"
+#487 - ON KEY ("home") supported only by 4js and Aubit
+#TODO-add compat descriptor to:  537 540 541 542 543 561 562 571
+
+
+#dump_screen tests:  4 6 8 10 15 29 67 74 102 103 220 223 230 231 236 247 252 254
 
 ######################
 #Tests that currently fail because of the errors in the test itself
-INVALID_TESTS="375 377 684 105 705 253"
+INVALID_TESTS="375 377 684 105 705 253 255 256 257 258 259 229"
 #375,377 -"informix".systables (assumes user "informix" created test database)
-#684,253 - no test files
+#684,253,255 256 257 258 259 - no test files
 #105 - missing database schemma
 #705 - "It is not possible to convert between the specified types." with -ifx-p
+#229 - missing *.infx files (should be .expected)
+#230 - diff: screen10_M.infx: No such file or directory - ...etc...
+
 
 ##############################################################################
 #							Functions
@@ -67,7 +75,7 @@ look_for="$1:"
 change_to=$2
 test_no=$3
 makefile=`ls $CURR_DIR/$test_no/?akefile`
-if test "$makefile" = ""; then 
+if test "$makefile" = ""; then  240 706 225 234 248
 	echo "ERROR: can't get makefile name"
 	pwd
 	echo "$CURR_DIR/$test_no/?akefile"
@@ -553,6 +561,7 @@ USE_COMP=aubit
 MAKE_TARGET=run
 MAKE=gmake
 DB_HAS_TRANSACTION=NULL
+TEST_DB="test1"
 #decimals work ok with 'LC_NUMERIC' set to C
 #apparently they fail with anything else, like when LANG is set to 'de_DE@euro'
 export LC_NUMERIC="C"
@@ -666,9 +675,9 @@ if test "$PLATFORM" = "UNIX"; then
 	SO_EXT=.so
 fi
 
-DEFAULT_FLAGS="$DEFAULT_FLAGS -described -nolong -err-with-log -show-time"
+DEFAULT_FLAGS="$DEFAULT_FLAGS -described -nolong -err-with-log"
 #DEFAULT_FLAGS="$DEFAULT_FLAGS -stop"
-CERT_DEFAULT_FLAGS="$CERT_DEFAULT_FLAGS -described -nolong -err-with-log -show-time"
+CERT_DEFAULT_FLAGS="$CERT_DEFAULT_FLAGS -described -nolong -err-with-log"
 
 #######################
 #Apply platform defaults, see if we are to run multiple tests
@@ -699,7 +708,23 @@ for a in $FLAGS; do
    
    		-xxx)
 			VERBOSE=1
-   			change_setting "compat_test" "1" "351"
+
+#or perhaps a dumbed down expect script that just sends commands and does not
+#expect anything.
+
+(
+echo "q\c";
+sleep 2;
+echo "SMITH*";
+sleep 2;
+echo "<ESC>";
+sleep 1;
+echo "b";
+sleep 1;
+
+) | fglrun progam.42r
+
+
 			;;
 		-defaults)
             #If there is a conflict, USER flags will win
@@ -760,7 +785,7 @@ for a in $FLAGS; do
                 else
 					CVSIGNORE="$a/.cvsignore"
 					#CVSIGNORE_OUT=">> $CVSIGNORE"
-					ADDEXT_LIST=".pic"
+					#ADDEXT_LIST=".pic"
 					for ADDEXT in $ADDEXT_LIST; do
 						if ! grep "$ADDEXT" "$CVSIGNORE" > /dev/null ; then 
 							#echo "*$ADDEXT" $CVSIGNORE_OUT
@@ -1144,7 +1169,6 @@ for a in $FLAGS; do
     -show-time)     #Show timing results for each test
 		SHOW_TIME=1
         ;;
-
 	-update)		#Update tests souce code from CVS
 		cvs -q update -d -P 
 		exit
@@ -1161,7 +1185,9 @@ for a in $FLAGS; do
 		CLEAN_ALL=1
 		CLEAN=1		
 		;;
-		
+	-ignore-compat)	#Skip testing for test compatibility with no-aubit compilers
+		IGNORE_COMPAT=1
+		;;		
 	-stop)          #stop on error
 		ERROR_STOP=1
 	    ;;
@@ -1587,7 +1613,7 @@ for a in $FLAGS; do
         ;;
 	-ifx-p)				#Use Informix P-code compiler instead of Aubit compiler
 		USE_COMP=ifx-p
-		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_TESTS $EXPECT_TO_FAIL_IFX"
+		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_IFX"
 		#force Informix compiler to check all SQL for ANSI compliance
 		#I4GL_PC_FLAGS variable used in i4gl.mk
 		I4GL_PC_FLAGS="$I4GL_PC_FLAGS -ansi"
@@ -1602,10 +1628,19 @@ for a in $FLAGS; do
 		fi
 		#Indicate that we will use Informix RDBMS
 		USE_SQLITE=0; USE_ESQLI=1
+		
+		#get version
+		set `fglpc -v 2>/dev/null | head -1|sed -e 's/^INFORMIX-4GL Version //' -e 's/\./ /g'`
+		if test "$1" != "" -a "$2" != ""; then
+			I4GL_PCOMPILER_VER_MAJOR=$1
+			I4GL_PCOMPILER_VER_MINOR=$2				
+		else
+			echo "ERROR: Cannot get fglpc version."
+		fi
 		;;
 	-4js-p)				#Use FourJs P-code compiler instead of Aubit compiler
 		USE_COMP=4js-p
-		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_TESTS $EXPECT_TO_FAIL_4JS"
+		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_4JS"
 		if test -f "$FJSRUNNER" ; then
 			if test "$VERBOSE" = "1"; then		
 				echo "Note: using custom runner"
@@ -1616,10 +1651,30 @@ for a in $FLAGS; do
 		fi
 		#Indicate that we will use Informix RDBMS
 		USE_SQLITE=0; USE_ESQLI=1
+		if ! test -f "$TEST_DB.sch"; then 
+			#-c : Enable Database to 4GL data type conversion.
+			#Database type          4GL type
+			#--------------------------------------
+			#BOOLEAN                CHAR(1)
+			#INT8                   DECIMAL(19,0)
+			#SERIAL8                DECIMAL(19,0)
+			#Note- fglschema will fail without -c - not sure why
+			fglschema -c $TEST_DB
+			RET=$?
+			if test "$RET" != "0"; then 
+				rm -f $TEST_DB.sch
+			fi
+			if ! test -f "$TEST_DB.sch"; then
+				echo "ERROR: failed to create 4Js schema file for $TEST_DB"
+				exit 8
+			fi
+		fi
+		export FGLDBPATH=$CURR_DIR
+		
 		;;
 	-querix)				#Use Querix compiler instead of Aubit compiler
 		USE_COMP=querix
-		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_TESTS $EXPECT_TO_FAIL_QUERIX"
+		EXPECT_TO_FAIL_TESTS="$EXPECT_TO_FAIL_QUERIX"
 		#Force Querix compiler to check SQL fro ANSI compliance
 		#Q4GL_CC_FLAGS variable used in q4gl.mk
 		Q4GL_CC_FLAGS="$Q4GL_CC_FLAGS -ansi"
@@ -1718,6 +1773,7 @@ for a in $FLAGS; do
 		echo " -console    Use CONSOLE UI for tests"
 		echo " -gtk        Use GTK+ UI for running tests"		
 		echo " -tuin       use HL_TUIN UI for tests"
+		echo " -ignore-compat Skip testing for test compatibility with non-aubit compilers"		
 		echo ""
 		exit 0
         ;;
@@ -1966,9 +2022,6 @@ if test "$ALL_DB" = "1"; then
 	SHOW_TIME="0"
 fi
 
-#echo "SHOW_TIME=$SHOW_TIME"
-#exit
-
 HOSTNAME=`hostname`
 
 if test "$HOSTNAME" = "aptiva.falout.org"; then
@@ -1995,7 +2048,6 @@ else
 fi
 LOGFILE=$CURR_DIR/build.log
 RESLOGFILE=$CURR_DIR/resources.log
-TEST_DB=test1
 if test "$DEBUG" != ""; then
 	echo "** "
 	echo "** WARNING:"
@@ -3294,9 +3346,11 @@ do
 		if test "$NEED_TRANSACTION" = "1" ; then
 			echo "Database MUST have transactions enabled for this test."
 		fi
-		
-		#TODO: NEED_IFX_VERSION
-		
+
+		if test "$NEED_IFX_VERSION" != "" -a "$NEED_IFX_VERSION" != "0"; then
+			echo "Needs at least version $NEED_IFX_VERSION of Informix 4gl."
+		fi
+
 		echo ""
 		continue
 	fi
@@ -3312,7 +3366,27 @@ do
     if test "$NO_SKIP" != "1"; then
 		if test "$NEED_IFX_VERSION" != "" -a "$NEED_IFX_VERSION" != "0"; then
 			if test "$USE_COMP" = "ifx-p"; then
-				echo "FIXME: check version"			
+				set `echo $NEED_IFX_VERSION | sed -e 's/\./ /g'` #@echo "7.31"
+				NO_GO=0
+				if test "$1" -lt "$I4GL_PCOMPILER_VER_MAJOR"; then
+					NO_GO=1
+				else
+					if test "$I4GL_PCOMPILER_VER_MINOR" -lt "$2" -a "$1" = "$I4GL_PCOMPILER_VER_MAJOR"; then 
+						NO_GO=1
+					fi
+				fi
+				if test "$NO_GO" = "1"; then
+					SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
+					if test "$VERBOSE" = "1"; then
+						echo "Skipping test $a needs version $NEED_IFX_VERSION but have $I4GL_PCOMPILER_VER_MAJOR.$I4GL_PCOMPILER_VER_MINOR" >> $LOGFILE
+					fi
+					SKIP_NOVERSION_LIST="$SKIP_NOVERSION_LIST $a"
+					continue
+				else
+					if test "$VERBOSE" = "1"; then
+						echo "Version check OK: $NEED_IFX_VERSION >= $I4GL_PCOMPILER_VER_MAJOR.$I4GL_PCOMPILER_VER_MINOR" >> $LOGFILE
+					fi
+				fi
 			fi
 		fi
 		if test "$A4GL_FAKELEXTYPE" = "PCODE" && test "$IS_PCODE_ENABLED" = "0"; then
@@ -3414,7 +3488,18 @@ do
 			SKIP_NOMAKEFILE_LIST="$SKIP_NOMAKEFILE_LIST $a"
 			continue
 		fi
-		if test "$USE_COMP" != "aubit"; then 
+		if test "$USE_COMP" != "aubit"; then
+			if test "$USE_COMP" = "4js-p"; then
+				TMP=""
+				TMP=`find $CURR_DIR/$a -name "*.4gl" -exec grep -l aclfgl_dump_screen {} \;`
+				if test "$TMP" != ""; then 
+					if test "$VERBOSE" = "1"; then
+						echo "Skip $a - can't dump_screen with 4js"
+					fi
+					SKIP_DUMP_SCREEN="$SKIP_DUMP_SCREEN $a"
+					continue
+				fi
+			fi
 			if test -f "$a/keys.in"; then 
 				SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
 				if test "$VERBOSE" = "1"; then
@@ -3423,8 +3508,7 @@ do
 				SKIP_KEYS_IN_LIST="$SKIP_KEYS_IN_LIST $a"
 				continue
 			fi
-			if test "$compat_test" != "1"; then
-			#if test "1" = "2"; then
+			if test "$compat_test" != "1" -a "$IGNORE_COMPAT" != "1"; then
 				SKIP_CNT=`(expr $SKIP_CNT + 1) 2>/dev/null`
 				if test "$VERBOSE" = "1"; then
 					echo "$a Not run - $USE_COMP specified on non-compat test" >> $LOGFILE
@@ -3620,7 +3704,6 @@ do
 		cat $TIME_TMPFILE >> $CURR_DIR/$TIME_FILE
 	fi
 
-
     ################################
     #Check the result
 	if test "$VERBOSE" = "1" ; then 
@@ -3634,7 +3717,10 @@ do
 			#test is not described as compatible, but even using no-aubit compiler 
 			#it passed, so it should be described as compatible
 			NOT_COMPAT_BUT_PASSED="$NOT_COMPAT_BUT_PASSED $a"
-			change_setting "compat_test" "1" "$a"
+			#we do not want to automatically declare test compatible, just because
+			#one compiler can do it. NB; Querix sometimes fails with error, but 
+			#does not exit with error code
+			#change_setting "compat_test" "1" "$a"
 		fi
 	
 		if test "$IS_EXPECT_TO_FAIL_TEST" = "1" ; then
@@ -3661,6 +3747,10 @@ do
 		fi
 	else
 		FAIL_CNT=`(expr $FAIL_CNT + 1) 2>/dev/null`
+
+		if test "$compat_test" != "1" -a "$USE_COMP" != "aubit"; then
+			IS_EXPECT_TO_FAIL_TEST=1
+		fi
 		
 		if test "$IS_EXPECT_TO_FAIL_TEST" = "1" ; then 
 			TMPNOTE="(expected)"
@@ -3773,9 +3863,12 @@ fi
 if test "$SKIP_OLD_MAKEFILE_LIST" != ""; then 
 	echo "Skipped - has old makefile: $SKIP_OLD_MAKEFILE_LIST" >> $LOGFILE
 fi
+if test "$SKIP_DUMP_SCREEN" != ""; then 
+	echo "Skipped dump_screen tests: $SKIP_DUMP_SCREEN" >> $LOGFILE
+fi
 	SKIP_OTHER_LIST="\
 	$SKIP_PCODE_LIST $SKIP_TUI_LIST $SKIP_LONG_LIST $SKIP_CONSOLE_LIST \
-	$SKIP_NONDB_LIST $SKIP_DB_LIST $SKIP_NOSILENT_LIST \
+	$SKIP_NONDB_LIST $SKIP_DB_LIST $SKIP_NOSILENT_LIST $SKIP_NOVERSION_LIST\
 	$SKIP_GRAPHIC_LIST $SKIP_NOMAKEFILE_LIST $SKIP_NOCOMPAT_LIST"
 	#clipp it:
 	SKIP_OTHER_LIST=`echo $SKIP_OTHER_LIST`
