Replacing 4glpc and other build updates on Windows

diff --git a/aubit4glsrc/trunk/cint/make_cintlib b/aubit4glsrc/trunk/cint/make_cintlib
--- a/aubit4glsrc/trunk/cint/make_cintlib
+++ b/aubit4glsrc/trunk/cint/make_cintlib
@@ -1,22 +1,24 @@
 #!/bin/sh
 
-
 # Clean:
-
-rm -f makefile G__cpp_libA4GL_cint.C G__cpp_libA4GL_cint.h *.bak *~
-
-
+rm -f makefile G__cpp_libA4GL_cint.C G__cpp_libA4GL_cint.h *.bak *~ \
+ 	libA4GL_cint.def  make.bat
 if test "$1" = "-clean"; then 
 	exit 0
 fi	
 
-
-
 ################
 # Settings:
-
 source ../etc/aubitrc
-
+#WARNING: on Windows, CINTSYSDIR has to be in Windows format (not CygWin
+#or MSYS mapping (cygdrive) because makecint and cint executables are
+#native Windows executables and know nothing about path mapping
+case "$CINTSYSDIR" in *cygdrive*) 
+	echo "ERROR: CINTSYSDIR is in CygWin format"
+	exit 5
+	;;
+esac
+echo "CINTSYSDIR=$CINTSYSDIR"
 export CINTSYSDIR
 export PATH=$PATH:$CINTSYSDIR
 MAKECINT=$CINTSYSDIR/makecint
@@ -31,23 +33,22 @@ export LD_ELF_LIBRARY_PATH=$LD_LIBRARY_PATH
 
 ################
 # Check stuff;
-
 if test ! -f "$MAKECINT"; then 
 	echo "ERROR: file $MAKECINT does not exist"
 	exit 1
 fi
-
+if test "$COMSPEC" = ""; then 
+	SO_EXT=.so
+else
+	SO_EXT=.dll
+fi
 
 ################
 # Create Makefile:
-
-$MAKECINT -mk makefile -dl libA4GL_cint.so -p -H a4gl_cint_4gldef.h -l $USEAUBIT_PATH/lib/libaubit4gl.so
+$MAKECINT -mk makefile -dl libA4GL_cint$SO_EXT -p -H a4gl_cint_4gldef.h -l $USEAUBIT_PATH/lib/libaubit4gl$SO_EXT
 
 ################
 # Build library:
-
-echo $CINTSYSDIR
-
 if test -f "makefile" ; then 
 	#make CINTIPATH=-I$(CINTLIBDIR) CINTSYSDIR=$CINTBINDIR -f makefile
 	make -f makefile
@@ -56,17 +57,15 @@ else
 	exit 2
 fi
 
-
 ################
 # Copy lib to Aubit lib dir:
-
-if test -f libA4GL_cint.so; then 
-	cp libA4GL_cint.so ../lib
+if test -f libA4GL_cint$SO_EXT; then 
+	mv libA4GL_cint$SO_EXT ../lib
+	echo "CINT support library (lib/libA4GL_cint$SO_EXT) created."
 else
-	echo "ERROR: failed to create libA4GL_cint.so"
+	echo "ERROR: failed to create libA4GL_cint$SO_EXT"
 	exit 3
 fi
 
 exit 0
-
 
